### PR TITLE
Use JoinPath to construct vSphere url

### LINKED ISSUE #12856: Flaky handling of vcenter endpoint URL for vsphere datacenters
### What happened?
If user provides `/` at the end of `vsphere.endpoint` in Seed spec, user cluster creation fails with very cryptic errors like below..

```
cluster validation failed: cloud: Invalid value: "<redacted>": failed to create vCenter session: POST "//sdk": 400 Bad Request
failed to get datastore list: failed to create vCenter session: POST "//sdk": 400 Bad Request
failed to create REST API session: POST "//sdk": 400 Bad Request
```

I believe that this happens because a) we append `/sdk/` at the end of the endpoint URL provided and b) we then search for `//` to strip out http or https at the start BUT due to one slash at end the of endpoint and another slash at start of /sdk, we get match for `//` just before sdk instead of just before https and so the parsing logic fails.

I do not know where in the code this parsing happens.

### Expected behavior
Code should be resilient to handle presence or absence of `/` at the end of endpoint url. Also, error thrown can be made more explicit.

### How to reproduce the issue?
1. Create a vsphere datacenter definition in seed
2. ensure to add a `/` at the end of the endpoint url in configuration
3. Try to create a user cluster in that DC

### How is your environment configured?

- KKP version: 2.23.4 (But this issue exists from the start of the time ;o) )
- Shared or separate master/seed clusters?: Separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# Seed
apiVersion: kubermatic.k8c.io/v1
kind: Seed
metadata:
  name: seed-vsphere
  namespace: kubermatic
spec:
  country: DE
  datacenters:
    vsphere:
      country: DE
      location: Fra
      spec:
        vsphere:
          # rest of the spec removed for brevity
          # notice the / at the end
          endpoint: "https://my.awesome.vcenter.corp/"
```

</details>

### What cloud provider are you running on?
Vsphere

### What operating system are you running in your user cluster?
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
We shouldn't `fmt.Sprintf` the `/sdk` path for vSphere. Instead, we should use `url.JoinPath` to append it after parsing the initial datacenter URL. This makes endpoint parsing more robust.

**Which issue(s) this PR fixes**:

Fixes #12856

**What type of PR is this?**
/kind bug
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
No longer fail constructing vSphere endpoint when a `/` suffix is present in the datacenter configuration
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/vsphere/client.go [hunk 1]
```diff
@@ -36,11 +36,13 @@ type RESTSession struct {
...
 
 func newRESTSession(ctx context.Context, dc *kubermaticv1.DatacenterSpecVSphere, username, password string, caBundle *x509.CertPool) (*RESTSession, error) {
-	u, err := url.Parse(fmt.Sprintf("%s/sdk", dc.Endpoint))
+	endpoint, err := url.Parse(dc.Endpoint)
 	if err != nil {
 		return nil, err
 	}
 
+	u := endpoint.JoinPath("/sdk")
+
```
Comment (xrstf) [inline pkg/provider/cloud/vsphere/client.go:45]: You could use `url.JoinPath()` instead, which does exactly what these 2 statements do.

Comment (embik) [reply pkg/provider/cloud/vsphere/client.go:45]: Should have checked the function signature, I thought that one required `url.URL` parameters. Will update the PR tomorrow.

Comment (embik) [reply pkg/provider/cloud/vsphere/client.go:45]: I'm surprised `url.JoinPath` doesn't throw an error though. What happens to URL parsing that we currently have? Are we losing anything from not running it through the parser?

Comment (embik) [reply pkg/provider/cloud/vsphere/client.go:45]: Actually, `url.JoinPath` produces a string, but we need an  `*url.URL` later.

**Review by xrstf — APPROVED** [review]
/approve

you and your excuses
