### PR TITLE
fix displayed GCP disk types

### LINKED ISSUE #6715: Match disk types for GCP image types
The balanced disk type doesn't work for some instance types. The same for the SSD type

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**: fix displayed GCP disk types. I've checked all GCP machine standards with `pd-balanced` disk type and all instances were failing. The only way was to filter out this disk type.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6715

```release-note
NONE
```

### CODE REVIEW

File: pkg/handler/common/provider/gcp.go [hunk 1]
```diff
@@ -169,7 +171,8 @@ func GCPDiskTypesWithClusterCredentialsEndpoint(ctx context.Context, userInfoGet
 
 func ListGCPDiskTypes(ctx context.Context, sa string, zone string) (apiv1.GCPDiskTypeList, error) {
 	diskTypes := apiv1.GCPDiskTypeList{}
-
+	// TODO: There are some issues at the moment with local-ssd and pd-balanced, that's why it is disabled at the moment.
```
Comment (lsviben) [inline pkg/handler/common/provider/gcp.go:174]: do we have some issue or something to reference here?
