### PR TITLE
Fix the router-subnet-link cleanup issue in OpenStack

### LINKED ISSUE #14050: KKP should delete router-links that it created, even if it did not create the subnet
### What happened?

During cluster creation, it's possible to choose a pre-existing security group, network and subnet to use - instead of having KKP create new ones (= default). This works very well and serves several advanced use cases.

However, if a pre-existing subnet is provided, KKP does NOT add the `kubermatic.k8c.io/cleanup-openstack-router-subnet-link-v2` finalizer. Thus it will not delete the link and UC deletion will be stuck as the router can't be deleted (since a port is still attached to it).

### Expected behavior

KKP deletes the link before it attempts to delete the router, because the `kubermatic.k8c.io/cleanup-openstack-router-subnet-link-v2` finalizer is present on the cluster resource. Thus the UC deletion will be able successful.

### How to reproduce the issue?

1. Create a network and subnet in OpenStack
2. Create a UC and choose the previously created network and subnet
3. Look at the cluster resource's finalizers and notice there's one too few
4. Delete the UC
5. Notice that deletion is stuck
6. Find this event when describing the cluster:
```
  Warning  ReconcilingError          13m (x21 over 23m)  kkp-cloud-controller                             failed cloud provider cleanup: failed to delete router '78608eef-9d5a-4606-873d-b4c4cfdada89': Expected HTTP response code [202 204] when accessing [DELETE https://network.api.zhw.cloud.switch.ch/v2.0/routers/78608eef-9d5a-4606-873d-b4c4cfdada89], but got 409 instead
{"NeutronError": {"type": "RouterInUse", "message": "Router 78608eef-9d5a-4606-873d-b4c4cfdada89 has ports still attached: 08f12133-0556-4a9f-811a-6efdb85ee3d5", "detail": ""}}
```

### How is your environment configured?

- KKP version: v2.26.2
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

N/A

### Additional information

This is very similar to #14049, just that essentially the opposite thing is happening and causing a problem.

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
**What this PR does / why we need it**:
This PR addresses the router-subnet-link cleanup issue in OpenStack when creating a user cluster with an existing network and subnet. The primary cause of the problem is that the cluster resource lacks the `kubermatic.k8c.io/cleanup-openstack-router-subnet-link-v2` finalizer, which is essential for ensuring that links attached to the router are properly cleaned up. As a result, when attempting to delete the cluster, the router fails to be deleted due to lingering ports still attached to it.

**Which issue(s) this PR fixes**:

Fixes #14050

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixed router-subnet-link cleanup for OpenStack user clusters created with existing networks and subnets.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/openstack/provider.go [hunk 1]
```diff
@@ -622,8 +622,15 @@ func linkSubnetToRouter(netClient *gophercloud.ServiceClient, cluster *kubermati
 		if err != nil {
 			return err
 		}
-		kubernetes.AddFinalizer(cluster, finalizer)
+		// Add the Link finalizer
+		_, err = update(ctx, cluster.Name, func(cluster *kubermaticv1.Cluster) {
+			kubernetes.AddFinalizer(cluster, finalizer)
+		})
+		if err != nil {
+			return fmt.Errorf("failed to add RouterSubnetLinkCleanupFinalizer in the cluster spec: %w", err)
```
Comment (xrstf) [inline pkg/provider/cloud/openstack/provider.go]: Replace the concrete finalizer with %s and use `finalizer` to make the error correct.

**Review by kron4eg — APPROVED** [review]
/approve
