### PR TITLE
validate length of EAR encryption key

### LINKED ISSUE #10829: EAR enabled with invalid encryption key gets stuck in Pending state
If we enable EAR with an invalid value for encryption key say "password" then it gets in Pending state. 

In Pending state any changes are rejected. 

We should check for this invalid key earlier to avoid this situation. 

To reproduce: 

`kubectl  --type merge --patch-file patch.yaml` 

patch.yaml
```
spec:
  encryptionConfiguration:
    enabled: true
    resources:
      - secrets
    secretbox:
      keys:
        - name: encryption-key-2022-01
          value: password
```

### PR DESCRIPTION
**Pull request by PratikDeoghare**
**What this PR does / why we need it**:
 Validates length of the encryption key used for EAR. Currently the length is not validated.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/10829

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go [hunk 1]
```diff
@@ -269,6 +335,38 @@ func (r *Reconciler) reconcile(ctx context.Context, log *zap.SugaredLogger, clus
 	}
 }
 
+func (r *Reconciler) validateSecretRef(cluster *kubermaticv1.Cluster, log *zap.SugaredLogger) (*reconcile.Result, error) {
+	if hasSecretKeyRef(cluster) {
```
Comment (PratikDeoghare) [inline pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go]: change to `!hasKeyRef { return } `

File: pkg/validation/cluster_test.go [hunk 2]
```diff
@@ -886,3 +886,63 @@ func TestValidateGCPCloudSpec(t *testing.T) {
...
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			t.Log(test.name)
+			err := validateEncryptionConfiguration(test.clusterSpec, field.NewPath("spec", "encryptionConfiguration"))
+			t.Logf("%+v", err)
+			if (err != nil) != test.expectErr {
+				t.Logf("expected error: %t, got: %+v", test.expectErr, err)
```
Comment (embik) [inline pkg/validation/cluster_test.go]: The whole logging here is probably for debugging the test, but it should probably be removed and as far as I can see, this test can currently simply not fail.

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/validation/cluster_test.go [hunk 3]
```diff
@@ -886,3 +886,61 @@ func TestValidateGCPCloudSpec(t *testing.T) {
...
+			expectErr: true,
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			err := validateEncryptionConfiguration(test.clusterSpec, field.NewPath("spec", "encryptionConfiguration"))
+			if (err != nil) != test.expectErr {
+				t.Logf("expected error: %t, got: %+v", test.expectErr, err)
+			}
```
Comment (embik) [inline pkg/validation/cluster_test.go]: This still doesnt fail the test if the error is not the expected error, no? I think we should be doing something like:

```go
assert.Equal(t, test.expectedError, err)
```

As the other test cases in this file do.

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/validation/cluster_test.go (hunk 3 above)
Comment (PratikDeoghare) [reply pkg/validation/cluster_test.go]: Yes. Can make it happen.

Comment (PratikDeoghare) [reply pkg/validation/cluster_test.go]: How about that?

File: cmd/seed-controller-manager/main.go [hunk 4]
```diff
@@ -185,6 +185,11 @@ Please install the VerticalPodAutoscaler according to the documentation: https:/
 		log.Fatalw("Unable to create the seed getter", zap.Error(err))
 	}
 
+	seedClientGetter, err := seedClientGetterFactory(rootCtx, mgr.GetClient())
+	if err != nil {
+		log.Fatalw("Unable to create the seed client getter", zap.Error(err))
+	}
+
```
Comment (embik) [inline cmd/seed-controller-manager/main.go]: I don't think this (and all the other stuff to get this into the EAR controller) is necessary; The seed-controller-manager mainly talks to its assigned Seed, so it only needs one Seed client. You can see other controllers using `mgr.GetClient()` to get a seed client here:

https://github.com/kubermatic/kubermatic/blob/b4a7df6129ef6a978a3f57b926ff24f987f8a429/pkg/controller/seed-controller-manager/preset-controller/controller.go#L69

https://github.com/kubermatic/kubermatic/blob/b4a7df6129ef6a978a3f57b926ff24f987f8a429/pkg/controller/seed-controller-manager/constraint-template-controller/controller.go#L85

https://github.com/kubermatic/kubermatic/blob/b4a7df6129ef6a978a3f57b926ff24f987f8a429/pkg/controller/seed-controller-manager/operating-system-profile-synchronizer/controller.go#L84

**Review by embik — CHANGES_REQUESTED** [review]

File: cmd/seed-controller-manager/main.go (hunk 4 above)
Comment (embik) [reply cmd/seed-controller-manager/main.go]: Using the client embedded into the `Reconciler` struct for the encryption-at-rest-controller should suffice for what the code does, no?

https://github.com/kubermatic/kubermatic/blob/b4a7df6129ef6a978a3f57b926ff24f987f8a429/pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go#L90

Comment (PratikDeoghare) [reply cmd/seed-controller-manager/main.go]: Yes. It should work. I thought seed-ctrl-mgr could run outside the seeds it is managing and then it would be necessary to get the right client. 

But I see no other ctrl hanging on the seed-ctrl-mgr doing this. 

Will cleanup. :+1:

Comment (PratikDeoghare) [reply cmd/seed-controller-manager/main.go]: Why is there `seedGetter` tho since you already know the seed?

Comment (embik) [reply cmd/seed-controller-manager/main.go]: I assume because you might want to read information from the `Seed` object (e.g. specific configuration to change controller behaviour).

File: pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go [hunk 5]
```diff
@@ -177,9 +179,62 @@ func (r *Reconciler) Reconcile(ctx context.Context, request reconcile.Request) (
 	return *result, err
 }
 
+func getSecretKeyValue(client ctrlruntimeclient.Client, ref *corev1.SecretKeySelector, namespace string) ([]byte, error) {
+	secret := corev1.Secret{}
+	if err := client.Get(context.Background(), ctrlruntimeclient.ObjectKey{
```
Comment (embik) [inline pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go]: This should take a `ctx context.Context` argument and pass that to the client calls.

File: pkg/provider/kubernetes/seed.go [hunk 6]
```diff
@@ -144,7 +144,7 @@ func SeedsGetterFactory(ctx context.Context, client ctrlruntimeclient.Client, na
 	}, nil
 }
 
-func SeedKubeconfigGetterFactory(ctx context.Context, client ctrlruntimeclient.Client) (provider.SeedKubeconfigGetter, error) {
+func SeedKubeconfigGetterFactory(ctx context.Context, client ctrlruntimeclient.Reader) (provider.SeedKubeconfigGetter, error) {
```
Comment (embik) [inline pkg/provider/kubernetes/seed.go]: Don't change this :D

File: pkg/validation/cluster_test.go [hunk 7]
```diff
@@ -886,3 +886,66 @@ func TestValidateGCPCloudSpec(t *testing.T) {
 		})
 	}
 }
+
+func TestValidateEncryptionConfiguration(t *testing.T) {
```
Comment (embik) [inline pkg/validation/cluster_test.go:890]: Can we also add a test with invalid base64?

File: cmd/seed-controller-manager/wrappers_ce.go [hunk 8]
```diff
@@ -24,7 +24,6 @@ import (
 
 	"k8c.io/kubermatic/v2/pkg/provider"
 	"k8c.io/kubermatic/v2/pkg/provider/kubernetes"
-
```
Comment (embik) [inline cmd/seed-controller-manager/wrappers_ce.go]: don't remove this line.

File: cmd/seed-controller-manager/wrappers_ee.go [hunk 9]
```diff
@@ -27,7 +27,6 @@ import (
 	groupprojectbindingcontroller "k8c.io/kubermatic/v2/pkg/ee/group-project-binding/controller"
 	resourcequotaseedcontroller "k8c.io/kubermatic/v2/pkg/ee/resource-quota/seed-controller"
 	"k8c.io/kubermatic/v2/pkg/provider"
-
```
Comment (embik) [inline cmd/seed-controller-manager/wrappers_ee.go]: same here.

**Review by embik — CHANGES_REQUESTED** [review]
Sorry that I keep throwing curveballs at you 😅

**Review by embik — APPROVED** [review]
/lgtm
