### PR TITLE
Remove deprecated setting in cilium application

### LINKED ISSUE #12840: Upgrade to Cilium 1.14 after KKP upgrade fails
### What happened?

For when upgrading from a KKP 2.23 environment, #12830 has fixed the problem with immutable values rejecting the changes to the `ApplicationInstallation`.

Unfortunately, upgrading Cilium to 1.14 afterwards is broken. The `ApplicationInstallation` gets updated, but  the `user-cluster-controller-manager` is logging:

```json
{"level":"error","time":"2023-11-10T14:35:14.707Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-app-installation-controller","object":{"name":"cilium","namespace":"kube-system"},"namespace":"kube-system","name":"cilium","reconcileID":"78ada97b-3cd7-4ccd-9576-e4afd6173823","error":"handling installation of application installation: execution error at (cilium/templates/cilium-configmap.yaml:886:8): Value ipam.operator.clusterPoolIPv4PodCIDR removed, use ipam.operator.clusterPoolIPv4PodCIDRList instead"}
```

This is due to the way the `ApplicationInstallation` looks like after the upgrade. It has both ` ipam.operator.clusterPoolIPv4PodCIDR` and `ipam.operator.clusterPoolIPv4PodCIDRList` set. The intention was to migrate away from the former, but it's probably not correctly overridden/patched to be empty.

**This only happens when you come from KKP 2.23!**

### Expected behavior

Cilium upgrade to 1.14 works in KKP 2.24.

### How to reproduce the issue?

1. Deploy KKP 2.23
2. Create user cluster with Cilium 1.13
3. Upgrade KKP to `main` branch version
4. Attempt to upgrade Cilium in user clustrer to 1.14 after the KKP upgrade finished

### How is your environment configured?

- KKP version: `main`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

`ApplicationInstallation` for `cilium`:

<details>

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  creationTimestamp: "2023-11-10T12:37:00Z"
  finalizers:
  - kubermatic.k8c.io/cleanup-application-installation
  generation: 3
  labels:
    apps.kubermatic.k8c.io/managed-by: kkp
    apps.kubermatic.k8c.io/type: cni
  name: cilium
  namespace: kube-system
  resourceVersion: "31404"
  uid: 613a02a9-d11d-4bf0-9d32-c43cc5127f08
spec:
  applicationRef:
    name: cilium
    version: 1.14.3
  deployOptions:
    helm:
      timeout: 10m0s
      wait: true
  namespace:
    create: false
    name: kube-system
  reconciliationInterval: 1h0m0s
  values:
    certgen:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    cni:
      exclusive: false
    hubble:
      relay:
        enabled: true
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
      tls:
        auto:
          method: cronJob
      ui:
        backend: {}
        enabled: true
        frontend: {}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
    ipam:
      operator:
        clusterPoolIPv4MaskSize: "24"
        clusterPoolIPv4PodCIDR: 172.25.0.0/16
        clusterPoolIPv4PodCIDRList:
        - 172.25.0.0/16
    k8sServiceHost: <redacted>
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    operator:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      replicas: 1
      securityContext:
        seccompProfile:
          type: RuntimeDefault
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
status:
  applicationVersion:
    template:
      source:
        helm:
          chartName: cilium
          chartVersion: 1.14.3
          url: oci://quay.io/kubermatic/helm-charts
    version: 1.14.3
  conditions:
    ManifestsRetrieved:
      lastHeartbeatTime: "2023-11-10T14:30:23Z"
      message: application's source successfully downloaded
      observedGeneration: 3
      reason: DownloadSourceSuccessful
      status: "True"
    Ready:
      lastHeartbeatTime: "2023-11-10T14:30:24Z"
      lastTransitionTime: "2023-11-10T14:30:24Z"
      message: 'execution error at (cilium/templates/cilium-configmap.yaml:886:8):
        Value ipam.operator.clusterPoolIPv4PodCIDR removed, use ipam.operator.clusterPoolIPv4PodCIDRList
        instead'
      observedGeneration: 3
      reason: InstallationFailed
      status: "False"
  helmRelease:
    info:
      description: Upgrade complete
      firstDeployed: "2023-11-10T12:37:02Z"
      lastDeployed: "2023-11-10T14:18:45Z"
      notes: |2

                You have successfully installed Cilium with Hubble Relay and Hubble UI.

        Your release version is 1.13.8.

        For any further help, visit https://docs.cilium.io/en/v1.13/gettinghelp
      status: deployed
    name: kube-system-cilium
    version: 5
  method: helm
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

This is a release blocker for 2.24.

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
Remove deprecated `clusterPoolIPv4PodCIDR` field leftover during upgrade.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12840

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go [hunk 1]
```diff
@@ -369,6 +369,12 @@ func ApplicationInstallationReconciler(cluster *kubermaticv1.Cluster, overwriteR
 				return app, fmt.Errorf("failed to merge CNI values: %w", err)
 			}
 
+			if cluster.Spec.CNIPlugin.Type == kubermaticv1.CNIPluginTypeCilium {
+				ipam := values["ipam"].(map[string]any)
+				operator := ipam["operator"].(map[string]any)
+				delete(operator, "clusterPoolIPv4PodCIDR")
+			}
```
Comment (embik) [inline pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go:376]: Will this work? Can you maybe test against the upgrade environment? If the field is removed, I suspect it might be omitted from the patch and won't change?

Comment (cnvergence) [reply pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go:376]: It might be the case here, let me check it first then

**Review by embik — APPROVED** [review]
/approve

**Comment by wozniakjan** [comment]
@cnvergence @embik , looks like the nodeport envoy proxy struggles to get operational
```
[2023-11-13T12:55:57+00:00] Waiting for Deployments to roll out...
[2023-11-13T12:55:57+00:00] Not all Deployments have finished rolling out, namely: kubermatic-seed-controller-manager	nodeport-proxy-envoy
Retry 1/9 exited 1, retrying in 1 seconds...
[2023-11-13T12:55:58+00:00] Not all Deployments have finished rolling out, namely: kubermatic-seed-controller-manager	nodeport-proxy-envoy
Retry 2/9 exited 1, retrying in 2 seconds...
[2023-11-13T12:56:01+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 3/9 exited 1, retrying in 4 seconds...
[2023-11-13T12:56:05+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 4/9 exited 1, retrying in 8 seconds...
[2023-11-13T12:56:13+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 5/9 exited 1, retrying in 16 seconds...
[2023-11-13T12:56:29+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 6/9 exited 1, retrying in 32 seconds...
[2023-11-13T12:57:01+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 7/9 exited 1, retrying in 64 seconds...
[2023-11-13T12:58:05+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 8/9 exited 1, retrying in 128 seconds...
[2023-11-13T13:00:13+00:00] Not all Deployments have finished rolling out, namely: nodeport-proxy-envoy
Retry 9/9 exited 1, no more retries left.
```
is that a known flake? could be related to cilium changes introduced here maybe.

**Comment by embik** [comment]
@wozniakjan I suspect it's related to the CI registry mirror. Also see #eng on Slack.

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve
