### PR TITLE
VCD: Move CSI controller to seed cluster

### LINKED ISSUE #13021: VMware Cloud Director CSI driver is broken
Post https://github.com/kubermatic/kubermatic/pull/12936, it seems that the CSI driver for VMware Cloud Director is broken.

The pod for  CSI controller is crashing with the following logs:

```
E0201 09:21:01.850229       1 disks.go:888] error occurred when getting defined entity [ip26kxrp44]; skipping upgrade of CSI status section: [{"minorErrorCode":"ACCESS_TO_RESOURCE_IS_FORBIDDEN","message":"[ 34bf6503-e7f1-4293-8b3e-196e498fda7a ] This operation is denied.","stackTrace":null}]
E0201 09:21:02.141112       1 driver.go:148] unable to add error [RdeUpgradeError] into [CSI.Errors] in RDE [ip26kxrp44], failed to get RDE [ip26kxrp44] when adding error to the errorSet of [csi] ; expected http response [200], obtained [403]: resp: ["{\"minorErrorCode\":\"ACCESS_TO_RESOURCE_IS_FORBIDDEN\",\"message\":\"[ e7fb5c36-8af7-4309-a253-738efcec595a ] This operation is denied.\",\"stackTrace\":null}"]: [403 Forbidden]
panic: error while setting up driver: [CSI section upgrade failed when CAPVCD RDE is present, [error when getting defined entity [ip26kxrp44] from VCD: [403 Forbidden]; skipping upgrade of CSI status section to Version [1.5.0]]]

goroutine 1 [running]:
main.runCommand()
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:153 +0x4d6
main.main.func2(0xc0002a0000?, {0x123916f?, 0x4?, 0x4?})
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:67 +0x17
github.com/spf13/cobra.(*Command).execute(0xc0002a0000, {0xc0000340b0, 0x4, 0x4})
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a0000)
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:87 +0x228
```

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
For VCD, this PR moves the CSI controller plugin to the user cluster namespace in the seed cluster. 

**Which issue(s) this PR fixes**:

Towards https://github.com/kubermatic/kubermatic/issues/11985, fixes #13021 

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:
**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
VMware Cloud Director: Move CSI controller to seed cluster
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/test pre-kubermatic-e2e-vmware-cloud-director-ubuntu-1.29

This will fail as it was broken after https://github.com/kubermatic/kubermatic/pull/12936

**Comment by xrstf** [comment]
Which part of this is fixing #13021? just out of interest and in case we need to fix other release branches.

**Comment by ahmedwaleedmalik** [comment]
> Which part of this is fixing #13021? just out of interest and in case we need to fix other release branches.

Is https://github.com/kubermatic/kubermatic/pull/12936 already available in other release branches? That's pretty strange.

Anyways, upgrading RDE is a capability that was built around the VMware Cloud Director CSE offering, which is not relevant to us. So dropping that flag fixed the issue https://github.com/kubermatic/kubermatic/pull/13020/commits/1ede2c69a3517f2035bb20e4da9398b4d1cc4185. This was working fine until VCD CSI 1.3.2 but after the upgrade in https://github.com/kubermatic/kubermatic/pull/12936  it started failing.

File: pkg/controller/user-cluster-controller-manager/resources/reconciler.go [hunk 1]
```diff
@@ -1408,6 +1414,35 @@ func (r *reconciler) ensureKubernetesDashboardResourcesAreRemoved(ctx context.Co
 	return nil
 }
 
+func (r *reconciler) ensureOrphanedVMwareCloudDirectorCSIResourcesAreRemoved(ctx context.Context) error {
```
Comment (xrstf) [inline pkg/controller/user-cluster-controller-manager/resources/reconciler.go]: Why is this necessary? When re-applying the CSI addon, orphaned resources should automatically be removed, no?

Comment (ahmedwaleedmalik) [reply pkg/controller/user-cluster-controller-manager/resources/reconciler.go]: I wasn't sure if they are removed automatically. But if they are, we can drop this bit of code.

File: pkg/resources/csi/vmwareclouddirector/deployment.go [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+	"k8c.io/reconciler/pkg/reconciling"
+
+	appsv1 "k8s.io/api/apps/v1"
+	corev1 "k8s.io/api/core/v1"
+	"k8s.io/apimachinery/pkg/api/resource"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+)
+
+const (
+	csiVersion = "1.5.0"
```
Comment (xrstf) [inline pkg/resources/csi/vmwareclouddirector/deployment.go:35]: Please add this to the `hack/versions.yaml`

File: pkg/resources/csi/vmwareclouddirector/deployment.go [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+				},
+				{
+					Name:            "vcd-csi-plugin",
+					ImagePullPolicy: corev1.PullIfNotPresent,
+					Image:           registry.Must(data.RewriteImage("projects.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver:" + csiVersion)),
+					Command:         []string{"/opt/vcloud/bin/cloud-director-named-disk-csi-driver"},
+					Args: []string{
+						"--endpoint=$(CSI_ENDPOINT)",
+						"--cloud-config=/etc/kubernetes/vcloud/config",
+						"--v=5",
```
Comment (xrstf) [inline pkg/resources/csi/vmwareclouddirector/deployment.go:214]: Can we lower the default verbosity to something reasonable like 2?

Comment (ahmedwaleedmalik) [reply pkg/resources/csi/vmwareclouddirector/deployment.go:214]: This has been copied from the addon and kept as is; 5 looks fine to me.

File: pkg/controller/user-cluster-controller-manager/resources/reconciler.go (hunk 1 above)
Comment (ahmedwaleedmalik) [reply pkg/controller/user-cluster-controller-manager/resources/reconciler.go]: Removed
