### PR TITLE
fix duplicates in collecting go metrics

### LINKED ISSUE #15081: Failed to parse metrics from master-controller-manager
### What happened?

The kubermatic-master-controller-manager pod is failing Prometheus scrapes with HTTP 500 errors due to duplicate metric collector registration. The `/metrics` endpoint returns an error indicating that multiple metrics (go_gc_duration_seconds, go_goroutines, etc.) were "collected before with the same name and label values".

**Error details:**
<details>

```bash
$ curl -s 'http://localhost:9090/api/v1/targets' | jq '.data.activeTargets[] | select(.health == "down")'
{
  "discoveredLabels": {
    "__address__": "172.27.0.93:8085",
    "__meta_kubernetes_namespace": "kubermatic",
    "__meta_kubernetes_pod_annotation_fluentbit_io_parser": "json_iso",
    "__meta_kubernetes_pod_annotation_prometheus_io_port": "8085",
    "__meta_kubernetes_pod_annotation_prometheus_io_scrape": "true",
    "__meta_kubernetes_pod_annotationpresent_fluentbit_io_parser": "true",
    "__meta_kubernetes_pod_annotationpresent_prometheus_io_port": "true",
    "__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape": "true",
    "__meta_kubernetes_pod_container_id": "containerd://91dc717c53e876408a803a2c4f70d5d049a72021b55f33035d7ec657d2f128ba",
    "__meta_kubernetes_pod_container_image": "quay.io/kubermatic/kubermatic-ee:v2.29.0-alpha.1",
    "__meta_kubernetes_pod_container_init": "false",
    "__meta_kubernetes_pod_container_name": "controller-manager",
    "__meta_kubernetes_pod_container_port_name": "metrics",
    "__meta_kubernetes_pod_container_port_number": "8085",
    "__meta_kubernetes_pod_container_port_protocol": "TCP",
    "__meta_kubernetes_pod_controller_kind": "ReplicaSet",
    "__meta_kubernetes_pod_controller_name": "kubermatic-master-controller-manager-69f4fd9c5f",
    "__meta_kubernetes_pod_host_ip": "172.31.11.151",
    "__meta_kubernetes_pod_ip": "172.27.0.93",
    "__meta_kubernetes_pod_label_app_kubernetes_io_name": "kubermatic-master-controller-manager",
    "__meta_kubernetes_pod_label_app_kubernetes_io_version": "v2.29.0-alpha.1",
    "__meta_kubernetes_pod_label_pod_template_hash": "69f4fd9c5f",
    "__meta_kubernetes_pod_labelpresent_app_kubernetes_io_name": "true",
    "__meta_kubernetes_pod_labelpresent_app_kubernetes_io_version": "true",
    "__meta_kubernetes_pod_labelpresent_pod_template_hash": "true",
    "__meta_kubernetes_pod_name": "kubermatic-master-controller-manager-69f4fd9c5f-4b8cj",
    "__meta_kubernetes_pod_phase": "Running",
    "__meta_kubernetes_pod_ready": "true",
    "__meta_kubernetes_pod_uid": "31f6a37c-1e65-457a-a3fb-62d87bd51649",
    "__metrics_path__": "/metrics",
    "__scheme__": "http",
    "__scrape_interval__": "30s",
    "__scrape_timeout__": "10s",
    "job": "pods"
  },
  "labels": {
    "app_kubernetes_io_name": "kubermatic-master-controller-manager",
    "app_kubernetes_io_version": "v2.29.0-alpha.1",
    "instance": "172.27.0.93:8085",
    "job": "pods",
    "namespace": "kubermatic",
    "pod": "kubermatic-master-controller-manager-69f4fd9c5f-4b8cj",
    "pod_template_hash": "69f4fd9c5f"
  },
  "scrapePool": "pods",
  "scrapeUrl": "http://172.27.0.93:8085/metrics",
  "globalUrl": "http://172.27.0.93:8085/metrics",
  "lastError": "server returned HTTP status 500 Internal Server Error",
  "lastScrape": "2025-09-25T13:24:54.066424529Z",
  "lastScrapeDuration": 0.024305882,
  "health": "down",
  "scrapeInterval": "30s",
  "scrapeTimeout": "10s"
}
```

```bash
$ curl -i localhost:8085/metrics
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Thu, 25 Sep 2025 13:20:00 GMT
Transfer-Encoding: chunked

An error has occurred while serving metrics:

29 error(s) occurred:
* collected metric "go_gc_duration_seconds" { summary:{sample_count:215 sample_sum:0.061487726 quantile:{quantile:0 value:9.0731e-05} quantile:{quantile:0.25 value:0.000125801} quantile:{quantile:0.5 value:0.000168281} quantile:{quantile:0.75 value:0.000274052} quantile:{quantile:1 value:0.004674064}}} was collected before with the same name and label values
* collected metric "go_gc_gogc_percent" { gauge:{value:100}} was collected before with the same name and label values
* collected metric "go_gc_gomemlimit_bytes" { gauge:{value:9.223372036854776e+18}} was collected before with the same name and label values
* collected metric "go_goroutines" { gauge:{value:1166}} was collected before with the same name and label values
* collected metric "go_info" { label:{name:"version" value:"go1.25.1"} gauge:{value:1}} was collected before with the same name and label values
* collected metric "go_memstats_alloc_bytes" { gauge:{value:7.0835832e+07}} was collected before with the same name and label values
* collected metric "go_memstats_alloc_bytes_total" { counter:{value:6.628112752e+09}} was collected before with the same name and label values
* collected metric "go_memstats_buck_hash_sys_bytes" { gauge:{value:2.644841e+06}} was collected before with the same name and label values
* collected metric "go_memstats_frees_total" { counter:{value:6.6267209e+07}} was collected before with the same name and label values
* collected metric "go_memstats_gc_sys_bytes" { gauge:{value:5.393184e+06}} was collected before with the same name and label values
* collected metric "go_memstats_heap_alloc_bytes" { gauge:{value:7.0835832e+07}} was collected before with the same name and label values
* collected metric "go_memstats_heap_idle_bytes" { gauge:{value:3.8838272e+07}} was collected before with the same name and label values
* collected metric "go_memstats_heap_inuse_bytes" { gauge:{value:8.1616896e+07}} was collected before with the same name and label values
* collected metric "go_memstats_heap_objects" { gauge:{value:477213}} was collected before with the same name and label values
* collected metric "go_memstats_heap_released_bytes" { gauge:{value:1.5253504e+07}} was collected before with the same name and label values
* collected metric "go_memstats_heap_sys_bytes" { gauge:{value:1.20455168e+08}} was collected before with the same name and label values
* collected metric "go_memstats_last_gc_time_seconds" { gauge:{value:1.758806319195232e+09}} was collected before with the same name and label values
* collected metric "go_memstats_mallocs_total" { counter:{value:6.6744422e+07}} was collected before with the same name and label values
* collected metric "go_memstats_mcache_inuse_bytes" { gauge:{value:4832}} was collected before with the same name and label values
* collected metric "go_memstats_mcache_sys_bytes" { gauge:{value:15704}} was collected before with the same name and label values
* collected metric "go_memstats_mspan_inuse_bytes" { gauge:{value:1.00752e+06}} was collected before with the same name and label values
* collected metric "go_memstats_mspan_sys_bytes" { gauge:{value:1.41984e+06}} was collected before with the same name and label values
* collected metric "go_memstats_next_gc_bytes" { gauge:{value:1.00431026e+08}} was collected before with the same name and label values
* collected metric "go_memstats_other_sys_bytes" { gauge:{value:1.006327e+06}} was collected before with the same name and label values
* collected metric "go_memstats_stack_inuse_bytes" { gauge:{value:5.373952e+06}} was collected before with the same name and label values
* collected metric "go_memstats_stack_sys_bytes" { gauge:{value:5.373952e+06}} was collected before with the same name and label values
* collected metric "go_memstats_sys_bytes" { gauge:{value:1.36309016e+08}} was collected before with the same name and label values
* collected metric "go_sched_gomaxprocs_threads" { gauge:{value:4}} was collected before with the same name and label values
* collected metric "go_threads" { gauge:{value:12}} was collected before with the same name and label values
```
</details>

### Expected behavior

The `/metrics` endpoint should return valid Prometheus metrics without errors, allowing Prometheus to successfully scrape the target.

### How to reproduce the issue?

1. Port-forward kubermatic-master-controller-manager v2.29.0-alpha.1
2. Check Prometheus targets: `curl -s 'http://localhost:9090/api/v1/targets' | jq '.data.activeTargets[] | select(.health == "down")'`
3. Access the metrics endpoint directly: `curl http://localhost:8085/metrics`
4. Observe the HTTP 500 error with duplicate metric collector messages

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by soer3n**
**What this PR does / why we need it**:
Since the update of controller-runtime package to 0.21.0 the metrics endpoint of master controller manager is broken due to duplicate entries for go stats. This is caused because controller-runtime now enables gocollector similar to the default registerer. This pr removes the gocollector from the default registerer to avoid these duplicates.

**Which issue(s) this PR fixes**:

Fixes #15081

**What type of PR is this?**

/bug
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by buraksekili — APPROVED** [review]
/lgtm
/approve

File: cmd/master-controller-manager/main.go [hunk 1]
```diff
@@ -145,6 +146,10 @@ func main() {
 	// register the global error metric. Ensures that runtime.HandleError() increases the error metric
 	metrics.RegisterRuntimErrorMetricCounter("kubermatic_master_controller_manager", prometheus.DefaultRegisterer)
 
+	// The controller-runtime manager already registers a Go collector since https://github.com/kubernetes-sigs/controller-runtime/pull/3070 was merged, so we must
+	// unregister the one from the default registry to avoid duplicate metrics.
+	prometheus.Unregister(promcollectors.NewGoCollector())
+
```
Comment (ahmedwaleedmalik) [inline cmd/master-controller-manager/main.go:152]: Shouldn't this rather be done here? Have you already tried this?

https://github.com/kubermatic/kubermatic/blob/main/pkg/metrics/server/server.go#L40-L44

```
func init() {
	ctrlruntimemetrics.Registry.Unregister(
		collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))
	ctrlruntimemetrics.Registry.Unregister(collectors.NewGoCollector())
        prometheus.Unregister(collectors.NewGoCollector())
}
```

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]
q

File: cmd/master-controller-manager/main.go (hunk 1 above)
Comment (soer3n) [reply cmd/master-controller-manager/main.go:152]: Yes, i checked if the metrics are again fine after unregistering it in main.go. Since the default registerer is passed later in main.go to the collectors i think it is okay to do it there.

Comment (ahmedwaleedmalik) [reply cmd/master-controller-manager/main.go:152]: Didn't really understand your point. Have you tried unregistering it [here](https://github.com/kubermatic/kubermatic/blob/main/pkg/metrics/server/server.go#L40-L44)? If that works then please do that instead of copy pasting this around to multiple places since that is problematic. This PR IMO is also a result of configuring it in the wrong place initially instead of the `init` function since you then have to copy https://github.com/kubermatic/kubermatic/blob/main/cmd/seed-controller-manager/main.go#L175-L177 around to master-controller-manager as well.

Comment (buraksekili) [reply cmd/master-controller-manager/main.go:152]: In the init() function, can we ensure that the Go collector (the one that is duplicated) is registered before we start the controller-runtime Runnable that registers the Go collector? Personally I do not believe so, and if not, unregistering it in the init function will just attempt to remove an unregistered collector, which ultimately results in the same error.
Since this package is being used in different packages, i guess, it's better to unregister in the main flow instead of init function

Comment (ahmedwaleedmalik) [reply cmd/master-controller-manager/main.go:152]: > In the init() function, can we ensure that the Go collector (the one that is duplicated) is registered before we start the controller-runtime Runnable that registers the Go collector? Personally I do not believe so, and if not, unregistering it in the init function will just attempt to remove an unregistered collector, which ultimately results in the sam

My point, i'll reiterate, was to try unregistering it there and see if it works. Have you already tried this @buraksekili before posting this or all of these just some assumptions?

**Review by ahmedwaleedmalik — APPROVED** [review]
I wish the PR actually properly fixed the issue, in a single place instead of duplications that are always problematic. But I also can't spend more time on this. Since the PR was already approved i'm simply going to re-approve it.

/approve
/lgtm
/milestone KKP 2.29
