### PR TITLE
Recover from Grafana data loss

### LINKED ISSUE #12127: MLA controller race condition when re-provisioning Grafana instance from scratch
### What happened?

When the user cluster MLA Grafana instance loses its state (e.g. by persistent volumes being deleted/lost), the user cluster MLA controller can run into a race condition when re-provisioning it:

1. `Project` resources on the seed cluster still have the `mla.k8c.io/organization` annotation that point to a specific Grafana Organization ID.
2. A `Project` gets reconciled (let's call it Project A).
3. When the mla-controller does not find a Organization under the ID stored in Project B (because Grafana was wiped), it re-creates the Project's organisation it is currently reconciling.
4. However, creating Orgs now starts back at `2` as number (`1` is always the default org). Since mla-controller does not process projects in a stable order, there is a good chance another `Project` (let's call it Project B) already has the `mla.k8c.io/organization=2` annotation.
5. When Project B gets reconciled, the mla-controller will find the organisation created for Project A and will accept it as organisation for Project B.

Thus, mla-controller will provision datasources and permissions into the wrong organisation afterwards.

### Expected behavior

mla-controller should be capable of re-provisioning a wiped Grafana instance from scratch and not confuse organisations.

### How to reproduce the issue?

See steps describe above.

### How is your environment configured?

- KKP version: 2.21, but should be present on any version
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

Ideas for the implementation of a fix:

- mla-controller should check if the discovered organisation name contains the project ID of the `Project` it's currently reconciling; if not, it knows it needs to re-create the organisation because of an apparently ID mismatch.

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This PR slightly improves the Grafana org reconciliation loop. It adds another check for the org's name to clumsily detect a drift (most likely caused by a lost storage volume). If the org name does not have the correct suffix, it's assumed that the link between project<->org is invalid and a new org is created instead.

**Which issue(s) this PR fixes**:
Fixes #12127

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
The MLA stack is now able to recover from a lost Grafana volume, properly recreating organizations for KKP projects.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by embik — CHANGES_REQUESTED** [review]
This looks pretty good as it is, but I do believe that we also need to implement the check for the org name somewhere around https://github.com/kubermatic/kubermatic/blob/09c2ef84901b5b2ad7c50db0ed7af8a58723c60a/pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go#L208
and https://github.com/kubermatic/kubermatic/blob/09c2ef84901b5b2ad7c50db0ed7af8a58723c60a/pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go#L211

Otherwise we might end up with datasources and dashboards deployed into the wrong organisation because these controllers were faster than the org-grafana-controller that was fixed here. In my opinion, those controllers should just print a warning and re-queue the reconciling, but refuse to operate on Grafana until the project annotation is fixed.

**Comment by xrstf** [comment]
> In my opinion, those controllers should just print a warning and re-queue the reconciling, but refuse to operate on Grafana until the project annotation is fixed.

agreed

File: pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go [hunk 1]
```diff
@@ -187,17 +186,16 @@ func (r *dashboardGrafanaController) handleDeletion(ctx context.Context, log *za
...
-			id, err := strconv.ParseUint(orgID, 10, 32)
+			org, err := getOrgByProject(ctx, grafanaClient, &project)
 			if err != nil {
-				return fmt.Errorf("unable to parse grafana org annotation %s: %w", orgID, err)
+				// Looks like this project doesn't have corresponding Grafana Organization yet,
+				// or it has an invalid org (after a Grafana data loss, for example); we can skip it
+				// for now and it will be reconciled by org_grafana_controller later.
+				log.Debugw("Project doesn't have a valid grafana org annotation, skipping", "project", project.Name, zap.Error(err))
+				continue
 			}
```
Comment (embik) [inline pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go:196]: also required in `datasource_grafana_controller.go` :-)

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go (hunk 1 above)
Comment (embik) [reply pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go:196]: nvm, my mistake.

**Review by embik — APPROVED** [review]
/approve
