### PR TITLE
gives seed clusters good configuration file

### LINKED ISSUE #3323: a wrong config used to create seed clients
**Description**:

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: before seed clusters were given master config so they couldn't properly locate resources as they were connected to the wrong server

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3323

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: api/cmd/kubermatic-api/main.go [hunk 1]
```diff
@@ -120,7 +115,7 @@ func createInitProviders(options serverRunOptions) (providers, error) {
 			kubermaticSeedClient := kubermaticclientset.NewForConfigOrDie(cfg)
 			kubermaticSeedInformerFactory := kubermaticinformers.NewSharedInformerFactory(kubermaticSeedClient, informer.DefaultInformerResyncPeriod)
 			defaultImpersonationClientForSeed := kubernetesprovider.NewKubermaticImpersonationClient(cfg)
-			seedCtrlruntimeClient, err := ctrlruntimeclient.New(config, ctrlruntimeclient.Options{})
+			seedCtrlruntimeClient, err := ctrlruntimeclient.New(cfg, ctrlruntimeclient.Options{})
```
Comment (p0lyn0mial) [inline api/cmd/kubermatic-api/main.go:118]: that was the issue, as each provider was given a master cfg file, let me check for how long it was with us as we might to backport it to already released versions

Comment (p0lyn0mial) [reply api/cmd/kubermatic-api/main.go:118]: introduced 9 days ago, https://github.com/kubermatic/kubermatic/pull/3205/files#diff-2c79aff0e2588a763c9fd75a55f89fa0R123
