### PR TITLE
(fix): add revision labels to OpenStack CSI addon

### LINKED ISSUE #14216: UC credential rotation on OpenStack is still broken, because openstack-cinder-csi-controllerplugin pod is not restarted
### What happened?

In theory, it's possible to rotate the credentials of a UC by editing the Cluster object and added the new credential pair. In our case, it's specifying `applicationCredentialID` and `applicationCredentialSecret` for OpenStack.

There have been a bunch of fixes to make this work, I think particularly #13703 and #13819 and indeed, many things that didn't work do work now.

However, one thing seems missing. The `openstack-cinder-csi-controllerplugin` pod in the UC is _not_ restarted, thus never learning about the new credentials, despite the latter having been updated. As such, when the old credentials stop working, volumes can't be managed anymore.

### Expected behavior

The `openstack-cinder-csi-controllerplugin` pod in the UC is restarted after the `cloud-config-csi` secret in the UC got updated.

### How to reproduce the issue?

- enable config drive in seed/datacenter
- create UC on OpenStack
- set `applicationCredentialID` and `applicationCredentialSecret` in the Cluster to a new credential pair (would probably also work with username/password instead)
- delete original credentials
- check `openstack-cinder-csi-controllerplugin`
- maybe you need to create a PV, but I think it will list volumes once per minute either way

### How is your environment configured?

- KKP version: 2.27.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 24.04

### Additional information

The pod's logs show the issue clearly:
```
E0307 16:23:46.557868       1 controller.go:146] Failed to reconcile volume attachments: failed to ListVolumes: failed to list volumes: rpc error: code = Internal desc = ListVolumes failed with error Unable to re-authenticate: Expected HTTP response code [200 204 300] when accessing [GET https://volume.api.stage1.cloud.switch.ch/v3/volumes/detail], but got 401 instead: {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}: Expected HTTP response code [201 202] when accessing [POST https://identity.api.stage1.cloud.switch.ch/v3/auth/tokens], but got 404 instead: {"error":{"code":404,"message":"Could not find Application Credential: 
fab5fafb300d4bd68a00ed03c6900e7b.","title":"Not Found"}}
```

### PR DESCRIPTION
**Pull request by buraksekili**
**What this PR does / why we need it**:

Adds revision label support to OpenStack CSI controller deployment to trigger pod restarts when cloud-config-csi secret is updated. This ensures CSI pods are restarted when the cloud-config-csi  secret containing OpenStack Application Credentials is updated.

This PR
- Adds new CSI revision label handling for OpenStack Cinder CSI controller plugin
- Fixes typo in requeue comment

**Which issue(s) this PR fixes**:

Fixes #14216 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Adds revision label support to OpenStack CSI controller deployment to trigger pod restarts when cloud-config-csi secret is updated.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/resources/reconciling/modifier/related_revisions.go [hunk 1]
```diff
@@ -46,6 +46,12 @@ func RelatedRevisionsLabels(ctx context.Context, client ctrlruntimeclient.Client
 	}
 }
 
+// AddRevisionLabelsToObject is a helper function that adds revisions of the resources that the given object depends on, to the given object labels.
+// The revision labels are used to trigger a restart of the object when the dependent resources are updated.
+func AddRevisionLabelsToObject(ctx context.Context, client ctrlruntimeclient.Client, obj ctrlruntimeclient.Object) (ctrlruntimeclient.Object, error) {
+	return addRevisionLabelsToObject(ctx, client, obj)
+}
+
```
Comment (moelsayed) [inline pkg/resources/reconciling/modifier/related_revisions.go:54]: Why not export the internal function directly?

File: pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go [hunk 2]
```diff
@@ -264,7 +264,7 @@ func (r *Reconciler) ensureAddons(ctx context.Context, log *zap.SugaredLogger, c
 	return nil
 }
 
-func (r *Reconciler) addonReconciler(ctx context.Context, cluster *kubermaticv1.Cluster, addon kubermaticv1.Addon) reconciling.NamedAddonReconcilerFactory {
+func (r *Reconciler) addonReconciler(_ context.Context, cluster *kubermaticv1.Cluster, addon kubermaticv1.Addon) reconciling.NamedAddonReconcilerFactory {
```
Comment (moelsayed) [inline pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go]: Is this an interface function? if not, I think we can remove the context altogether..

File: pkg/resources/reconciling/modifier/related_revisions.go (hunk 1 above)
Comment (buraksekili) [reply pkg/resources/reconciling/modifier/related_revisions.go:54]: I just did not want to update callers of the internal method; instead created a public one that calls directly the internal one. But if you think this is redundant, I can update the code accordingly.

File: pkg/controller/seed-controller-manager/addon/addon_controller.go [hunk 3]
```diff
@@ -923,3 +970,51 @@ func (r *Reconciler) cleanupDefaultStorageClassAddon(ctx context.Context, cluste
...
+}
+
+func (r *Reconciler) addCSIRevisionLabels(
+	ctx context.Context,
+	cluster *kubermaticv1.Cluster,
+	parsedUnstructuredObj *metav1unstructured.Unstructured,
+) (*metav1unstructured.Unstructured, error) {
+	if cluster == nil || cluster.Spec.Cloud.Openstack == nil ||
+		parsedUnstructuredObj == nil || parsedUnstructuredObj.GetKind() != "Deployment" ||
+		parsedUnstructuredObj.GetName() != "openstack-cinder-csi-controllerplugin" {
```
Comment (moelsayed) [inline pkg/controller/seed-controller-manager/addon/addon_controller.go]: nit: can we put the strings in conts?

Comment (buraksekili) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go]: Sure! Updated in bc53dec1874ca38518c821bd18486ffb1902b634

File: pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go (hunk 2 above)
Comment (buraksekili) [reply pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go]: Removed in bc53dec1874ca38518c821bd18486ffb1902b634
