### PR TITLE
fix(installer): add validation for ip that's shown in terminal for ingress and dns configuration

### LINKED ISSUE #13864: Issue with kkp-installer, providing private IP as the final output for Ingress and DNS configuration
### What happened?

- When I tried installing kkp using this https://docs.kubermatic.com/kubermatic/v2.26/installation/install-kkp-ce/ for hetzner cluster, everything worked but the final output where we show the ingress IP/IP to be configured for DNS was private due to which kkp was not coming up.

### Expected behavior

- Ingress IP should show correct public i.e external IP and same for DNS configuration.

### How to reproduce the issue?

- Create a hetzner cluster using terraform script present in kubeone
- Create a k8s cluster using kubeone
- Run the steps mentioned in this [doc](https://docs.kubermatic.com/kubermatic/v2.26/installation/install-kkp-ce/) to install kkp-ce.

### How is your environment configured?

- KKP version: 2.26.0
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Hetzner Cloud

### What operating system are you running in your user cluster?

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by rajaSahil**
**What this PR does / why we need it**:

- add validation for ip that's shown in terminal for ingress and dns configuration

**Which issue(s) this PR fixes**:

Fixes #13864 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Add validation for ip that's shown in terminal for ingress and dns configuration. Hostname is preferred, if it's not present then public IP is preferred over private IP.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/install/stack/common/validation.go [hunk 1]
```diff
@@ -140,3 +141,18 @@ func randomString() (string, error) {
 
 	return base64.RawURLEncoding.EncodeToString(b), nil
 }
+
+// ValidatePublicIp validates whether ip provided is public
+func ValidatePublicIp(ipAddress string) bool {
```
Comment (xrstf) [inline pkg/install/stack/common/validation.go]: Boolean functions should just be called "Is...". And this doesn't need to be anexported function.

File: pkg/install/stack/common/validation.go [hunk 2]
```diff
@@ -140,3 +141,18 @@ func randomString() (string, error) {
...
+	ipAddr := net.ParseIP(ipAddress)
+	if ipAddr == nil {
+		return false
+	}
+
+	if ipAddr.IsPrivate() {
+		return false
+	}
+
+	return true
```
Comment (xrstf) [inline pkg/install/stack/common/validation.go]: `return ipAddr != nil && !ipAddr.IsPrivate()`

File: pkg/install/stack/common/validation_test.go [hunk 3]
```diff
@@ -0,0 +1,42 @@
+package common
```
Comment (xrstf) [inline pkg/install/stack/common/validation_test.go]: This file is missing the boilerplate license header.

File: pkg/install/stack/common/validation_test.go [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+import "testing"
+
+func TestValidatePublicIp(t *testing.T) {
+	type args struct {
+		ipAddress string
+	}
```
Comment (xrstf) [inline pkg/install/stack/common/validation_test.go]: This sub structure doesn't really offer much value in this testcase, IMHO. This could be condensed down to

```
testcases := map[string]bool{
   "10.110.197.9": false,
   ...
}
```

as IMHO the subtest names do not offer much extra information in this test.

File: pkg/install/stack/kubermatic-master/stack.go [hunk 5]
```diff
@@ -380,6 +380,12 @@ func showDNSSettings(ctx context.Context, logger *logrus.Entry, kubeClient ctrlr
 		logger.Infof("   %s.    IN  CNAME  %s.", domain, hostname)
 		logger.Infof("   *.%s.  IN  CNAME  %s.", domain, hostname)
 	} else if ip := ingresses[0].IP; ip != "" {
+		for _, ingress := range ingresses {
+			if common.ValidatePublicIp(ingress.IP) {
+				ip = ingress.IP
+				break
+			}
+		}
```
Comment (xrstf) [inline pkg/install/stack/kubermatic-master/stack.go]: Thinking more about this, I think this needs to be rewritten a bit more. If we're now looking through all ingresses for a suitable (or at least better) IP, but further up we also clearly prefer a _hostname_, then why should we not also look through all ingresses for a hostname, instead of just the first one?

This should be rewritten to something similar to

```
var hostname, ip string
for all ingresses {
   if has hostname { hostname = ingress.hostname }
   if has ip {
      // prefer a public IP, but private IPs are also okay depending on the KKP setup
      if ip == "" { ip = ingress.ip }
      else if is public ingress.ip { ip = ingress.ip }
   }
}

if hostname { log log log }
else if ip { log log log }
```

**Comment by xrstf** [comment]
You need to provide a relelase note for this and fill out the documentation block according to the PR template notes. :)

File: pkg/install/stack/common/validation.go (hunk 1 above)
Comment (rajaSahil) [reply pkg/install/stack/common/validation.go]: Addressed

File: pkg/install/stack/common/validation.go (hunk 2 above)
Comment (rajaSahil) [reply pkg/install/stack/common/validation.go]: Addressed

File: pkg/install/stack/common/validation_test.go (hunk 3 above)
Comment (rajaSahil) [reply pkg/install/stack/common/validation_test.go]: Removed the function from `common` package and added it in `kubermaticmaster` package

File: pkg/install/stack/common/validation_test.go (hunk 4 above)
Comment (rajaSahil) [reply pkg/install/stack/common/validation_test.go]: Addressed

File: pkg/install/stack/kubermatic-master/stack.go (hunk 5 above)
Comment (rajaSahil) [reply pkg/install/stack/kubermatic-master/stack.go]: Make sense, thank you!

**Review by xrstf — APPROVED** [review]
/approve
