### PR TITLE
Hotfix: defaulting and validation for tag category

### LINKED ISSUE #11925: vSphere tags are not optional when defaultTagCategoryID is set
When creating a vSphere cluster without tags the dashboard is throwing the following error:

`Cluster.kubermatic.k8c.io "ggd4qbxfsh" is invalid: spec.cloud.vsphere.tags.tags: Invalid value: "null": spec.cloud.vsphere.tags.tags in body must be of type array: "null"`

This seems only happening when defaultTagCategoryID is set on the seed level and the cluster does not have tags set.

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
`CategoryID` should be optional in the cloud spec if `DefaultTagCategoryID` is configured at the seed level.

**Which issue(s) this PR fixes**:

Fixes #11925

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/vsphere/provider.go [hunk 1]
```diff
@@ -119,8 +119,14 @@ func (v *VSphere) DefaultCloudSpec(ctx context.Context, spec *kubermaticv1.Clust
 		if v.dc.DefaultTagCategoryID != "" {
 			spec.Cloud.VSphere.Tags = &kubermaticv1.VSphereTag{
 				CategoryID: v.dc.DefaultTagCategoryID,
+				Tags:       []string{},
 			}
 		}
+	} else {
+		// If tags were specified without a CategoryID then use the default CategoryID, if configured at seed level.
```
Comment (mate4st) [inline pkg/provider/cloud/vsphere/provider.go:126]: What if tags are specified without a CategoryID and no defaultCategoryID is specified/set on seed level?

Comment (ahmedwaleedmalik) [reply pkg/provider/cloud/vsphere/provider.go:126]: The validating webhook will reject such a cluster.

https://github.com/kubermatic/kubermatic/pull/11928/files#diff-4fa162a12c4d00d9041c47cdc45569b25718ef42bd5b748dc8b57838c34da641R151

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers
