### PR TITLE
Addition of missing images to image-loader

### LINKED ISSUE #9166: image-loader does not load images hidden behind conditionals
### What happened?

The `image-loader` utility does not load a couple of images that are hidden behind two kind of conditionals:

1. Conditionals within the addon templates (e.g. `image-loader` only loads calico 3.8.0 images, not other versions like 3.19, 3.20 or 3.21.
2. Conditionals within KKP code, like cloud provider specific Deployments, for example here: https://github.com/kubermatic/kubermatic/blob/89f3303a53edc41e0b0969936a5bae5fb7c2949d/pkg/controller/seed-controller-manager/kubernetes/resources.go#L318-L322

This was reported as customer support request 3644.

### What should happen?

All images required to run KKP should be loaded by `image-loader`.

### How to reproduce?

Run `image-loader`. This for example is the list of image I got from running this from the `release/v2.19` branch:

```sh
_build/image-loader -addons-path ./addons -charts-path ~/Workspace/deployments/kkp-2.19/charts/ -configuration-file ~/Workspace/deployments/kkp-2.19/kubermatic.yaml -helm-values-file ~/Workspace/deployments/kkp-2.19/values.yaml -registry registry.xxx.test -dry-run 2>&1 | grep 'Tagging image' | cut -d '"' -f4
docker.io/calico/cni:v3.8.0
docker.io/calico/node:v3.8.0
docker.io/dexidp/dex:v2.30.0
docker.io/envoyproxy/envoy-alpine:v1.17.1
docker.io/grafana/grafana:8.1.2
docker.io/grafana/loki:2.4.1
docker.io/grafana/promtail:2.3.0
docker.io/jimmidyson/configmap-reload:v0.3.0
docker.io/kubermatic/machine-controller:v1.42.0
docker.io/kubernetesui/dashboard:v2.4.0
docker.io/kumina/openvpn-exporter:v0.2.2
docker.io/library/busybox:1.33
docker.io/lmierzwa/karma:v0.89
docker.io/minio/minio:RELEASE.2021-08-20T18-32-01Z
docker.io/nfvpe/multus:v3.6
docker.io/nginxinc/nginx-unprivileged:1.20.1-alpine
docker.io/prom/blackbox-exporter:v0.18.0
docker.io/sstarcher/helm-exporter:0.4.3
docker.io/velero/velero:v1.6.3
gcr.io/etcd-development/etcd:v3.4.3
gcr.io/etcd-development/etcd:v3.5.1
gcr.io/google_containers/addon-resizer:1.8.4
gcr.io/google_containers/heapster-amd64:v1.5.2
gcr.io/google_containers/vpa-admission-controller:0.5.0
gcr.io/google_containers/vpa-recommender:0.5.0
gcr.io/google_containers/vpa-updater:0.5.0
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.20.0
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.22.0
k8s.gcr.io/coredns/coredns:v1.7.0
k8s.gcr.io/coredns/coredns:v1.8.0
k8s.gcr.io/coredns/coredns:v1.8.4
k8s.gcr.io/ingress-nginx/controller:v1.0.5@sha256:55a1fcda5b7657c372515fe402c3e39ad93aa59f6e4378e82acd99912fe6028d
k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
k8s.gcr.io/kube-apiserver:v1.20.13
k8s.gcr.io/kube-apiserver:v1.20.14
k8s.gcr.io/kube-apiserver:v1.21.8
k8s.gcr.io/kube-apiserver:v1.22.5
k8s.gcr.io/kube-controller-manager:v1.20.13
k8s.gcr.io/kube-controller-manager:v1.20.14
k8s.gcr.io/kube-controller-manager:v1.21.8
k8s.gcr.io/kube-controller-manager:v1.22.5
k8s.gcr.io/kube-proxy:v1.20.13
k8s.gcr.io/kube-proxy:v1.20.14
k8s.gcr.io/kube-proxy:v1.21.8
k8s.gcr.io/kube-proxy:v1.22.5
k8s.gcr.io/kube-scheduler:v1.20.13
k8s.gcr.io/kube-scheduler:v1.20.14
k8s.gcr.io/kube-scheduler:v1.21.8
k8s.gcr.io/kube-scheduler:v1.22.5
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.1
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.3
k8s.gcr.io/metrics-server-amd64:v0.2.1
k8s.gcr.io/metrics-server/metrics-server:v0.5.0
quay.io/brancz/kube-rbac-proxy:v0.11.0
quay.io/coreos/flannel:v0.11.0
quay.io/jetstack/cert-manager-cainjector:v1.5.2
quay.io/jetstack/cert-manager-controller:v1.5.2
quay.io/jetstack/cert-manager-webhook:v1.5.2
quay.io/kubermatic/addons:9e66f7856a56b8f453a3d2a14af834199f66d41f
quay.io/kubermatic/dashboard-ee:NA
quay.io/kubermatic/grafana-plugins:1.3.1
quay.io/kubermatic/http-prober:v0.3.3
quay.io/kubermatic/kubeletdnat-controller:9e66f7856a56b8f453a3d2a14af834199f66d41f
quay.io/kubermatic/kubermatic-ee:9e66f7856a56b8f453a3d2a14af834199f66d41f
quay.io/kubermatic/kubermatic:v2.19.2
quay.io/kubermatic/nodeport-proxy:9e66f7856a56b8f453a3d2a14af834199f66d41f
quay.io/kubermatic/openvpn:v2.5.2-r0
quay.io/kubermatic/s3-exporter:v0.5
quay.io/kubermatic/telemetry-kubermatic-agent:v0.1.0
quay.io/kubermatic/telemetry-kubernetes-agent:v0.1.0
quay.io/kubermatic/telemetry-reporter:v0.1.0
quay.io/kubermatic/util:2.0.0
quay.io/prometheus/alertmanager:v0.22.2
quay.io/prometheus/node-exporter:v1.2.2
quay.io/prometheus/prometheus:v2.29.1
```

Note missing images like Cilium, newer Calico versions, or CSI/CCM images.

### Environment

- KKP Version: 2.19, but present on any
- Shared or separate master/seed clusters?: -
- Master/seed cluster provider: -

### PR DESCRIPTION
**Pull request by mlavacca**
**What does this PR do / Why do we need it**:
This PR improves the image-loader by loading some new images related to:
* CCM/CSI
* Canal
* Cilium

**Does this PR close any issues?**:
Fixes #9166 

**Special notes for your reviewer**:
This is the new output of 
```sh
./_build/image-loader -addons-path ./addons -charts-path ~/Workspace/deployments/kkp-2.19/charts/ -configuration-file ~/Workspace/deployments/kkp-2.19/kubermatic.yaml -helm-values-file ~/Workspace/deployments/kkp-2.19/values.yaml -registry registry.xxx.test -dry-run 2>&1 | grep 'Tagging image' | cut -d '"' -f4
```

```
anx-cr.io/anexia/anx-cloud-controller-manager:0.1.0
docker.io/calico/cni:v3.19.1
docker.io/calico/cni:v3.20.2
docker.io/calico/cni:v3.21.2
docker.io/calico/cni:v3.22.1
docker.io/calico/cni:v3.8.0
docker.io/calico/kube-controllers:v3.19.1
docker.io/calico/kube-controllers:v3.20.2
docker.io/calico/kube-controllers:v3.21.2
docker.io/calico/kube-controllers:v3.22.1
docker.io/calico/node:v3.19.1
docker.io/calico/node:v3.20.2
docker.io/calico/node:v3.21.2
docker.io/calico/node:v3.22.1
docker.io/calico/node:v3.8.0
docker.io/dexidp/dex:v2.30.0
docker.io/envoyproxy/envoy-alpine:v1.17.1
docker.io/envoyproxy/envoy:v1.18.4@sha256:e5c2bb2870d0e59ce917a5100311813b4ede96ce4eb0c6bfa879e3fbe3e83935
docker.io/grafana/grafana:8.1.2
docker.io/grafana/loki:2.4.2
docker.io/grafana/promtail:2.4.2
docker.io/hetznercloud/hcloud-cloud-controller-manager:v1.12.1
docker.io/jimmidyson/configmap-reload:v0.3.0
docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.21.0
docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.22.0
docker.io/k8scloudprovider/openstack-cloud-controller-manager:v1.23.1
docker.io/kubermatic/machine-controller:v1.42.0
docker.io/kubernetesui/dashboard:v2.4.0
docker.io/kubernetesui/dashboard:v2.5.0
docker.io/kumina/openvpn-exporter:v0.2.2
docker.io/library/busybox:1.33
docker.io/lmierzwa/karma:v0.89
docker.io/minio/minio:RELEASE.2022-02-16T00-35-27Z
docker.io/nginxinc/nginx-unprivileged:1.20.1-alpine
docker.io/prom/blackbox-exporter:v0.18.0
docker.io/sstarcher/helm-exporter:0.4.3
docker.io/velero/velero:v1.6.3
gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.21.1
gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.22.4
gcr.io/etcd-development/etcd:v3.4.3
gcr.io/etcd-development/etcd:v3.5.1
gcr.io/google_containers/heapster-amd64:v1.5.2
ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8.1
k8s.gcr.io/autoscaling/addon-resizer:1.8.14
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.2
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.22.2
k8s.gcr.io/autoscaling/cluster-autoscaler:v1.23.0
k8s.gcr.io/autoscaling/vpa-admission-controller:0.9.2
k8s.gcr.io/autoscaling/vpa-recommender:0.9.2
k8s.gcr.io/autoscaling/vpa-updater:0.9.2
k8s.gcr.io/coredns/coredns:v1.8.0
k8s.gcr.io/coredns/coredns:v1.8.4
k8s.gcr.io/ingress-nginx/controller:v1.0.5@sha256:55a1fcda5b7657c372515fe402c3e39ad93aa59f6e4378e82acd99912fe6028d
k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1@sha256:64d8c73dca984af206adf9d6d7e46aa550362b1d7a01f3a0a91b20cc67868660
k8s.gcr.io/kube-apiserver:v1.21.10
k8s.gcr.io/kube-apiserver:v1.21.8
k8s.gcr.io/kube-apiserver:v1.22.5
k8s.gcr.io/kube-apiserver:v1.22.7
k8s.gcr.io/kube-apiserver:v1.23.5
k8s.gcr.io/kube-controller-manager:v1.21.10
k8s.gcr.io/kube-controller-manager:v1.21.8
k8s.gcr.io/kube-controller-manager:v1.22.5
k8s.gcr.io/kube-controller-manager:v1.22.7
k8s.gcr.io/kube-controller-manager:v1.23.5
k8s.gcr.io/kube-proxy:v1.21.10
k8s.gcr.io/kube-proxy:v1.21.8
k8s.gcr.io/kube-proxy:v1.22.5
k8s.gcr.io/kube-proxy:v1.22.7
k8s.gcr.io/kube-proxy:v1.23.5
k8s.gcr.io/kube-scheduler:v1.21.10
k8s.gcr.io/kube-scheduler:v1.21.8
k8s.gcr.io/kube-scheduler:v1.22.5
k8s.gcr.io/kube-scheduler:v1.22.7
k8s.gcr.io/kube-scheduler:v1.23.5
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.1
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.3
k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.3.0
k8s.gcr.io/metrics-server-amd64:v0.2.1
k8s.gcr.io/metrics-server/metrics-server:v0.5.0
quay.io/brancz/kube-rbac-proxy:v0.11.0
quay.io/cilium/certgen:v0.1.5
quay.io/cilium/cilium:v1.11.0@sha256:ea677508010800214b0b5497055f38ed3bff57963fa2399bcb1c69cf9476453a
quay.io/cilium/hubble-relay:v1.11.0@sha256:306ce38354a0a892b0c175ae7013cf178a46b79f51c52adb5465d87f14df0838
quay.io/cilium/hubble-ui-backend:v0.8.3@sha256:13a16ed3ae9749682c817d3b834b2f2de901da6fb41de7753d7dce16650982b3
quay.io/cilium/hubble-ui:v0.8.3@sha256:018ed122968de658d8874e2982fa6b3a8ae64b43d2356c05f977004176a89310
quay.io/cilium/operator-generic:v1.11.0@sha256:b522279577d0d5f1ad7cadaacb7321d1b172d8ae8c8bc816e503c897b420cfe3
quay.io/coreos/flannel:v0.11.0
quay.io/coreos/flannel:v0.15.1
quay.io/jetstack/cert-manager-cainjector:v1.5.2
quay.io/jetstack/cert-manager-controller:v1.5.2
quay.io/jetstack/cert-manager-webhook:v1.5.2
quay.io/kubermatic/addons:9f655f5b761c2420457aee29d4091dc67591a603
quay.io/kubermatic/dashboard:NA
quay.io/kubermatic/grafana-plugins:1.3.1
quay.io/kubermatic/http-prober:v0.3.3
quay.io/kubermatic/kubeletdnat-controller:9f655f5b761c2420457aee29d4091dc67591a603
quay.io/kubermatic/kubermatic:9f655f5b761c2420457aee29d4091dc67591a603
quay.io/kubermatic/kubermatic:v9.9.9-dev
quay.io/kubermatic/kubevirt-cloud-controller-manager:v0.1.0
quay.io/kubermatic/kubevirt-csi-driver-operator:v0.1.0
quay.io/kubermatic/nodeport-proxy:9f655f5b761c2420457aee29d4091dc67591a603
quay.io/kubermatic/openvpn:v2.5.2-r0
quay.io/kubermatic/s3-exporter:v0.5
quay.io/kubermatic/telemetry-kubermatic-agent:v0.1.0
quay.io/kubermatic/telemetry-kubernetes-agent:v0.1.0
quay.io/kubermatic/telemetry-reporter:v0.1.0
quay.io/kubermatic/util:2.0.0
quay.io/prometheus/alertmanager:v0.22.2
quay.io/prometheus/node-exporter:v1.2.2
quay.io/prometheus/prometheus:v2.29.1
quay.io/prometheus/prometheus:v2.33.3
```

**Documentation**:

**Does this PR introduce a user-facing change?**:

```release-note
The Image-loader utility now includes all the images used by KKP, considering also the provider-specific ones (e.g., CCM, CSI).
```

### CODE REVIEW

File: pkg/apis/kubermatic/v1/cluster.go [hunk 1]
```diff
@@ -893,7 +893,8 @@ type GCPCloudSpec struct {
 type KubevirtCloudSpec struct {
 	CredentialsReference *providerconfig.GlobalSecretKeySelector `json:"credentialsReference,omitempty"`
 
-	Kubeconfig string `json:"kubeconfig,omitempty"`
+	Kubeconfig    string `json:"kubeconfig,omitempty"`
+	CSIKubeConfig string `json:"csiKubeconfig,omitempty"`
```
Comment (embik) [inline pkg/apis/kubermatic/v1/cluster.go]: Why is this added here? I don't think I understand the kubevirt related changes in this PR. Are they intentional?

**Review by embik — CHANGES_REQUESTED** [review]

**Comment by embik** [comment]
This is likely not directly related to your PR, but I noticed the following two images in your command output:

- `quay.io/kubermatic/dashboard:NA`
- `quay.io/kubermatic/kubermatic:v9.9.9-dev`

I don't think these should be in there. Is this something with your charts directory? `v9.9.9-dev` shouldn't show up if the charts are extracted from a release.

File: pkg/apis/kubermatic/v1/cluster.go (hunk 1 above)
Comment (mlavacca) [reply pkg/apis/kubermatic/v1/cluster.go]: This is the only field (at least, the only one I found) that retrieve is enforced through a secret; this means that to make the whole thing work, we'd need to have a cluster from which to get a secret with that value stored. For all the other fields cloud-related, we first try to get the value from the cloudSpec, then if it doesn't exist we try to fetch a secret containing the data. In the image-loader scenario, we must have a field to set because there is no cluster in place to get the secret from (we could use a fake client, but it looks sooo hacky to me). You can see all the credential fetching methods here: https://github.com/kubermatic/kubermatic/blob/8552b8ed98ed2cfb8011b215c2b9d13c00649d28/pkg/resources/credentials.go#L316-L629

Comment (embik) [reply pkg/apis/kubermatic/v1/cluster.go]: Okay that actually makes a lot of sense, thank you. @hdurand0710 could you please take a quick look at this PR from a kubevirt perspective? Are there any objections to this (being able to pass the CSI kubeconfig directly instead of relying on a secret)?

Comment (hdurand0710) [reply pkg/apis/kubermatic/v1/cluster.go]: It makes sense and look good me on a KubeVirt perspective. I've launched the Kubevirt e2e test to be on the safe side.

**Comment by mlavacca** [comment]
> @mlavacca: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pre-kubermatic-e2e-kubevirt-ubuntu-1.23	[8552b8e](https://github.com/kubermatic/kubermatic/commit/8552b8ed98ed2cfb8011b215c2b9d13c00649d28)	[link](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/9518/pre-kubermatic-e2e-kubevirt-ubuntu-1.23/1511605070460882944)	true	`/test pre-kubermatic-e2e-kubevirt-ubuntu-1.23`
> [Full PR test history](https://public-prow.loodse.com/pr-history?org=kubermatic&repo=kubermatic&pr=9518)

This is failing due to the validation that I added. Is CSIKubeconfig supposed to always exist or do we admit scenarios in which it doesn't @hdurand0710 ?

**Comment by hdurand0710** [comment]
> > @mlavacca: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name	Commit	Details	Required	Rerun command
> > pre-kubermatic-e2e-kubevirt-ubuntu-1.23	[8552b8e](https://github.com/kubermatic/kubermatic/commit/8552b8ed98ed2cfb8011b215c2b9d13c00649d28)	[link](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/9518/pre-kubermatic-e2e-kubevirt-ubuntu-1.23/1511605070460882944)	true	`/test pre-kubermatic-e2e-kubevirt-ubuntu-1.23`
> > [Full PR test history](https://public-prow.loodse.com/pr-history?org=kubermatic&repo=kubermatic&pr=9518)
> 
> This is failing due to the validation that I added. Is CSIKubeconfig supposed to always exist or do we admit scenarios in which it doesn't @hdurand0710 ?

It's supposed to always exist.

**Review by embik — APPROVED** [review]
looks good to me, but will need approval from sig-api.

**Comment by embik** [comment]
@mlavacca how difficult would it be to cherry-pick this into at least `release/v2.20`? Since this is a customer request, I'd like to get this into something that is accessible for end users before the next minor release.

**Comment by mlavacca** [comment]
I guess it is as difficult as do
/cherry-pick release/v2.20
