### PR TITLE
AWS: improved validation during cluster creation

### LINKED ISSUE #848: Don't fail if default VPC isn't available
@mrIncompetent said that we can handle not having a default VPC in another more graceful way, so we don't increase our `kubermatic_cluster_controller_unhandled_errors_total` counter.

```
I0322 09:22:43.912329       1 controller.go:364] syncing cluster bsbf2hfp72
I0322 09:22:43.947780       1 controller.go:442] Error syncing cluster bsbf2hfp72: failed to get default vpc: unable not find default vpc
```

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: when a user did't specify vpc && subnet make sure we can
get default vpc && subnet if not don't allow to create a cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #848

**Special notes for your reviewer**:

### CODE REVIEW

**Review by mrIncompetent — APPROVED** [review]

File: api/pkg/provider/cloud/aws/provider.go [hunk 1]
```diff
@@ -53,6 +53,23 @@ func (a *amazonEc2) ValidateCloudSpec(cloud *kubermaticv1.CloudSpec) error {
 		}
 	}
 
+	if cloud.AWS.VPCID == "" && cloud.AWS.SubnetID == "" {
```
Comment (p0lyn0mial) [inline api/pkg/provider/cloud/aws/provider.go:56]: Haven't tested it but I think this is what we want. `ValidateCloudSpec` is called  during cluster creation https://github.com/kubermatic/kubermatic/blob/master/api/pkg/handler/cluster.go#L24
