### PR TITLE
cinder csi: allow topology support customization

### LINKED ISSUE #12877: Openstack: cinder CSI: can't disable topology support
Recent upgrade of the cinder CSI driver in https://github.com/kubermatic/kubermatic/pull/12593#discussion_r1414142649 seems to cause a regression.

Upstream has set a topology support as default - https://github.com/kubernetes/cloud-provider-openstack/pull/1430, which breaks environments where the AZs between nova and cinder are mismatched.

Since KKP currently doesn't allow any customization of the cinder CSI driver, the only way forward is to build custom addons image and hardcode this flag on the controller plugin
```
--feature-gates=Topology=false
``` 

more in: https://github.com/kubernetes/cloud-provider-openstack/issues/2185

### PR DESCRIPTION
**Pull request by wozniakjan**
**What this PR does / why we need it**:
This PR introduces configurability over Cinder CSI plugin topology support. Openstack allows Nova and Cinder AZs to be named differently which breaks with the topology support enabled on the CSI driver making it impossible for volumes to get provisioned.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12877

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Openstack: allow configuring Cinder CSI topology support either on `Cluster` or `Seed` resource field `cinderTopologyEnabled`.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: cmd/conformance-tester/pkg/clients/client_kube.go [hunk 1]
```diff
@@ -193,6 +194,12 @@ func (c *kubeClient) CreateCluster(ctx context.Context, log *zap.SugaredLogger,
 		cluster.Spec.ClusterNetwork.IPFamily = kubermaticv1.IPFamilyDualStack
 	}
 
+	// Cilium became KKP's default CNI plugin but our CentOS images do not support it yet
+	// https://github.com/kubermatic/kubermatic/pull/12752
+	// https://github.com/kubermatic/kubermatic/pull/12878#issuecomment-1842451739
+	if scenario.OperatingSystem() == providerconfig.OperatingSystemCentOS {
+		cluster.Spec.CNIPlugin = &kubermaticv1.CNIPluginSettings{Type: kubermaticv1.CNIPluginTypeCanal}
```
Comment (wozniakjan) [inline cmd/conformance-tester/pkg/clients/client_kube.go:201]: maybe we should not allow cilium with centos at the moment?

**Comment by wozniakjan** [comment]
ptal
/cc: @embik @xmudrii

**Review by embik — CHANGES_REQUESTED** [review]
Please make the release note more specific (which field to set on clusters or datacenters to enable/disable this).

File: pkg/apis/kubermatic/v1/cluster.go [hunk 2]
```diff
@@ -1310,6 +1310,11 @@ type OpenstackCloudSpec struct {
 	// The suffix is set to `nip.io` by default. Can only be used with the external CCM and might be deprecated and removed in
 	// future versions as it is considered a workaround only.
 	IngressHostnameSuffix *string `json:"ingressHostnameSuffix,omitempty"`
+
+	// Flag to configure enablement of CSI Cinder plugin for topology support.
```
Comment (xmudrii) [inline pkg/apis/kubermatic/v1/cluster.go]: Nit: I think the comment might make more sense the other way
```suggestion
	// Flag to configure enablement of topology support for the Cinder CSI plugin.
```

File: pkg/apis/kubermatic/v1/datacenter.go [hunk 3]
```diff
@@ -604,6 +604,9 @@ type DatacenterSpecOpenstack struct {
 	EnabledFlavors []string `json:"enabledFlavors,omitempty"`
 	// Optional: defines if the IPv6 is enabled for the datacenter
 	IPv6Enabled *bool `json:"ipv6Enabled,omitempty"`
+	// Optional: configures enablement of CSI Cinder plugin for topology support.
```
Comment (xmudrii) [inline pkg/apis/kubermatic/v1/datacenter.go]:
```suggestion
	// Optional: configures enablement of topology support for the Cinder CSI Plugin.
```

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
