### PR TITLE
Fix selector modification

### LINKED ISSUE #1053: Fix update issues

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
- Streamlines all labels & selectors
- Adds delete & create logic to deployments and statefulsets for selector changes

Fixes #1053

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: api/pkg/controller/cluster/pending.go [hunk 1]
```diff
@@ -640,6 +641,12 @@ func (cc *Controller) ensureDeployments(c *kubermaticv1.Cluster) error {
 			continue
 		}
 
+		// In case we update something immutable we need to delete&recreate. Creation happens on next sync
```
Comment (p0lyn0mial) [inline api/pkg/controller/cluster/pending.go:644]: is this necessary ? Or maybe is this a one-off operation ?

I think this can cause downtime. I am just worried that in the future no one will remember about that. I am just thinking out loud, maybe a force flag would be better ?

File: api/pkg/resources/apiserver/deployment.go [hunk 2]
```diff
@@ -34,11 +38,12 @@ func Deployment(data *resources.TemplateData, existing *appsv1.Deployment) (*app
 
 	dep.Name = resources.ApiserverDeploymenName
 	dep.OwnerReferences = []metav1.OwnerReference{data.GetClusterRef()}
+	dep.Labels = resources.GetLabels(name)
```
Comment (p0lyn0mial) [inline api/pkg/resources/apiserver/deployment.go:41]: handy method :)

**Comment by mrIncompetent** [comment]
Requesting review from you both as it's a fairly big change

File: api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml [hunk 3]
```diff
@@ -11,6 +11,8 @@ data:
     disablestrictzonecheck=true
 metadata:
   creationTimestamp: null
+  labels:
+    app: cloud-config
```
Comment (p0lyn0mial) [inline api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml:15]: why we decided to add labels to ConfigMaps

Comment (mrIncompetent) [reply api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml:15]: I just added them to everything in `pkg/resources`
But they do not make much sense there. I'll remove them from ConfigMaps

File: api/pkg/controller/cluster/pending.go (hunk 1 above)
Comment (mrIncompetent) [reply api/pkg/controller/cluster/pending.go:644]: It will definitely create a downtime. But that's OK IMO.

File: api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml (hunk 3 above)
Comment (p0lyn0mial) [reply api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml:15]: okay, I'd add labels to object only if they are required.

File: api/pkg/controller/cluster/pending.go (hunk 1 above)
Comment (p0lyn0mial) [reply api/pkg/controller/cluster/pending.go:644]: do we usually inform customers on planned downtime :)?

File: api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml (hunk 3 above)
Comment (mrIncompetent) [reply api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml:15]: Ah it actually makes sense for the prometheus configmap. 
It lets you very simply fetch every related resource for an app.

But as the CloudConfig does get used by the apiserver & controller-manager `app` seems hard to define.
WDYT @p0lyn0mial

File: api/pkg/controller/cluster/pending.go (hunk 1 above)
Comment (mrIncompetent) [reply api/pkg/controller/cluster/pending.go:644]: No. Until recently every update involved a downtime.
As the downtime is not more than 1 min no one actually notices

**Review by metalmatze — APPROVED** [review]

File: api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml (hunk 3 above)
Comment (p0lyn0mial) [reply api/pkg/resources/test/fixtures/configmap-aws-1.8.0-cloud-config.yaml:15]: this is something I suspected. The Labels make querying the system easier. SGTM

File: api/pkg/controller/cluster/pending.go (hunk 1 above)
Comment (p0lyn0mial) [reply api/pkg/controller/cluster/pending.go:644]: SGTM

**Comment by p0lyn0mial** [comment]
lgtm
