### PR TITLE
fix kubevirt tenant rbac

### LINKED ISSUE #13966: RBAC issue with csi-driver for kubevirt tenant cluster
csi-driver for kubevirt provider clusters is complaining about non-existing clusterRole `csi-controller`. There is none, but there is kubevirt-csi-controller.

```
csi-driver I0106 10:58:56.571789       1 controller.go:464] failed removing volume pvc-2a552866-acf8-4459-b8a6-3bd18c17f4ff from VM loving-poitras-65679c7b5d-qbz5g, err: virtualmachin
einstances.kubevirt.io "loving-poitras-65679c7b5d-qbz5g" is forbidden: User "system:serviceaccount:cluster-rl877lc7c6:kubevirt-csi" cannot get resource "virtualmachineinstances" in AP
I group "kubevirt.io" in the namespace "cluster-rl877lc7c6": RBAC: clusterrole.rbac.authorization.k8s.io "csi-controller" not found
```

1. Issue

The roleRef here should specify `resources.KubeVirtCSIClusterRoleName` instead of`resources.KubeVirtCSIControllerName`?

https://github.com/kubermatic/kubermatic/blob/25ed4f7ccd44d2be69c34e745c9bcb59ae1927fd/pkg/resources/csi/kubevirt/rbac.go#L170-L174

2. Issue

Additionally, the Role created for the cluster (`kubevirt-csi`), is lacking the `get` verb for `vmis`.

### PR DESCRIPTION
**Pull request by redradrat**
**What this PR does / why we need it**:
Fixes rbac issues for kubevirt provider.

* add "get" for vmis for kubevirt-csi role
* ~~fix roleRef for csi-controller binding~~

**Which issue(s) this PR fixes**:

Fixes #13966

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
The created RBAC Role for the csi-driver now grants get for VirtualMachineInstances.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
@redradrat Could you please provide a release-note for this change? It seems like something worth mentioning.

File: pkg/resources/csi/kubevirt/rbac.go [hunk 1]
```diff
@@ -170,7 +170,7 @@ func ControllerRoleBindingReconciler(c *kubermaticv1.Cluster) reconciling.NamedR
 			r.RoleRef = rbacv1.RoleRef{
 				APIGroup: "rbac.authorization.k8s.io",
 				Kind:     "ClusterRole",
-				Name:     resources.KubeVirtCSIControllerName,
+				Name:     resources.KubeVirtCSIClusterRoleName,
```
Comment (ahmedwaleedmalik) [inline pkg/resources/csi/kubevirt/rbac.go]: The other change(adding `get` verb) makes sense. However, this change, at least to me, seems like we have a bigger issue with the RBAC since this role/rolebinding is being created in the seed cluster which is not required IMO. But for now it's good to go from my side.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/hold for Moath

File: pkg/resources/csi/kubevirt/rbac.go (hunk 1 above)
Comment (moadqassem) [reply pkg/resources/csi/kubevirt/rbac.go]: I agree with @ahmedwaleedmalik here. This change doesn't make quite sense to me and the whole RBAC model must be completely re-worked, by the end of the day the CSI controller is working on . However this should be in another PR.as the KubeVirt CSi Driver is only looking at Tenant cluster and Infra cluster not the seed. And this PR applies things on seed.

Comment (akash-gautam) [reply pkg/resources/csi/kubevirt/rbac.go]: Till we get the RBAC model reworked, doesn't it make sense to have these changes in? Currently the `csi-controller` is configured to use a cluster role already just that the binding is referring to a non-existing cluster role this PR is just changing it to refer to the correct cluster role. Without the binding update it just keeps complaining that the cluster role doesn't exist `group "kubevirt.io" in the namespace "cluster-rl877lc7c6": RBAC: clusterrole.rbac.authorization.k8s.io "csi-controller" not found`.

Comment (moadqassem) [reply pkg/resources/csi/kubevirt/rbac.go]: > Till we get the RBAC model reworked, doesn't it make sense to have these changes in?

Not really as this might even complicate things more when this will be refactored because this change will then point to a real cluster role that will introduce confusion to whom is gonna work on it. 

> Without the binding update it just keeps complaining that the cluster role doesn't exist group "kubevirt.io" in the namespace "cluster-rl877lc7c6": RBAC: clusterrole.rbac.authorization.k8s.io "csi-controller" not found.

That means you would like to get rid of a log message message and exchange it with a logical error that will go silent for god knows when. IMHO, I would prefer to leave this error message to mark down this issue for the future instead of hiding somewhere in the code.

Comment (redradrat) [reply pkg/resources/csi/kubevirt/rbac.go]: @moadqassem  I have reverted the change in question.

**Comment by redradrat** [comment]
@moadqassem @akash-gautam @toschneck I have reverted the ClusterRole relevant change. So this is now just the missing get verb for the vmis.
@xrstf I adjusted the Release Notes accordingly, as I assume they'll be taken automatically?

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
