### PR TITLE
Use etcd client cert auth

### LINKED ISSUE #1436: Enable TLS for apiserver <-> etcd communication
Currently the communication between the kubernetes apiserver and its backing etcd happens unencrypted. This should be changed because:

* It is insecure
* If an APIServer happens to talk to the wrong etcd, this will succeed and emit itself in a wide range of weird behvaiours

If possible, this should be implemented in a way that rolling upgrades of existing clusters work and no migration logic gets added.

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Enables client cert authentication on etcd.

Whats missing:
- [x] Client cert for backup handling

Fixes #1436

**Release note**:
```release-note
Communication between apiserver and etcd is now encrypted
```

### CODE REVIEW

File: api/pkg/resources/apiserver/etcd-client-certificate.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	"github.com/kubermatic/kubermatic/api/pkg/resources"
+
+	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	certutil "k8s.io/client-go/util/cert"
+	"k8s.io/client-go/util/cert/triple"
+)
+
+// EtcdClientCertificate returns a secret with the etcd client certificate
+func EtcdClientCertificate(data *resources.TemplateData, existing *corev1.Secret) (*corev1.Secret, error) {
```
Comment (alvaroaleman) [inline api/pkg/resources/apiserver/etcd-client-certificate.go]: I think this rather belongs into the `pkg/ressources/etcd` package, especially since the backup job needs it as well

Comment (alvaroaleman) [reply api/pkg/resources/apiserver/etcd-client-certificate.go]: Or maybe: Have a func for this in `pkg/ressources/etcd` that takes the desired names/OUs as argument

File: api/pkg/resources/apiserver/etcd-client-certificate.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+	ca, err := data.GetClusterCA()
+	if err != nil {
+		return nil, fmt.Errorf("failed to get cluster ca: %v", err)
+	}
+
+	if b, exists := se.Data[resources.ApiserverEtcdClientCertificateCertSecretKey]; exists {
+		certs, err := certutil.ParseCertsPEM(b)
+		if err != nil {
+			return nil, fmt.Errorf("faield to certificate (key=%s) from existing secret %s: %v", resources.ApiserverEtcdClientCertificateCertSecretKey, resources.ApiserverEtcdClientCertificateSecretName, err)
```
Comment (alvaroaleman) [inline api/pkg/resources/apiserver/etcd-client-certificate.go]: typo

File: api/pkg/resources/apiserver/etcd-client-certificate.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+		}
+
```
Comment (alvaroaleman) [inline api/pkg/resources/apiserver/etcd-client-certificate.go]: Expiration check is missing

**Review by alvaroaleman — CHANGES_REQUESTED** [review]

**Comment by alvaroaleman** [comment]
This is also still missing a migration

**Comment by mrIncompetent** [comment]
Just added the secret revisions to the pod labels.
No migration needed. We might see a downtime of the Apiserver's for the time the etcd gets updated.

**Review by alvaroaleman — APPROVED** [review]
