### PR TITLE
set rollback revision explicit to last deployed for helm releases managed by applicationinstallations

### LINKED ISSUE #13915: [KKP 2.26+] ApplicationInstallations getting stuck on missing revision
### What happened?

Original issue #12846 which was fixed and backported to 2.25 (#13332) is still not working fully well.

We still get occasionally Application stuck issue. I have confirmed at it happens occasionally, at least at two customer locations.

### Expected behavior

Applications should not get stuck into pending status without any user intervention.

### How to reproduce the issue?

Not sure how to get the issue reproduced as it is very random. But the analysis below can provide some clues to see the logic written in the code and fix it.

In below logs (a real world cluster), both apps are stuck. See the helm releases available in the output below..
```shell
# kubeconfig for the user-cluster is exported
❯ helm ls -Aa
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kube-system-cilium              kube-system     9792            2024-10-12 22:34:13.224973335 +0000 UTC pending-upgrade cilium-1.14.9           1.14.9
kube-system-ingress-nginx       ingress-nginx   511             2024-10-12 22:18:58.530734113 +0000 UTC pending-upgrade ingress-nginx-4.9.1     1.9.6
❯ helm history -n ingress-nginx kube-system-ingress-nginx
REVISION        UPDATED                         STATUS          CHART                   APP VERSION     DESCRIPTION
509             Sat Oct 12 22:08:57 2024        deployed        ingress-nginx-4.9.1     1.9.6           Upgrade complete
511             Sat Oct 12 22:18:58 2024        pending-upgrade ingress-nginx-4.9.1     1.9.6           Preparing upgrade
❯ helm history -n kube-system kube-system-cilium
REVISION        UPDATED                         STATUS          CHART           APP VERSION     DESCRIPTION
9790            Sat Oct 12 22:25:58 2024        deployed        cilium-1.14.9   1.14.9          Upgrade complete
9792            Sat Oct 12 22:34:13 2024        pending-upgrade cilium-1.14.9   1.14.9          Preparing upgrade
```

See the details in usercluster-controller pods of that user-cluster. Note the target release no in 3rd log line..
```log
{"level":"info","time":"2024-12-04T06:32:38.048Z","logger":"kkp-app-installation-controller","caller":"application-installation-controller/controller.go:252","msg":"Release for ApplicationInstallation seems to be stuck, attempting rollback now","applicationinstallation":"kube-system/ingress-nginx"}
{"level":"info","time":"2024-12-04T06:32:38.096Z","logger":"kkp-app-installation-controller","caller":"action/rollback.go:65","msg":"preparing rollback of kube-system-ingress-nginx","applicationinstallation":"kube-system/ingress-nginx"}
{"level":"info","time":"2024-12-04T06:32:38.125Z","logger":"kkp-app-installation-controller","caller":"action/rollback.go:113","msg":"rolling back kube-system-ingress-nginx (current: v511, target: v510)","applicationinstallation":"kube-system/ingress-nginx"}{"level":"error","time":"2024-12-04T06:32:38.128Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-app-installation-controller","object":{"name":"ingress-nginx","namespace":"kube-system"},"namespace":"kube-system","name":"ingress-nginx","reconcileID":"a019802a-bf24-4b8f-bf3b-686538349b9f","error":"handling installation of application installation: failed to rollback release: Could not rollback release \"kube-system-ingress-nginx\": release: not found"}
```

As you can see in line 3 - the usercluster-controller is trying to rollback to a version that does not exist! I do not know why that version is not present in the cluster. In general I think the logic should be that we should look at latest `deployed` release and we should rollback to that release.

### How is your environment configured?

- KKP version: 2.25.11
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)
NA

</details>

### What cloud provider are you running on?
vsphere

### What operating system are you running in your user cluster?
Ubuntu 22.04

### PR DESCRIPTION
**Pull request by soer3n**
**What this PR does / why we need it**:

This PR adds logic for using the last successful deployed revision for a rollback of a helm release managed by application installation controller if needed. The default revision for a rollback if not set is the current minus one which could lead to issues as described in #13915.

**Which issue(s) this PR fixes**:

Fixes #13915

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
The rollback revision is now set explicit to the last deployed revision when a helm release managed by an application installation fails and a rollback is executed to avoid errors when the last deployed revision is not the current minus 1 and history limit is set to 1.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/applications/helmclient/client.go [hunk 1]
```diff
@@ -473,7 +473,15 @@ func (h HelmClient) GetMetadata(releaseName string) (*action.Metadata, error) {
...
+	// which could lead to errors due to missing revisions when the latest ones failed because we configure history limits
+	// on upgrade actions
+	latestDeployedRelease, err := h.actionConfig.Releases.Deployed(releaseName)
+	if err != nil {
+		return fmt.Errorf("Could not fetch last successful release %q: %w", releaseName, err)
+	}
+	client.Version = latestDeployedRelease.Version
+	err = client.Run(releaseName)
 	if err != nil {
 		return fmt.Errorf("Could not rollback release %q: %w", releaseName, err)
```
Comment (xrstf) [inline pkg/applications/helmclient/client.go]: error strings should ideally not begin with capital letters

Comment (soer3n) [reply pkg/applications/helmclient/client.go]: thanks for the hint. I changed it also for other error strings which began with a capital letter in this file.

**Review by xrstf — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
@soer3n Can you please edit the PR description and provide a release-note for our users?
