### PR TITLE
fix: CBSL credentials and status sync to seed for seperate master and seed cluster setup

### LINKED ISSUE #14691: CBSL credential secret not synced to seed clusters
### What happened?

When creating a ClusterBackupStorageLocation (CBSL) in the master cluster, the associated credential secret is not automatically synced to seed clusters. This requires manual intervention to copy the secret, which is not ideal for a fully automated backup solution

### Expected behavior

1. CBSL is created in the master cluster
2. Credential secret is created in the master cluster
3. Both CBSL and its credential secret are automatically synced to seed clusters
4. Backup operations work without manual intervention

### How to reproduce the issue?

1. Create a CBSL in the master cluster:
2. Observe that:
   - CBSL is synced to seed clusters
   - Credential secret is created in master cluster
   - Credential secret is NOT synced to seed clusters

### How is your environment configured?

- KKP version: 2.27
- Shared or separate master/seed clusters?: Shared

### What cloud provider are you running on?

AWS

### Additional information

- This issue was discovered after the fix in PR #13955
- The fix in PR #13955 correctly handles CBSL sync but missed the credential secret sync
- This is a regression in the backup functionality for multi-cluster setups

### PR DESCRIPTION
**Pull request by rajaSahil**
**What this PR does / why we need it**:
This PR fixes an issue where the ClusterBackupStorageLocation (CBSL) was reconciled to seed clusters without syncing the referenced credential Secret, causing backup operations to fail.
This PR ensures that the credential Secret is created or updated in each seed cluster during CBSL reconciliation. 

**Which issue(s) this PR fixes**:

Fixes #14691 and #14645 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix issue with CBSL credentials and status not syncing to seed clusters.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/ee/cluster-backup/master/sync-controller/controller.go [hunk 1]
```diff
@@ -167,3 +176,57 @@ func (r *reconciler) handleDeletion(ctx context.Context, log *zap.SugaredLogger,
 
 	return kuberneteshelper.TryRemoveFinalizer(ctx, r.masterClient, cbsl, cleanupFinalizer)
 }
+
+func syncCBSLCredentialSecret(
```
Comment (xrstf) [inline pkg/ee/cluster-backup/master/sync-controller/controller.go:180]: Why is this not simply using the SecretReconciler from the reconciling framework?

Comment (rajaSahil) [reply pkg/ee/cluster-backup/master/sync-controller/controller.go:180]: I wasn’t aware of that, just updated it.
Thanks!

File: pkg/ee/cluster-backup/master/sync-controller/controller.go [hunk 2]
```diff
@@ -167,3 +176,35 @@ func (r *reconciler) handleDeletion(ctx context.Context, log *zap.SugaredLogger,
...
+	}
+
+	seedCBSLSecret := &corev1.Secret{}
+	if err := seedClient.Get(ctx, cbslKey, seedCBSLSecret); err != nil && !apierrors.IsNotFound(err) {
+		return fmt.Errorf("failed to fetch CBSL credential secret on seed cluster: %w", err)
+	}
+
+	if seedCBSLSecret.UID != "" && seedCBSLSecret.UID == cbslSecret.UID {
+		return nil
+	}
```
Comment (xrstf) [inline pkg/ee/cluster-backup/master/sync-controller/controller.go]: Counter offer: Move the UID check *into* the `secretReconcilerFactory` and let the reconciling framework take care of fetching the secret from the seed. Inside secretReconcilerFactory you can then simply not do anything with the given secret.

Comment (rajaSahil) [reply pkg/ee/cluster-backup/master/sync-controller/controller.go]: Makes sense, thanks!

**Review by xrstf — APPROVED** [review]
/approve

**Comment by judge-red** [comment]
Any chance to get this backported to 2.28?

**Comment by rajaSahil** [comment]
Yeah, it’s going to be backported to the previous releases.
