### PR TITLE
Fix KubeVirt client schema creation

### LINKED ISSUE #11840: kubermatic-seed-controller-manager crashes with concurrent map writes
### What happened?

kubermatic-seed-controller-manager is occasionally (at 37 restarts since the upgrade yesterday) crashing in our 2.22 QA environment. It seems to be related to kubevirt client code and mirrors what is happening in kubermatic-api (https://github.com/kubermatic/dashboard/issues/5660), also related to kubevirt code.

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 2413 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc00028d880, {{0x4316a19, 0xb}, {0x43050aa, 0x2}, {0x3606da8, 0x16}}, {0x4a31f78?, 0xc001c50100})
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:175 +0x2f7
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc00028d880, {{0x4316a19?, 0x0?}, {0x43050aa?, 0x40dc07?}}, {0xc002b4fef0?, 0xc, 0x7fcea6003ad0?})
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:149 +0x237
kubevirt.io/api/core/v1.AddKnownTypesGenerator.func1(0xc005508be0?)
	kubevirt.io/api@v0.58.0/core/v1/register.go:92 +0x34b
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x4a41960?, 0xc005508be0?)
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme_builder.go:29 +0x5b
k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt.newClient({0xc0018cc000, 0x1626}, {{0x0, {0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, 0x0}, ...})
	k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt/client.go:73 +0x1c2
k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt.NewClient(...)
	k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt/client.go:90
k8c.io/kubermatic/v2/pkg/resources/csi/kubevirt.InfraAccessSecretReconciler.func1.1(0xc00322c280)
	k8c.io/kubermatic/v2/pkg/resources/csi/kubevirt/secret.go:52 +0x2ac
k8c.io/reconciler/pkg/reconciling.SecretObjectWrapper.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/zz_generated_reconcile.go:121 +0x3f
k8c.io/reconciler/pkg/reconciling.CreateWithNamespace.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:46 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithName.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:57 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithNamespace.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:46 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithName.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:57 +0x3d
k8c.io/reconciler/pkg/reconciling.EnsureNamedObject({0x4a44108, 0xc0027b8900}, {{0xc003107008?, 0x0?}, {0x433c986?, 0x0?}}, 0x0?, {0x4a5baa8, 0xc000931140}, {0x4a75f70, ...}, ...)
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:122 +0x602
k8c.io/reconciler/pkg/reconciling.ReconcileSecrets({0x4a44108, 0xc0027b8900}, {0xc004f1db00, 0x1f, 0xc004cd5800?}, {0xc003107008, 0x12}, {0x4a5baa8, 0xc000931140}, {0x0, ...})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/zz_generated_reconcile.go:139 +0x186
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureSecrets(0xc000031a40, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0xc004cd5800?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:506 +0x96
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureResourcesAreDeployed(0xc000031a40, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0x1?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:105 +0x31a
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcileCluster(0xc000031a40?, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0x6d3ea40?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/pending.go:51 +0x19b
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcile(0xc000031a40, {0x4a44108?, 0xc0027b8900}, 0xc000031a40?, 0xc004cd5800)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:310 +0x385
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile.func1()
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:268 +0x9a
k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1/helper.ClusterReconcileWrapper({0x4a44108, 0xc0027b8900}, {0x4a5baa8, 0xc000931140}, {0x7ffccdd2929c, 0x0}, 0xc004cd5800, {{0x49ffdf0, 0x1c}, {0x4a34240, ...}, ...}, ...)
	k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1/helper/helper.go:86 +0xe2
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile(0xc000031a40, {0x4a44108, 0xc0027b8900}, {{{0x0?, 0x10?}, {0xc003815656?, 0x40dc07?}}})
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:252 +0x2f8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4a44108?, {0x4a44108?, 0xc0027b8900?}, {{{0x0?, 0x38f9ea0?}, {0xc003815656?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000c3cbe0, {0x4a44060, 0xc000947fc0}, {0x3d30ea0?, 0xc0030a9400?})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000c3cbe0, {0x4a44060, 0xc000947fc0})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x333
```

### Expected behavior

kubermatic-seed-controller-manager shouldn't be crashing.

### How to reproduce the issue?

Unclear, but looks like interacting with / creating KubeVirt clusters can trigger the code in question.

### How is your environment configured?

- KKP version: v2.22.0-alpha.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Fix schema creation

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/11840

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/kubevirt/client.go [hunk 1]
```diff
@@ -48,6 +60,7 @@ type ClientOptions struct {
 
 func newClient(kubeconfig string, opts ClientOptions) (*Client, error) {
 	var client ctrlruntimeclient.Client
+	opts.ControllerRuntimeOptions.Scheme = scheme
```
Comment (embik) [inline pkg/provider/cloud/kubevirt/client.go:63]: is it a good idea to override this unconditionally? That way you cannot pass a custom scheme anymore, even if you wanted. It would be nice if `opts.ControllerRuntimeOptions.Scheme` was respected if it's not `nil`, and otherwise we use the new scheme added, no?

Comment (mfranczy) [reply pkg/provider/cloud/kubevirt/client.go:63]: I am not convinced that we want to pass a custom scheme for KubeVirt client.

> That way you cannot pass a custom scheme anymore

That's the goal. If you want to do that just use another controller runtime client instance.
Having a strict control over schema makes this piece of code a KubeVirt client, not another generic controller-runtime client.

I want to avoid situation where people using this client override (or even merge) the schema.
It should be related to our KubeVirt features as much as possible.

That's my reasoning.

Comment (mfranczy) [reply pkg/provider/cloud/kubevirt/client.go:63]: However, I could be more explicit about that and potentially return an error when somebody tries to pass schema in the options (or use my own custom options type).

Although I think it's not important for now. We can add it later.

Comment (embik) [reply pkg/provider/cloud/kubevirt/client.go:63]: Yeah I think throwing an error would be nice. I agree it's probably not a good idea to use a different scheme, but just dropping it silently could lead to confusion later on.

Comment (mfranczy) [reply pkg/provider/cloud/kubevirt/client.go:63]: I plan to improve in the near future, for now I would vote to leave it as it is.
I will get rid of the client duplication in the dashboard so at that time i will add necessary checks.

Comment (embik) [reply pkg/provider/cloud/kubevirt/client.go:63]: alright, makes sense.

**Review by embik — APPROVED** [review]
