### PR TITLE
Fix 2.22 MLA Upgrade issues

### LINKED ISSUE #11857: MLA stack upgrade issues
### What happened?

During MLA stack upgrade from MLA [v0.2.5](https://github.com/kubermatic/mla/releases/tag/v0.2.5) (from the external repo) to the version embedded with KKP v2.22.0-alpha.0 the following issues have found:

Consul upgrade:
```
INFO[0010]    📦 Deploying Consul…
INFO[0010]       Updating release from 0.36.0 to 2.22.0-alpha.0…
ERRO[0015] ❌ Operation failed: failed to deploy Consul: failed to deploy Helm release: failed to install:
Error: UPGRADE FAILED: release consul failed, and has been rolled back due to atomic being set: cannot patch "consul-consul-server" with kind StatefulSet: StatefulSet.apps "consul-consul-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden.
```

Loki upgrade:
```
INFO[0589]    📦 Deploying Loki…
INFO[0589]       Updating release from 0.39.0 to 2.22.0-alpha.0…
ERRO[1567] ❌ Operation failed: failed to deploy Loki: failed to deploy Helm release: failed to install: 
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
W0207 09:29:18.132882   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.193633   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.242387   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.273288   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.306733   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.465820   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: UPGRADE FAILED: release loki-distributed failed, and has been rolled back due to atomic being set: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline.
```

Several loki pods (compactor, distributor, ingester, querier, ...) stuck in crashloop, with the following error in the logs:
```
level=error ts=2023-02-07T08:15:11.662677578Z caller=main.go:51 msg="validating config" err="invalid queryrange config: the yaml flag `split_queries_by_interval` must now be set in the `limits_config` section instead of the `query_range` config section"
```

More details can be found in this comment: https://github.com/kubermatic/kubermatic/issues/11753#issuecomment-1420447011

### Expected behavior

The MLA stack upgrade should be successful on first attempt.

### PR DESCRIPTION
**Pull request by wurbanski**
**What this PR does / why we need it**:
* Fixes consul statefulset change not applying correctly
* (partial fix) Adds note about helm timeout during installation (#11850)

**Which issue(s) this PR fixes**:

Fixes #11857 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
MLA: Cortex and Consul operation will be briefly interrupted during the upgrade to patch the required objects
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/install/stack/usercluster-mla/stack.go [hunk 1]
```diff
@@ -91,6 +91,8 @@ func (*UserClusterMLA) Name() string {
 }
 
 func (s *UserClusterMLA) Deploy(ctx context.Context, opt stack.DeployOptions) error {
+	opt.Logger.Info("ℹ️ For usercluster-mla deployment, it is recommended to extend helm timeout by using flag --helm-timeout=15m0s...")
```
Comment (xrstf) [inline pkg/install/stack/usercluster-mla/stack.go]: "by using _the_ `--helm-helmout` flag"

Comment (xrstf) [reply pkg/install/stack/usercluster-mla/stack.go]: And if this is so strongly recommended, shouldn't we use a different default timeout for this stack and only issue this warning if the user gave a lower timeout? Currently this reads like "we know this is slow and our timeout is too small, but we're not setting a sensible default either, so please fix our stuf!" ^^

Comment (wurbanski) [reply pkg/install/stack/usercluster-mla/stack.go]: >shouldn't we use a different default timeout for this stack

fair point...

**Review by embik — APPROVED** [review]
/approve

**Comment by embik** [comment]
/hold

missed the ongoing discussion.

File: pkg/install/stack/usercluster-mla/stack.go (hunk 1 above)
Comment (embik) [reply pkg/install/stack/usercluster-mla/stack.go]: let's update the default timeout if possible, I agree with @xrstf it would make more sense.

Comment (wurbanski) [reply pkg/install/stack/usercluster-mla/stack.go]: I will jump right into it as soon as I'm finished with other incoming PR :)
