### PR TITLE
vSphere tags finalizer fixes

### LINKED ISSUE #11916: Deleting vSphere clusters is stuck after upgrading them from KKP 2.21 to KKP 2.22.0-rc.0
### What happened?

I created several vSphere user clusters on KKP 2.21.6. The KKP installation was then upgraded to 2.22.0-rc.0 as part of our QA efforts. After verifying that the upgrade went well, I wanted to delete the vSphere user clusters, but they are now stuck in deletion with the following finalizers:

```yaml
finalizers:
  - kubermatic.k8c.io/cleanup-credentials-secrets
  - kubermatic.k8c.io/cleanup-namespace
  - kubermatic.k8c.io/cleanup-vsphere-tag-category
```

This is the full log from seed-controller-manager that mentions the cluster name:

<details>

```json
{"level":"info","time":"2023-02-16T10:54:57.539Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Service","namespace":"cluster-spqs5887ks","name":"operating-system-manager-webhook"}
{"level":"info","time":"2023-02-16T10:54:59.324Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.ConfigMap","namespace":"cluster-spqs5887ks","name":"prometheus"}
{"level":"info","time":"2023-02-16T10:54:59.834Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.StatefulSet","namespace":"cluster-spqs5887ks","name":"prometheus"}
{"level":"info","time":"2023-02-16T10:54:59.854Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Secret","namespace":"cluster-spqs5887ks","name":"cloud-config"}
{"level":"info","time":"2023-02-16T10:55:07.152Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Secret","namespace":"cluster-spqs5887ks","name":"etcd-tls-certificate"}
{"level":"info","time":"2023-02-16T10:55:07.740Z","logger":"kkp-cloud-controller","caller":"cloud/cloud_controller.go:193","msg":"Reconciling cloud provider for cluster","cluster":"spqs5887ks"}
{"level":"info","time":"2023-02-16T10:55:08.853Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Secret","namespace":"cluster-spqs5887ks","name":"cloud-config-csi"}
{"level":"info","time":"2023-02-16T10:55:08.928Z","logger":"kkp-kubernetes-controller","caller":"resources/kubeconfig.go:136","msg":"invalid/outdated kubeconfig found, regenerating","namespace":"cluster-spqs5887ks","name":"operatingsystemmanager-webhook-kubeconfig"}
{"level":"info","time":"2023-02-16T10:55:12.139Z","caller":"vsphere/provider.go:95","msg":"reconciling vsphere folder","cluster":"spqs5887ks","folder":"/Hamburg/vm/Kubermatic-dev/spqs5887ks"}
{"level":"info","time":"2023-02-16T10:55:15.925Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Secret","namespace":"cluster-spqs5887ks","name":"operatingsystemmanager-webhook-kubeconfig"}
{"level":"info","time":"2023-02-16T10:55:21.436Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Secret","namespace":"cluster-spqs5887ks","name":"operating-system-manager-webhook-serving-cert"}
{"level":"info","time":"2023-02-16T10:55:23.020Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.NetworkPolicy","namespace":"cluster-spqs5887ks","name":"operating-system-manager-webhook-allow"}
{"level":"info","time":"2023-02-16T10:55:23.926Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.StatefulSet","namespace":"cluster-spqs5887ks","name":"etcd"}
{"level":"info","time":"2023-02-16T10:55:25.340Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"apiserver"}
{"level":"info","time":"2023-02-16T10:55:26.426Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"controller-manager"}
{"level":"info","time":"2023-02-16T10:55:27.022Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"machine-controller"}
{"level":"info","time":"2023-02-16T10:55:28.124Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"machine-controller-webhook"}
{"level":"info","time":"2023-02-16T10:55:28.871Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"usercluster-controller"}
{"level":"info","time":"2023-02-16T10:55:29.542Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"usercluster-webhook"}
{"level":"info","time":"2023-02-16T10:55:30.796Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"vsphere-cloud-controller-manager"}
{"level":"info","time":"2023-02-16T10:55:31.126Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"operating-system-manager"}
{"level":"info","time":"2023-02-16T10:55:31.443Z","caller":"reconciling/ensure.go:116","msg":"created new resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"operating-system-manager-webhook"}
{"level":"info","time":"2023-02-16T10:55:40.937Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.Deployment","namespace":"cluster-spqs5887ks","name":"vsphere-cloud-controller-manager"}
{"level":"info","time":"2023-02-16T10:57:00.553Z","caller":"reconciling/ensure.go:165","msg":"updated resource","kind":"v1.StatefulSet","namespace":"cluster-spqs5887ks","name":"etcd"}





{"level":"error","time":"2023-02-16T11:45:43.533Z","caller":"controller/controller.go:274","msg":"Reconciler error","controller":"kkp-addon-controller","object":{"name":"csi","namespace":"cluster-spqs5887ks"},"namespace":"cluster-spqs5887ks","name":"csi","reconcileID":"b7072e42-da7d-4753-aa28-dbe1f1bdb40f","error":"failed to remove cleanup finalizer: failed to remove finalizers [cleanup-manifests] from Addon cluster-spqs5887ks/csi: addons.kubermatic.k8c.io \"csi\" not found"}
{"level":"error","time":"2023-02-16T11:45:50.633Z","caller":"controller/controller.go:274","msg":"Reconciler error","controller":"kkp-addon-controller","object":{"name":"canal","namespace":"cluster-spqs5887ks"},"namespace":"cluster-spqs5887ks","name":"canal","reconcileID":"b49f56be-5998-466d-a382-fdb0c440d30b","error":"failed to remove cleanup finalizer: failed to remove finalizers [cleanup-manifests] from Addon cluster-spqs5887ks/canal: addons.kubermatic.k8c.io \"canal\" not found"}
```
</details>

### Expected behavior

vSphere clusters created on 2.21 should be deletable on 2.22.

### How to reproduce the issue?

- Create vSphere user cluster on 2.21
- Upgrade KKP to 2.22.0-rc.0
- Attempt to delete vSphere user cluster

### How is your environment configured?

- KKP version: v2.21.6 and v2.22.0-rc.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

vSphere

### What operating system are you running in your user cluster?

N/A

### PR DESCRIPTION
**Pull request by mate4st**
**What this PR does / why we need it**:

With the switch from managing only tags instead of categories the finalizer was renamed without taking care of clusters that had the now orphaned finalizer `kubermatic.k8c.io/cleanup-vsphere-tag-category`  set leading to cluster stuck in termination. 

In addition code that formerly set the finalizer `kubermatic.k8c.io/cleanup-vsphere-tag-category` was removed. Part of the code was to attach the finalizer to the cluster, this logic was not moved for tags. Therefore the new finalizer `kubermatic.k8c.io/cleanup-vsphere-tags` is never set on a cluster object.

This PR intends to delete the oprthaned finalizer  `kubermatic.k8c.io/cleanup-vsphere-tag-category`  unconditionally and set the new finalizer `kubermatic.k8c.io/cleanup-vsphere-tags`  on clusters with tags/categories used. 

**Which issue(s) this PR fixes**:

Fixes #11916

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/vsphere/provider.go [hunk 1]
```diff
@@ -233,6 +235,16 @@ func (v *VSphere) CleanUpCloudProvider(ctx context.Context, cluster *kubermaticv
...
 
+	// remove orphaned Category finalizer
+	if kuberneteshelper.HasFinalizer(cluster, tagCategoryCleanupFinalizer) {
+		cluster, err = update(ctx, cluster.Name, func(cluster *kubermaticv1.Cluster) {
+			kuberneteshelper.RemoveFinalizer(cluster, tagCategoryCleanupFinalizer)
+		})
+		if err != nil {
+			return nil, err
+		}
+	}
```
Comment (embik) [inline pkg/provider/cloud/vsphere/provider.go:246]: I think this could use `kuberneteshelper.TryRemoveFinalizer` instead.

File: pkg/provider/cloud/vsphere/tags.go [hunk 2]
```diff
@@ -36,6 +38,15 @@ func reconcileTags(ctx context.Context, restSession *RESTSession, cluster *kuber
...
 	}
 
+	cluster, err := update(ctx, cluster.Name, func(cluster *kubermaticv1.Cluster) {
+		if !kuberneteshelper.HasFinalizer(cluster, tagCleanupFinalizer) {
+			kuberneteshelper.AddFinalizer(cluster, tagCleanupFinalizer)
+		}
+	})
+	if err != nil {
+		return nil, fmt.Errorf("failed to add finalizer %s on vsphere cluster object: %w", tagCleanupFinalizer, err)
+	}
```
Comment (embik) [inline pkg/provider/cloud/vsphere/tags.go:48]: This could use `kuberneteshelper.TryAddFinalizer`.

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/provider/cloud/vsphere/provider.go (hunk 1 above)
Comment (mate4st) [reply pkg/provider/cloud/vsphere/provider.go:246]: I do not think its possible as I do not have a client available in the function, only the `ClusterUpdater`:
`type ClusterUpdater func(context.Context, string, func(*kubermaticv1.Cluster)) (*kubermaticv1.Cluster, error)`

Comment (embik) [reply pkg/provider/cloud/vsphere/provider.go:246]: True, good point. I take that back :D

File: pkg/provider/cloud/vsphere/tags.go (hunk 2 above)
Comment (embik) [inline pkg/provider/cloud/vsphere/tags.go:48]: This finalizer is already removed in the `provider.go` file during cleanup, no? Am I missing anything?

https://github.com/kubermatic/kubermatic/blob/1c585277eb00e03e6b8ac6660497154aef78e2dd/pkg/provider/cloud/vsphere/provider.go#L229-L236

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/provider/cloud/vsphere/tags.go (hunk 2 above)
Comment (embik) [reply pkg/provider/cloud/vsphere/tags.go:48]: Stupid me, yeah this is _adding_ the finalizer.

**Review by embik — APPROVED** [review]

**Review by embik — APPROVED** [review]
/approve

**Comment by embik** [comment]
/hold

#11921 broke MLA. I'm working on it.

**Comment by embik** [comment]
/hold cancel

Next run should fix it.
