### PR TITLE
initial installer fix

### LINKED ISSUE #464: Test and update the installer
Test if the installer is working.
https://github.com/kubermatic/kubermatic/tree/develop/config/installer 

Update the https://github.com/kubermatic/kubermatic/blob/develop/config/README.md

### PR DESCRIPTION
**Pull request by susman**
closes #464

### CODE REVIEW

**Comment by susman** [comment]
@realfake the idea is to to pass to this container values.yaml as a secret for each new deployment.

File: config/Dockerfile [hunk 1]
```diff
@@ -1,28 +1,28 @@
...
 COPY efk-logging /kubermatic/efk-logging
 COPY k8sniff /kubermatic/k8sniff
-COPY kube-lego /kubermatic/kube-lego
 COPY kubermatic /kubermatic/kubermatic
 COPY nginx-ingress-controller /kubermatic/nginx-ingress-controller
-COPY prometheus /kubermatic/prometheus
+COPY oauth /kubermatic/oauth
 COPY storage /kubermatic/storage
-COPY thirdpartyresources /kubermatic/thirdpartyresources
+COPY drone /kubermatic/drone
```
Comment (mrIncompetent) [inline config/Dockerfile]: No need to have drone in the image.

File: config/deploy_helm_charts.sh [hunk 2]
```diff
@@ -7,8 +7,10 @@ helm upgrade -i k8sniff -f kubermatic-values.yaml -f config/values.yaml k8sniff/
 helm upgrade -i kubermatic -f kubermatic-values.yaml -f config/values.yaml kubermatic/
 helm upgrade -i storage -f kubermatic-values.yaml -f config/values.yaml storage/
 helm upgrade -i nginx-ingress-controller -f kubermatic-values.yaml -f config/values.yaml nginx-ingress-controller/
-helm upgrade -i tpr -f kubermatic-values.yaml -f config/values.yaml thirdpartyresources/
-helm upgrade -i kube-lego -f kubermatic-values.yaml -f config/values.yaml kube-lego/
+helm upgrade -i oauth -f kubermatic-values.yaml -f config/values.yaml oauth/
+helm upgrade -i drone -f kubermatic-values.yaml -f config/values.yaml drone/
```
Comment (mrIncompetent) [inline config/deploy_helm_charts.sh]: No need to have drone in the image.

File: config/deploy_helm_charts.sh [hunk 3]
```diff
@@ -7,8 +7,10 @@ helm upgrade -i k8sniff -f kubermatic-values.yaml -f config/values.yaml k8sniff/
...
+helm upgrade -i certs -f kubermatic-values.yaml -f config/values.yaml certs/
+helm upgrade -i cert-manager -f kubermatic-values.yaml -f config/values.yaml cert-manager/
```
Comment (mrIncompetent) [inline config/deploy_helm_charts.sh]: I can see you're replacing the `prometheus` reference with `monitoring` in the dockerfile.
I assume this need to happen here as well?

File: config/deploy_helm_charts.sh [hunk 4]
```diff
@@ -7,8 +7,10 @@ helm upgrade -i k8sniff -f kubermatic-values.yaml -f config/values.yaml k8sniff/
...
 
 # Logging
 if grep -q '\bLogging\b' config/values.yaml; then
```
Comment (mrIncompetent) [inline config/deploy_helm_charts.sh]: Another thing i noticed is that this script does not handle rbac.
We should follow the documentation and create a serviceaccount & clusterrolebinding.
https://github.com/kubernetes/helm/blob/master/docs/service_accounts.md

File: config/Dockerfile [hunk 5]
```diff
@@ -1,28 +1,28 @@
 FROM alpine:3.6
```
Comment (mrIncompetent) [inline config/Dockerfile:1]: Is alpine a good choice for this case? Due to missing glibc we might run into issues.
Maybe we should switch to debian? (its the base for the hyperkube images. So we'll download it anyway)

**Review by mrIncompetent — DISMISSED** [review]

File: config/Dockerfile (hunk 5 above)
Comment (susman) [reply config/Dockerfile:1]: If helm is the only binary that'd run in the container - we don't need more that that.

File: config/deploy_helm_charts.sh [hunk 6]
```diff
@@ -7,16 +7,17 @@ helm upgrade -i k8sniff -f kubermatic-values.yaml -f config/values.yaml k8sniff/
...
   helm upgrade -i efk-logging -f kubermatic-values.yaml -f config/values.yaml efk-logging/
 fi
 #Monitoring
 if grep -q '\bPrometheus\b' config/values.yaml; then
-  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml prometheus/
+  helm upgrade -i prometheus -f kubermatic-values.yaml -f config/values.yaml monitoring/prometheus/
```
Comment (metalmatze) [inline config/deploy_helm_charts.sh]: This will fail deploying, because prometheus needs to have a prometheus operator deploy for all CRDs.

**Review by metalmatze — DISMISSED** [review]

File: config/deploy_helm_charts.sh (hunk 6 above)
Comment (susman) [reply config/deploy_helm_charts.sh]: Commits on the branch are more than welcome

File: config/deploy_helm_charts.sh (hunk 4 above)
Comment (susman) [reply config/deploy_helm_charts.sh]: fixed

File: config/deploy_helm_charts.sh (hunk 6 above)
Comment (mrIncompetent) [reply config/deploy_helm_charts.sh]: @metalmatze What is the correct way of deploying the monitoring stack?

Comment (metalmatze) [reply config/deploy_helm_charts.sh]: First the Prometheus Operator needs to be deployed, because it contains all the CRDs needed by the other stacks. Then you can deploy prometheus, alertmanager, kube-state-metrics, node-exporter and grafana in a random order (I think, not tested).

File: config/deploy_helm_charts.sh [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+   sleep 5
+done
+
+############# Kubermatic #############
+helm ${HELM_OPTS} upgrade -i storage -f ${VALUESFILE} storage/
+helm ${HELM_OPTS} upgrade -i k8sniff -f ${VALUESFILE} k8sniff/
+helm ${HELM_OPTS} upgrade -i nginx -f ${VALUESFILE} nginx-ingress-controller/
+helm ${HELM_OPTS} upgrade -i oauth -f ${VALUESFILE} oauth/
+helm ${HELM_OPTS} upgrade -i kubermatic -f ${VALUESFILE} kubermatic/
+helm ${HELM_OPTS} upgrade -i --namespace=cert-manager cert-manager -f ${VALUESFILE} cert-manager/
```
Comment (lbb) [inline config/deploy_helm_charts.sh]: We should either have a consistent namespace pattern existent for all charts or specify it every time.

**Review by lbb — CHANGES_REQUESTED** [review]

**Review by lbb — DISMISSED** [review]
🎖

**Review by lbb — APPROVED** [review]
Weil ich es kann
