### PR TITLE
Delete orphaned UserProjectBinding resources on User or Project deletion

### LINKED ISSUE #15098: UserProjectBindings for Serviceaccounts are not cleaned up after deletion
### What happened?

When deleting a serviceaccount in a kkp project the related userprojectbinding is not cleaned up. Since this resource is related to a serviceaccount, it should be cleaned up, when its parent resource is deleted.

Customer Reference: 8393

### Expected behavior

Userprojectbinding related to the deleted kkp serviceaccount is cleaned up.

### How to reproduce the issue?

Create and delete a serviceaccount in kkp. You should see a userprojectbinding for the deleted serviceaccount in kkp master cluster.

### How is your environment configured?

- KKP version: v2.28
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by rajaSahil**
**What this PR does / why we need it**:
This PR adds logic to delete orphaned UserProjectBinding resources when either the corresponding User or Project is deleted.

**Which issue(s) this PR fixes**:

Fixes #15098 

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Delete orphaned UserProjectBinding resources on User or Project deletion.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/master-controller-manager/user-project-binding/controller.go [hunk 1]
```diff
@@ -97,17 +97,17 @@ func (r *reconcileSyncProjectBinding) Reconcile(ctx context.Context, request rec
 func (r *reconcileSyncProjectBinding) reconcile(ctx context.Context, log *zap.SugaredLogger, projectBinding *kubermaticv1.UserProjectBinding) error {
 	project, err := r.getProjectForBinding(ctx, projectBinding)
 	if err != nil {
-		if apierrors.IsNotFound(err) {
-			return r.removeFinalizerFromBinding(ctx, projectBinding)
+		if err := r.Delete(ctx, projectBinding); err != nil && !apierrors.IsNotFound(err) {
```
Comment (kron4eg) [inline pkg/controller/master-controller-manager/user-project-binding/controller.go]: But how it will be removed without removing finalizer?

Comment (rajaSahil) [reply pkg/controller/master-controller-manager/user-project-binding/controller.go]: We don’t add any finalizer for the ServiceAccount UserProjectBinding, which is why it worked correctly during testing, have addressed it.

**Review by kron4eg — APPROVED** [review]
/approve
