### PR TITLE
KubeVirt fix upgrade issue from KKP 2.21 to KKP 2.22 for CSI access

### LINKED ISSUE #11880: KubeVirt upgrade issue: cluster not ready due to kubevirt-csi sa secret token reconciliation failure
### What happened?

During an upgrade from KKP 2.21 to KKP 2.22 (k8s 1.23.6), the upgrade of an existing KubeVirt cluster failed.
The cluster never becomes ready.
The error is:
```
failed to reconcile cluster: failed to ensure that the Secret exists: failed to ensure Secret cluster-cbhz52rgcf/csi-infra-kubeconfig: failed to generate object: serviceaccounts "kubevirt-csi" not found
```

Note that this error did not happen on the various upgrade done on the QA env. It happened only on Marcin's env.
Note that on QA, k8s versions were always >= 1.24.

### Expected behavior

The upgrade is successful, kubevirt CSI drive SA and secret are created.

### How is your environment configured?

- KKP version: 1.23.6
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

KubeVirt

### What operating system are you running in your user cluster?

no impact.

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
Fixes a reconciliation error when upgrading from KKP 2.21 to 2.22 (KubeVirt CSI driver SA not created).

**NO backport needed, this is new in KKP 2.22**

**Which issue(s) this PR fixes**:

Fixes #11880 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/provider/cloud/kubevirt/provider.go [hunk 1]
```diff
@@ -130,7 +130,7 @@ func (k *kubevirt) reconcileCluster(ctx context.Context, cluster *kubermaticv1.C
 		return cluster, err
 	}
 
-	err = reconcileInfraTokenAccess(ctx, cluster.Status.NamespaceName, client)
+	err = ReconcileInfraTokenAccess(ctx, cluster.Status.NamespaceName, client)
```
Comment (mfranczy) [inline pkg/provider/cloud/kubevirt/provider.go:133]: just a nit, please inside the function change the SA name that is taken from
`resource.KubeVirtCSIServiceAccountName` instead of `csiResourceName`

Comment (mfranczy) [reply pkg/provider/cloud/kubevirt/provider.go:133]: basically we should replace constant `csiResourceName` with `resource.KubeVirtCSIServiceAccountName` in the whole CSI file.

Comment (hdurand0710) [reply pkg/provider/cloud/kubevirt/provider.go:133]: done

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by hdurand0710** [comment]
cc @kubermatic/sig-release-managers
