### PR TITLE
Fix etcd migration

### LINKED ISSUE #1326: Fix etcd migration

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Change the way we migration from the operator to the StatefulSet.
Instead of letting every etcd pod get a snapshot & restore from it, restore only on the master & then add each member.

Fixes #1326 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: api/pkg/resources/etcd/statefulset.go [hunk 1]
```diff
@@ -64,7 +64,19 @@ func StatefulSet(data *resources.TemplateData, existing *appsv1.StatefulSet) (*a
...
-	etcdStartCmd, err := getEtcdStartCommand(data)
+	// For migration purpose.
+	// We switched from the etcd-operator to a simple etcd-StatefulSet. Therefore we need to migrate the data.
+	var migrate bool
+	_, err := data.ServiceLister.Services(data.Cluster.Status.NamespaceName).Get("etcd-cluster-client")
+	if err != nil {
+		if !errors.IsNotFound(err) {
+			return nil, err
+		}
+	} else {
```
Comment (alvaroaleman) [inline api/pkg/resources/etcd/statefulset.go:75]: That else catches the case `err == nil`, it must be an else for the `if !errors.IsNotFound(err)` instead

File: api/pkg/resources/etcd/statefulset.go [hunk 2]
```diff
@@ -241,28 +204,61 @@ func getEtcdCommand(data *resources.TemplateData, cmdTpl string) ([]string, erro
...
+    if [ "${POD_NAME}" = "etcd-2" ]; then
+        echo "i'm etcd-2. I join as new member as soon as we have 2 existing & healthy members"
+        until etcdctl --endpoints ${MASTER_ENDPOINT} member list | grep -q etcd-1; do sleep 1; echo "Waiting for etcd-1"; done
+        INITIAL_STATE="existing"
+        INITIAL_CLUSTER="etcd-0=http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-1=http://etcd-1.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-2=http://etcd-2.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380"
+    fi
 fi
+
+{{ else }}
+INITIAL_STATE="new"
```
Comment (alvaroaleman) [inline api/pkg/resources/etcd/statefulset.go]: This covers the case migrate == false, thus this must be `existing`, right?

**Review by alvaroaleman — CHANGES_REQUESTED** [review]

File: api/pkg/resources/etcd/statefulset.go [hunk 3]
```diff
@@ -241,28 +204,61 @@ func getEtcdCommand(data *resources.TemplateData, cmdTpl string) ([]string, erro
...
+INITIAL_CLUSTER="etcd-0=http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-1=http://etcd-1.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-2=http://etcd-2.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380"
+{{ end }}
+
+echo ${INITIAL_STATE}
+echo ${INITIAL_CLUSTER}
+
+/usr/local/bin/etcd \
```
Comment (alvaroaleman) [inline api/pkg/resources/etcd/statefulset.go]: Please use `exec` here to ensure the etcd is not a child of the shell

File: api/pkg/resources/etcd/statefulset.go (hunk 1 above)
Comment (mrIncompetent) [reply api/pkg/resources/etcd/statefulset.go:75]: But we only want the migrate if we could successfully find a service from the etcd-operator?

File: api/pkg/resources/etcd/statefulset.go (hunk 2 above)
Comment (mrIncompetent) [reply api/pkg/resources/etcd/statefulset.go]: No, `new` is fine. Otherwise the etcd won't initialize. During runtime, it will ignore the flag and start from what is on the filesystem

File: api/pkg/resources/etcd/statefulset.go (hunk 1 above)
Comment (alvaroaleman) [reply api/pkg/resources/etcd/statefulset.go:75]: Oh you are right

File: api/pkg/resources/etcd/statefulset.go [hunk 4]
```diff
@@ -198,56 +198,70 @@ func getEtcdCommand(name, namespace string, migrate bool) ([]string, error) {
...
-		"-ecx",
+		"-ec",
 		buf.String(),
 	}, nil
 }
 
 const (
-	etcdStartCommandTpl = `ETCDCTL_API=3
-MASTER_ENDPOINT="http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2379"
+	etcdStartCommandTpl = `export MASTER_ENDPOINT="http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2379"
```
Comment (alvaroaleman) [inline api/pkg/resources/etcd/statefulset.go]: maybe add a `export ETCDCTL_API=3` here to not have it as a prefix for every `etcdctl` call?

File: api/pkg/resources/etcd/statefulset.go [hunk 5]
```diff
@@ -198,56 +198,70 @@ func getEtcdCommand(name, namespace string, migrate bool) ([]string, error) {
...
 
 {{ if .Migrate }}
 # If we're already initialized
 if [ -d "{{ .DataDir }}" ]; then
-    INITIAL_STATE="existing"
-    INITIAL_CLUSTER="etcd-0=http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-1=http://etcd-1.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380,etcd-2=http://etcd-2.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380"
+    echo "we're already initialized"
+    if [ "${POD_NAME}" = "etcd-0" ]; then
+        export INITIAL_CLUSTER="etcd-0=http://etcd-0.{{ .ServiceName }}.{{ .Namespace }}.svc.cluster.local:2380"
+        export INITIAL_STATE="existing"
```
Comment (alvaroaleman) [inline api/pkg/resources/etcd/statefulset.go]: This is `INITIAL_STATE="existing` is true when the datadir already exists and has nothing to do with which pod we are running in, right? If yes, please move it to line 212 after the `if [ -d "{{ .DataDir }}" ]; then` and remove the redudant statements here and below

File: api/pkg/resources/etcd/statefulset.go (hunk 4 above)
Comment (mrIncompetent) [reply api/pkg/resources/etcd/statefulset.go]: Good point, i moved it there for debugging purpose

File: api/pkg/resources/etcd/statefulset.go (hunk 5 above)
Comment (mrIncompetent) [reply api/pkg/resources/etcd/statefulset.go]: Good point!

**Review by metalmatze — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]
