### PR TITLE
addons controller: hetzner CSI: redeploy CSIDriver to allow upgrade from v2.22 to v2.23

### LINKED ISSUE #12429: CSIDriver `csi.hetzner.cloud` is invalid: spec.fsGroupPolicy - field is immutable
### What happened?

We discovered during upgrading an internal KKP installation that the Hetzner CSI addon fails to apply:

```json
{"level":"error","time":"2023-06-30T07:33:53.825Z","caller":"controller/controller.go:274","msg":"Reconciler error","controller":"kkp-addon-controller","object":{"name":"csi","namespace":"cluster-jlp86llkdl"},"namespace":"cluster-jlp86llkdl","name":"csi","reconcileID":"a99cc40b-aef0-4c84-9ace-79e4a3218911","error":"failed to deploy the addon manifests into the cluster: failed to execute '/usr/local/bin/kubectl-1.26 --kubeconfig /tmp/cluster-jlp86llkdl-addon-csi-kubeconfig apply --prune --filename /tmp/cluster-jlp86llkdl-csi.yaml --selector kubermatic-addon=csi' for addon csi of cluster jlp86llkdl: exit status 1\nsecret/hcloud-csi unchanged\nserviceaccount/hcloud-csi unchanged\[nclusterrole.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrole.rbac.authorization.k8s.io/hcloud-csi) unchanged\[nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi) unchanged\ndeployment.apps/hcloud-csi-controller created\ndaemonset.apps/hcloud-csi-node configured\nservice/hcloud-csi-controller-metrics unchanged\nservice/hcloud-csi-node-metrics unchanged\nThe CSIDriver \"csi.hetzner.cloud\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n","errorCauses":[{"error":"failed to deploy the addon manifests into the cluster: failed to execute '/usr/local/bin/kubectl-1.26 --kubeconfig /tmp/cluster-jlp86llkdl-addon-csi-kubeconfig apply --prune --filename /tmp/cluster-jlp86llkdl-csi.yaml --selector kubermatic-addon=csi' for addon csi of cluster jlp86llkdl: exit status 1\nsecret/hcloud-csi unchanged\nserviceaccount/hcloud-csi unchanged\[nclusterrole.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrole.rbac.authorization.k8s.io/hcloud-csi) unchanged\[nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi](http://nclusterrolebinding.rbac.authorization.k8s.io/hcloud-csi) unchanged\ndeployment.apps/hcloud-csi-controller created\ndaemonset.apps/hcloud-csi-node configured\nservice/hcloud-csi-controller-metrics unchanged\nservice/hcloud-csi-node-metrics unchanged\nThe CSIDriver \"csi.hetzner.cloud\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n"}]}
```

The gist is that #12191 changed an immutable field on the `CSIDriver` resource for `csi.hetzner.cloud` and in KKP v2.23.0, the addon fails to apply.

### Expected behavior

The CSI addon can be applied/upgraded from KKP 2.22 to 2.23.

### How to reproduce the issue?

- Create Hetzner user cluster on KKP 2.22 with CCM/CSI enabled.
- Upgrade KKP setup to 2.23.0.
- Observe addon failures from seed-controller-manager logs.

### How is your environment configured?

- KKP version: v2.23.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Hetzner

### What operating system are you running in your user cluster?

N/A

### Additional information

A workaround for this is deleting the `csidriver` resource (`kubectl delete csidriver csi.hetzner.cloud`) and letting the addon-controller recreate it.

### PR DESCRIPTION
**Pull request by wozniakjan**
**What this PR does / why we need it**:
Before reconciling hetzner CSI addon, delete the `CSIDriver` resource if it has a mismatch in `fsGroupPolicy`, so the addon can be applied. Between KKP v2.22 and v2.23 https://github.com/kubermatic/kubermatic/pull/11968 introduced a change to an immutable field `fsGroupPolicy`, the upstream recommends recreating the `CSIDriver`:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1682-csi-driver-skip-permission#risks-and-mitigations

**Which issue(s) this PR fixes**:

fixes: https://github.com/kubermatic/kubermatic/issues/12429

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:
Should we add docs too to instruct users for the manual remediation of deleting the `CSIDriver` resource?

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
hetzner CSI: recreate CSIDriver to allow upgrade from 1.6.0 to 2.2.0
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/seed-controller-manager/addon/addon_controller.go [hunk 1]
```diff
@@ -506,6 +508,29 @@ func (r *Reconciler) getApplyCommand(ctx context.Context, kubeconfigFilename, ma
 	return cmd, nil
 }
 
+// Between v2.22 and v2.23, there was a change to hetzner CSI driver immutable field fsGroupPolicy
+// as a result, the CSDriver resource has to be redeployed
+// https://github.com/kubermatic/kubermatic/issues/12429
+func (r *Reconciler) migrateHetznerCSIDriver(ctx context.Context, log *zap.SugaredLogger, addon *kubermaticv1.Addon, cluster *kubermaticv1.Cluster) error {
+	cl, err := r.KubeconfigProvider.GetClient(ctx, cluster)
+	if err != nil {
+		return fmt.Errorf("Failed to get kube client: %w", err)
```
Comment (xrstf) [inline pkg/controller/seed-controller-manager/addon/addon_controller.go]: please use consistently lowercase letters at the beginning of error messages :)

File: pkg/controller/seed-controller-manager/addon/addon_controller.go [hunk 2]
```diff
@@ -532,6 +562,14 @@ func (r *Reconciler) ensureIsInstalled(ctx context.Context, log *zap.SugaredLogg
 
 	cmdLog := log.With("cmd", strings.Join(cmd.Args, " "))
 
+	if addon.Name == "csi" && cluster.Spec.Cloud.Hetzner != nil && cluster.Spec.Features[kubermaticv1.ClusterFeatureExternalCloudProvider] {
```
Comment (wozniakjan) [inline pkg/controller/seed-controller-manager/addon/addon_controller.go]: otherwise the addon will not deploy CSIDriver
https://github.com/kubermatic/kubermatic/blob/4782385290c867df50597a7b0670b82478cb7588/addons/csi/hetzner/hcloud-csi.yaml#L22

**Comment by wozniakjan** [comment]
following log line appears exactly once
```
2023-06-30T15:54:44.422+0200    debug   kkp-addon-controller    addon/addon_controller.go:530   deleting hetzner CSIDriver to allow upgrade {"worker-name": "jwozniak", "cluster": "dmsjc899ln", "addon": "csi"}
```

File: pkg/controller/seed-controller-manager/addon/addon_controller.go [hunk 3]
```diff
@@ -532,6 +558,14 @@ func (r *Reconciler) ensureIsInstalled(ctx context.Context, log *zap.SugaredLogg
...
+		// Between v2.22 and v2.23, there was a change to hetzner CSI driver immutable field fsGroupPolicy
+		// as a result, the CSDriver resource has to be redeployed
+		// https://github.com/kubermatic/kubermatic/issues/12429
+		if err := r.migrateHetznerCSIDriver(ctx, log, cluster); err != nil {
+			return fmt.Errorf("failed to migrate CSI Driver: %w", err)
+		}
```
Comment (embik) [inline pkg/controller/seed-controller-manager/addon/addon_controller.go:569]: While #10821 did the migration in a different place, I would vastly prefer if this migration logic also set a similar annotation, something like `kubermatic.k8c.io/migrated-hetzner-csi-addon` and checked for it. Running the `migrateHetznerCSIDriver` function every time the CSI driver gets reconciled feels expensive, especially given the fact that I don't think the called client is a cached one (I might be wrong here though).

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/controller/seed-controller-manager/addon/addon_controller.go (hunk 3 above)
Comment (wozniakjan) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:569]: sure, I can add the annotation, however, it is executed right before `kubectl apply` is called on multiple templated resources including this `CSIDriver`. Which is easily going to dominate checking this single resource.

Comment (embik) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:569]: That's a fair point, but I would still better sleep at night if we made sure migration code only actually runs once. We just discovered a case where migration logic continuously ran.

Comment (wozniakjan) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:569]: ptal @embik, I added an annotation with `Update`. Errors in applying the annotation are purposefully just logged, in the worst case, the annotation will be applied in the next reconciliation. But overall the amortized cost of this will be dominated by the `kubectl apply` behaviour of the addons controller.

Comment (embik) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:569]: Thanks!

File: pkg/controller/seed-controller-manager/addon/addon_controller.go [hunk 4]
```diff
@@ -530,8 +557,26 @@ func (r *Reconciler) ensureIsInstalled(ctx context.Context, log *zap.SugaredLogg
 		return fmt.Errorf("failed to create command: %w", err)
 	}
 
-	cmdLog := log.With("cmd", strings.Join(cmd.Args, " "))
+	if addon.Name == "csi" &&
+		cluster.Spec.Cloud.Hetzner != nil &&
+		cluster.Spec.Features[kubermaticv1.ClusterFeatureExternalCloudProvider] &&
+		cluster.Annotations[migratedHetznerCSIAddon] != "yes" {
```
Comment (embik) [inline pkg/controller/seed-controller-manager/addon/addon_controller.go:563]: just a very minor edge-case nit, can you add a check for `cluster.Annotations` (not) being nil before we try to access it here so we don't run into this? It shouldn't happen, but I'm always uncomfortable accessing maps that can be nil.

```suggestion
		(cluster.Annotations == nil || cluster.Annotations[migratedHetznerCSIAddon] != "yes") {
```

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/controller/seed-controller-manager/addon/addon_controller.go (hunk 4 above)
Comment (wozniakjan) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:563]: aren't these two statements semantically equivalent? Reading from nil map will return the default value for any key (so an empty string in this case).

Comment (embik) [reply pkg/controller/seed-controller-manager/addon/addon_controller.go:563]: Sorry, you are right. Brain messed up, this only applies to write operations. Nvm!

**Review by embik — APPROVED** [review]
/approve
