### PR TITLE
fix vsphere credential separation

### LINKED ISSUE #13534: Credentials configured for infraManagementUser end up in user clusters
### What happened?

If two different sets of credentials are provided for the vSphere cloud provider (CCM and CSI) and infrastructure management (KKP / machine-controller) functionality by specifying dedicated credentials for the infrastructure management functionality on the seed level with `Seed.spec.datacenters.${DC_NAME}.vsphere.infraManagementUser` and supplying additional credentials for the cloud provider functionality with `Cluster.spec.cloud.vsphere.username / password`, the credentials for the infrastructure management functionality end up in the user cluster e.g. in the secret `cloud-config-csi`.

### Expected behavior

* The credentials for the infrastructure management functionality (defined in either `Seed.spec.datacenters.${DC_NAME}.vsphere.infraManagementUser` or `Cluster.spec.cloud.vsphere.infraManagementUser`) are used by the machine-controller and do not end up in the user cluster
* The credentials for the cloud provider functionality (defined in either `Cluster.spec.cloud.vsphere.username / password` or `Preset.spec.vsphere.username / password`) are passed into the user cluster and used by the CCM / CSI

### How to reproduce the issue?

1. Configure dedicated credentials for the infrastructure management functionality on the seed level with `Seed.spec.datacenters.${DC_NAME}.vsphere.infraManagementUser`
1. Create a user cluster in the configured vSphere  datacenter and manually supply credentials for the cloud provider functionality
1. Check the environment variables `VSPHERE_USERNAME` and `VSPHERE_PASSWORD` of the machine-controller running on the seed cluster - they should contain the manually supplied credentials for the cloud provider functionality (not 100% sure)
1. Check the connect of the secret `cloud-config-csi` in the `kube-system` namespace - the cloud config will contain the credentials defined for the `infraManagementUser`

### How is your environment configured?

- KKP version: 2.25.3
- Shared or separate master/seed clusters?: Separate master / seed cluster

### Provide your KKP manifest here (if applicable)

Not relevant

### What cloud provider are you running on?

vSphere

### What operating system are you running in your user cluster?

Not relevant

### PR DESCRIPTION
**Pull request by soer3n**
**What this PR does / why we need it**:

This pull request correct the handling of given vsphere credentials. Until now the infra credentials always overide other credentials for all purposes including cloud config for ccm and csi plugin. With these changes the infra user will only be used for the machine controller if specified and user credentials for cloud configs. When no infra credentials given the user credentials will be used for everything.

**Which issue(s) this PR fixes**:

Fixes #13534 and #13995

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
[Breaking Changes] Vsphere credentials are now handled properly. For existing usercluster this will change the credentials in machine-controller and osm to `infraManagementUser` and  `infraManagementPassword` instead of `username` and `password` when specified. The latter one was always mounted to the before mentioned deployments in the past.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
cc @ahmedwaleedmalik 

@soer3n please create a testing ticket for this, I'll try to review it today or before EOD tomorrow.

File: pkg/provider/kubernetes/credentials.go [hunk 1]
```diff
@@ -411,18 +411,46 @@ func createOrUpdateKubevirtSecret(ctx context.Context, seedClient ctrlruntimecli
...
+	vsphereInfraUser := spec.Username
+	if spec.InfraManagementUser.Username != "" {
+		vsphereInfraUser = spec.InfraManagementUser.Username
+	}
+
+	vsphereInfraPassword := spec.Password
+	if spec.InfraManagementUser.Password != "" {
+		vsphereInfraPassword = spec.InfraManagementUser.Password
+	}
+
```
Comment (ahmedwaleedmalik) [inline pkg/provider/kubernetes/credentials.go]: vsphereInfraPassword and vsphereInfraPassword should be empty if they are not specified. By your logic, they will always be configured as `VsphereInfraManagementUserUsername=username` and `VsphereInfraManagementUserPassword=password` when not specified, which is wrong, unfortunately.

This can be highly confusing for the end users since they never specified the infra management credentials but somehow they have been injected by KKP.

File: pkg/provider/kubernetes/credentials.go [hunk 2]
```diff
@@ -411,18 +411,46 @@ func createOrUpdateKubevirtSecret(ctx context.Context, seedClient ctrlruntimecli
...
+		if val, _ := secretKeySelector(spec.CredentialsReference, resources.VsphereUsername); val != "" {
+			spec.Username = val
+		}
+	}
+
+	if val, _ := secretKeySelector(spec.CredentialsReference, resources.VsphereInfraManagementUserPassword); val == "" {
+		if val, _ := secretKeySelector(spec.CredentialsReference, resources.VspherePassword); val != "" {
+			spec.Password = val
+		}
+	}
```
Comment (ahmedwaleedmalik) [inline pkg/provider/kubernetes/credentials.go]: Looking at the code itself, I don't believe we need to modify anything in the `createVSphereSecret` function.

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

@soer3n please write a release note. Once the testing for this is done against the testing ticket, we should also backport this.

**Comment by archups** [comment]
@soer3n  can you please add release note to this PR. Thanks!
