### PR TITLE
prevents from sending on closed channel

### LINKED ISSUE #731: cluster-controller sending on closed channel
The cluster controller at syseleven just crashed with one of its goroutines and is dandling in an inconsistent state, not terminating. 
I only found out because Prometheus alerts where sent into your #alerting-syseleven slack channel and I looked into the alert.

```
I0208 07:11:42.222519       8 leaderelection.go:243] lock is held by cluster-controller-v1-157767814-6g22f-kubermatic-cluster-controller and has not yet expired
I0208 07:11:42.238889       8 leaderelection.go:203] failed to renew lease kube-system/kubermatic-cluster-controller: timed out waiting for the condition
I0208 07:11:42.268194       8 main.go:196] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kubermatic-cluster-controller", UID:"45fed553-e410-11e7-aa6b-fa163e12ceaa", APIVersion:"v1", ResourceVersion:"90690875", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cluster-controller-v1-157767814-gb9rd-kubermatic-cluster-controller stopped leading
E0208 07:11:42.268272       8 main.go:162] ==================== OnStoppedLeading ====================
I0208 07:11:42.519902       8 controller.go:371] Shutting down cluster controller
E0208 07:11:42.519947       8 main.go:113] Stopping os signal notifier: <nil>
E0208 07:11:42.519954       8 main.go:136] Stopping internal http server: <nil>
I0208 07:11:42.522830       8 main.go:140] Shutting down the internal http server
E0208 07:11:42.732666       8 main.go:180] Stopping controller: <nil>
panic: close of closed channel

goroutine 1 [running]:
main.main.func6(0x0, 0x0)
	/go/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-cluster-controller/main.go:181 +0x9c
github.com/kubermatic/kubermatic/api/vendor/github.com/oklog/run.(*Group).Run(0xc420549e30, 0xc4201aac00, 0x2)
	/go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/oklog/run/group.go:47 +0x141
main.main()
	/go/src/github.com/kubermatic/kubermatic/api/cmd/kubermatic-cluster-controller/main.go:185 +0xbaf
```

Sadly the controller keeps on running as it is in a inconsistent state.
Like this it seems that it is able to stay in a deadlock or something, but it's not possible to be scraped by Prometheus in this state anymore.
It is just sitting there doing nothing and blocks new instances being scheduled.

@mrIncompetent

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: prevents from sending on closed channel by using context for cancellation instead of "raw" channels.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #731

### CODE REVIEW

File: api/cmd/kubermatic-cluster-controller/main.go [hunk 1]
```diff
@@ -148,21 +150,22 @@ func main() {
...
+					err := startController(ctx.Done(), dcs, masterConfig, seedCmdConfig, versions, updates)
 					if err != nil {
 						glog.Error(err)
+						ctxDone()
 					}
-					close(leaderElectionStop)
 				},
 				OnStoppedLeading: func() {
 					glog.Error("==================== OnStoppedLeading ====================")
-					close(controllerStop)
```
Comment (p0lyn0mial) [inline api/cmd/kubermatic-cluster-controller/main.go:165]: when the leadership was lost we also closed `leaderElectionStop` channel. This in turn  lead to line 183 where we were trying to close `controllerStop` one more time.

**Review by mrIncompetent — APPROVED** [review]
