### PR TITLE
Fix web socket connections timeout

### LINKED ISSUE #11755: Fix request time limitation for web socket connections
### What happened?
Nginx ingress limits all API requests to a 1 minute timeout, which makes web socket connections (like for web terminal) be disconnected after 1 minute.

### Expected behavior
Web socket connections should remain active.

### How to reproduce the issue?
Create a user cluster, start web terminal for it and wait 1 minute until you are disconnected.

### What cloud provider are you running on?
It can be reproduced in any cloud provider.

### PR DESCRIPTION
**Pull request by hbernardo**
**What this PR does / why we need it**:
NGINX ingress limits all API requests to a 1 minute timeout, which makes web socket connections (like for Web Terminal) be disconnected after 1 minute.

**Which issue(s) this PR fixes**:

Fixes #11755

**What type of PR is this?**

/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Set nginx ingress `proxy-read-timeout` and `proxy-send-timeout` to 1 hour to support long-lasting connections (e.g. websocket)
```

**Documentation**:

```documentation
https://github.com/kubermatic/docs/pull/1336
```

### CODE REVIEW

File: pkg/controller/operator/master/resources/kubermatic/common.go [hunk 1]
```diff
@@ -97,7 +97,12 @@ func IngressReconciler(cfg *kubermaticv1.KubermaticConfiguration) reconciling.Na
 			if i.Annotations == nil {
 				i.Annotations = make(map[string]string)
 			}
-			i.Annotations["kubernetes.io/ingress.class"] = cfg.Spec.Ingress.ClassName
+			i.Annotations["kubernetes.io/ingress.class"] = cfg.Spec.Ingress.ClassNam
```
Comment (ahmedwaleedmalik) [inline pkg/controller/operator/master/resources/kubermatic/common.go]:
```suggestion
			i.Annotations["kubernetes.io/ingress.class"] = cfg.Spec.Ingress.ClassName
```

File: pkg/controller/operator/master/resources/kubermatic/common.go [hunk 2]
```diff
@@ -97,7 +97,12 @@ func IngressReconciler(cfg *kubermaticv1.KubermaticConfiguration) reconciling.Na
...
+
+			// NGINX ingress annotations to avoid timeout of websocket connections after 1 minute.
+			// Needed for Web Terminal feature, for example.
+			i.Annotations["nginx.ingress.kubernetes.io/proxy-read-timeout"] = "3600" // 1 hour
+			i.Annotations["nginx.ingress.kubernetes.io/proxy-send-timeout"] = "3600" // 1 hour
```
Comment (ahmedwaleedmalik) [inline pkg/controller/operator/master/resources/kubermatic/common.go:105]: > NGINX ingress annotations to avoid timeout of websocket connections after 1 minute

To avoid timeout after 1 minute, we are setting the timeout to 1 hour?

Comment (hbernardo) [reply pkg/controller/operator/master/resources/kubermatic/common.go:105]: 1 hour if no "read" or "send" activity happens.

Comment (ahmedwaleedmalik) [reply pkg/controller/operator/master/resources/kubermatic/common.go:105]: 1 hour seems way too much to me but maybe it's fine. @rastislavs WDYT?

Comment (ahmedwaleedmalik) [reply pkg/controller/operator/master/resources/kubermatic/common.go:105]: 1 hour seems way too much to me but maybe it's fine. @rastislavs WDYT?

Comment (rastislavs) [reply pkg/controller/operator/master/resources/kubermatic/common.go:105]: I think 3600 is fine. It also matches with similar timeout [that we have on the nodeport-proxy](https://github.com/kubermatic/kubermatic/blob/main/pkg/resources/nodeportproxy/nodeportproxy.go#L441).

Comment (ahmedwaleedmalik) [reply pkg/controller/operator/master/resources/kubermatic/common.go:105]: Fair point, lgtm then :D

**Comment by ahmedwaleedmalik** [comment]
cc @kubermatic/sig-release-managers

**Review by xmudrii — APPROVED** [review]
