### PR TITLE
Applications: discover if a release is stuck and rollback if necessary

### LINKED ISSUE #12846: System application `cilium` stops upgrading because another operation appears to be in progress
### What happened?

On our captain environment, a majority of user clusters that use the `cilium` system application as CNI are failing to upgrade the Cilium Helm chart to deploy any updates (e.g. when trying to update from 1.13.3 to 1.13.8). The `user-cluster-controller-manager` logs:

```json
{"level":"info","time":"2023-11-16T09:50:02.361Z","logger":"kkp-app-installation-controller","caller":"action/upgrade.go:144","msg":"preparing upgrade for kube-system-cilium","applicationinstallation":"kube-system/cilium"}
{"level":"error","time":"2023-11-16T09:50:02.651Z","logger":"kkp-app-installation-controller","caller":"application-installation-controller/controller.go:139","msg":"ReconcilingError","applicationinstallation":"kube-system/cilium","error":"handling installation of application installation: another operation (install/upgrade/rollback) is in progress"}
{"level":"error","time":"2023-11-16T09:50:02.651Z","caller":"controller/controller.go:274","msg":"Reconciler error","controller":"kkp-app-installation-controller","object":{"name":"cilium","namespace":"kube-system"},"namespace":"kube-system","name":"cilium","reconcileID":"4025b08d-fe2f-461f-aa7f-0aa8c6d6d4a4","error":"handling installation of application installation: another operation (install/upgrade/rollback) is in progress"}
```

Helm shows that the release is in "pending-upgrade" state and has a very high release:

```
NAME              	NAMESPACE  	REVISION	UPDATED                                	STATUS         	CHART               	APP VERSION
kube-system-cilium	kube-system	23523   	2023-09-19 21:08:45.002273733 +0000 UTC	pending-upgrade	cilium-1.13.3       	1.13.3
```

I'm not sure what creates this condition (it seems to happen to all clusters sooner or later), but my suspicion is that when the `user-cluster-controller-manager` gets terminated, it can make the helm release stuck in this state and won't try to pick it up again after restart. Since we are _constantly_ running release upgrades (see #12095), the chance of hitting one of those upgrades is quite high.

### Expected behavior

KKP does not stop reconciling the CNI system application.

### How to reproduce the issue?

Unclear, probably install latest KKP, create a user cluster with Cilium as CNI and run it through a couple of Kubernetes upgrades for both the underlying seed cluster and the user cluster.

### How is your environment configured?

- KKP version: v2.23.8
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

#### Workaround

To unblock, it is possible to delete the Helm release secrets from the `kube-system` namespace. The `user-cluster-controller-manager` will then re-deploy after some time.

To find the release secrets, run and then delete them:

```sh
$ kubectl get secrets | grep sh.helm.release.v1.kube-system-cilium
```

### PR DESCRIPTION
**Pull request by SimonTheLeg**
**What this PR does / why we need it**:

This PR fixes an issue caused by a helm inconsistency (for more details see below) in which a helm release can be stuck in a "pending-install" state  and never be fully rolled out. This has been observed in multiple clusters now, but being an inconsistency, there is no reliable way to reproduce this consistently.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12846

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

During the research we came to the following conclusion:
This is not directly related to an AppInstallController being destroyed while a helm release is still in progress. In all testing the AppController would delete the "broken" release and re-created it. Instead this seems to be related to a fluke in helm, which many people have encountered (see https://github.com/helm/helm/issues/7476 for more details).

The current approach is to check for a variety of conditions that we have observed at customer clusters and do a `helm rollback` to the previous version if a release appears to be stuck. This comes with the drawback, that after the rollback has been completed we will start a new release with the current version. 
However out of all the following alternatives, I think this is the best option. Alternatives considered were:
* always use the `atomic` flag -> scrapped because then end-users would loose the ability to debug applications where there is a legitimate issue in an helm chart after it has reached the timeout
* delete the complete helm secret, thus forcing a re-rollout of the app -> with this the complete helm history would be lost, so we decided against this option.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Addressing inconsistencies in helm that lead to an Application stuck in "pending-install"
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go [hunk 1]
```diff
@@ -242,6 +242,20 @@ func (r *reconciler) handleInstallation(ctx context.Context, log *zap.SugaredLog
...
 	}
 
+	// Because some upstream tools are not completely idempotent, we need a check to make sure a release is not stuck.
+	// This should be run before we make any changes to the status field, so we can use it in our analysis
+	stuck, err := r.appInstaller.IsReleaseStuck(ctx, log, r.seedClient, r.userClient, appInstallation)
+	if err != nil {
+		return fmt.Errorf("failed to check if the previous release is stuck: %w", err)
+	}
+	if stuck {
+		log.Infof("Release %q seems to be stuck in pending even after timeout, attempting rollback now")
```
Comment (embik) [inline pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go]: What timeout is being referred to here? I don't see any in `IsReleaseStuck`.

File: pkg/applications/providers/types.go [hunk 2]
```diff
@@ -59,6 +59,12 @@ type TemplateProvider interface {
 
 	// Uninstall the application.
 	Uninstall(applicationInstallation *appskubermaticv1.ApplicationInstallation) (util.StatusUpdater, error)
+
+	// Check if a Release is stuck
+	IsReleaseStuck(applicationInstallation *appskubermaticv1.ApplicationInstallation) (bool, error)
```
Comment (embik) [inline pkg/applications/providers/types.go]: Nit: Should this be called `IsReleaseStuck` or maybe just `IsStuck`? Given that we potential can add providers that aren't Helm, the "Release" part of this doesn't make much sense. It's a very Helm-specific term.

File: pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go (hunk 1 above)
Comment (SimonTheLeg) [reply pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go]: good spot. In the current implementation it is implicitly adherring to the timeout. Basically the conditions we check for can only occur if the release is beyond the timeout. But it is a good point, and I will re-word this slightly.
Because if we find out down the road, that we should check explicitly for the timeout then that makes sense to reflect it.

File: pkg/applications/providers/types.go (hunk 2 above)
Comment (SimonTheLeg) [reply pkg/applications/providers/types.go]: good point, have renamed it

**Review by embik — APPROVED** [review]
/approve

File: pkg/applications/providers/template/helm.go [hunk 3]
```diff
@@ -208,3 +208,76 @@ func getDeployOpts(appDefinition *appskubermaticv1.ApplicationDefinition, appIns
...
+// IsStuck aims to identify if a helm release is stuck. This targets an upstream issue in helm, which has not been resolved. For further details see:
+// - https://github.com/helm/helm/issues/7476
+// - https://github.com/helm/helm/issues/4558
+func (h HelmTemplate) IsStuck(applicationInstallation *appskubermaticv1.ApplicationInstallation) (bool, error) {
+	// if the release was successful, exit early
+	if applicationInstallation.Status.Conditions[appskubermaticv1.Ready].Status == "True" {
+		return false, nil
+	}
+	// currently we observe the stuck error exclusively with this message. If it does not exist, exit early
+	if applicationInstallation.Status.Conditions[appskubermaticv1.Ready].Message != "another operation (install/upgrade/rollback) is in progress" {
```
Comment (wurbanski) [inline pkg/applications/providers/template/helm.go:221]: I love helm
/s

**Review by wurbanski — APPROVED** [review]
/lgtm
/approve
