### PR TITLE
propagate upstream defaultValuesBlock changes on upgrade

### LINKED ISSUE #15619: System ApplicationDefinition defaultValuesBlock not reconciled after KKP upgrade
### What happened?

When KKP is upgraded with changes to a system ApplicationDefinition's defaultValuesBlock, the updated values are not reconciled to existing clusters. The root cause is in **application_catalog.go** where the reconciler preserves the cluster's existing defaultValuesBlock if non-empty, ignoring any updates from the embedded YAML.

### Expected behavior

System ApplicationDefinition defaultValuesBlock changes should be reconciled to seed clusters after KKP upgrades, ensuring critical value updates are applied automatically.

### How to reproduce the issue?

1. Create a user cluster in an environment where the KKP seed cluster has been upgraded to include the fix from https://github.com/kubermatic/kubermatic/pull/15152
2. Install the Cluster Autoscaler application.
3. In the user cluster, check the ApplicationInstallation resource: Observe that the latest changes introduced in `https://github.com/kubermatic/kubermatic/pull/15152` are missing from defaultValuesBlock.
4. In the seed cluster, check the ApplicationDefinition resource. The updates from `https://github.com/kubermatic/kubermatic/pull/15152` are also missing from defaultValuesBlock.
5.  Result: `defaultValuesBlock` still contains the old values that were present in the cluster prior to the upgrade.
### How is your environment configured?

- KKP version: 2.30
- Shared or separate master/seed clusters?: Shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### Additional information

Internal reference: 8897

### PR DESCRIPTION
**Pull request by buraksekili**
**What this PR does / why we need it**:

The system ApplicationDefinition reconciler unconditionally preserved the cluster's existing `defaultValuesBlock` when non-empty, so upstream changes shipped in KKP upgrades never propagated to existing clusters. This PR adds SHA1 hash-based change detection via the `apps.kubermatic.k8c.io/default-values-hash` annotation to distinguish admin customizations from stale values, allowing upstream updates to propagate unless an admin has explicitly modified the field.

**Which issue(s) this PR fixes**:
Fixes #15619

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
System ApplicationDefinitions now receive upstream `defaultValuesBlock` changes during KKP upgrades. Admin customizations are preserved via hash-based detection.
```

**Documentation**:
```documentation
NONE
```
 
```test-issue
Prerequisites: KKP with seed and user cluster access.

Setup
1. Create KKP 2.29.1
2. Check the cluster-autoscaler ApplicationDefinition values. There will be no `patch` RBAC since the PR mentioned in the linked issue has not been shipped yet.
3. Upgrade KKP to replicate the issue (to v2.29.5, which should include the cluster-autoscaler fix on its defaultValuesBlock). See that cluster-autoscaler ApplicationDefinition does not contain the fix after upgrading.

Given: KKP upgraded with this fix
4. Deploy KKP with this fix and wait for reconciliation.
5. Verify defaultValuesBlock is updated to the file-embedded default.
6. Verify the hash annotation exists on the ApplicationDefinition
7. If KKP ships changes to values.yaml and customer did not modify it,
   the ApplicationInstallation in the user cluster should reflect the new defaults.

# example runs
#
# ###########################################
# after upgrading 2.29.1 to 2.29.3, which includes the fix
# ###########################################
$ k get kubermaticconfigurations -n kubermatic kubermatic -o yaml | yq .status.kubermaticVersion && echo "<->" && k get appdef cluster-autoscaler -o yaml | grep -i patch || echo "fix is not applied"
v2.29.3
<->
fix is not applied

# ###########################################
# after upgrading 2.29.1 to the custom image that includes this PR
# ###########################################
$ k get kubermaticconfigurations -n kubermatic kubermatic -o yaml | yq .status.kubermaticVersion && echo "<->" && k get appdef cluster-autoscaler -o yaml | grep -i patch || echo "fix is not applied"
v2.30.0-alpha.1-78-ge4db298e4
<->
        - patch
```

### CODE REVIEW

File: pkg/applicationdefinitions/application_catalog.go [hunk 1]
```diff
@@ -127,16 +129,32 @@ func systemApplicationDefinitionReconcilerFactory(
...
+			// last apply. If so, preserve their override. Otherwise, use the
+			// file-embedded value so upstream changes propagate on upgrade.
+			fileHash := sha1Hex(fileAppDef.Spec.DefaultValuesBlock)
+			storedHash := clusterAppDef.Annotations[appskubermaticv1.ApplicationDefaultValuesHashAnnotation]
+			clusterHash := sha1Hex(clusterAppDef.Spec.DefaultValuesBlock)
+
+			if clusterAppDef.Spec.DefaultValuesBlock != "" &&
+				clusterAppDef.Spec.DefaultValuesBlock != "{}" &&
+				storedHash != "" &&
+				storedHash != clusterHash {
```
Comment (rajaSahil) [inline pkg/applicationdefinitions/application_catalog.go]: If both the clusterAppDef (modified by the cluster admin) and the fileAppDef (updated by Kubermatic) have changed since the last apply, the current logic always keeps the admin’s version and quietly discards the upstream update from fileAppDef.

The same issue shows up here as well, if a cluster admin adds additional resources to the autoscaler values, and later upstream introduces new resources (e.g., for RBAC), those upstream additions will never be applied because the admin’s version continues to take precedence.

File: pkg/applicationdefinitions/application_catalog.go [hunk 2]
```diff
@@ -127,16 +129,32 @@ func systemApplicationDefinitionReconcilerFactory(
...
 
 			clusterAppDef.Name = fileAppDef.Name
 			clusterAppDef.Spec = fileAppDef.Spec
+
+			// record what file hash we applied so future reconciles can detect admin changes
+			annotations := clusterAppDef.GetAnnotations()
+			if annotations == nil {
+				annotations = make(map[string]string)
+			}
+			annotations[appskubermaticv1.ApplicationDefaultValuesHashAnnotation] = fileHash
```
Comment (rajaSahil) [inline pkg/applicationdefinitions/application_catalog.go]: Don't we need to update fileHash, if we override DefaultValuesBlock in line number 144? Otherwise it would create a infinite loop?

**Review by rajaSahil — CHANGES_REQUESTED** [review]

File: pkg/applicationdefinitions/application_catalog.go (hunk 1 above)
Comment (buraksekili) [reply pkg/applicationdefinitions/application_catalog.go]: You are right that when both the admin and upstream modify defaultValuesBlock, the admin version takes precedence, and upstream additions are not merged in. This is the actually intended behavior that i envisioned. If the `defaultValuesBlock` contains changes, it should take precedence over the ones stored in the file, in my opinion. What do you think?
The approach I took is a pragmatic trade-off: upstream changes propagate to clusters where the admin has not customized the field. When an admin has customized it, they can clear the field to re-enable upstream propagation if they want the latest defaults.

Comment (rajaSahil) [reply pkg/applicationdefinitions/application_catalog.go]: > This is the actually intended behavior that i envisioned. If the `defaultValuesBlock` contains changes, it should take precedence over the ones stored in the file, in my opinion. What do you think? 

The core issue is that `defaultValuesBlock` is doing two jobs at once i.e holding **admin customizable** defaults and carrying **system critical** resources like RBAC. Because both are bundled together, the reconciler has no way to distinguish between admin introduced changes and upstream required updates.

IMO, we should separate these concerns. KKP-required resources should be generated in code and injected into a dedicated field (`SystemValuesBlock`). With this approach:
- `defaultValuesBlock` becomes purely admin editable, admin changes always take precedence, with no conflicts to resolve.
- KKP critical resources are consistently enforced via `SystemValuesBlock`
- The reconciler no longer needs to detect or reconcile simultaneous upstream vs. admin changes within the same field.

WDYT?

Comment (buraksekili) [reply pkg/applicationdefinitions/application_catalog.go]: If we introduce SystemValuesBlock, we'll need to handle 3-way merge strategies, which would complicate the user experience, in my opinion.
At the moment, the field itself is just a string, not a structured value. The field is a plain string, so we would need to decide precedence for overlapping keys at runtime, etc.
That said, most system-critical values (security contexts, registry overrides) are already enforced in Go code by the CNI and autoscaler controllers via mergo.WithOverride, independent of defaultValuesBlock. The one exception is RBAC resources in cluster-autoscaler's extraObjects, which still live in the YAML. We can move cluster-autosclar RBAC rules into Go code, to ensure that its being enforced all the time, while other configuration can go into a YAML file. If that sounds ok to you, we can handle this in a dedicated PR to keep the scope of this PR limited and clear

Comment (rajaSahil) [reply pkg/applicationdefinitions/application_catalog.go]: >  We can move cluster-autosclar RBAC rules into Go code, to ensure that its being enforced all the time, while other configuration can go into a YAML file. If that sounds ok to you, we can handle this in a dedicated PR to keep the scope of this PR limited and clear

Yes, this would work too.

File: pkg/applicationdefinitions/application_catalog.go (hunk 2 above)
Comment (buraksekili) [reply pkg/applicationdefinitions/application_catalog.go]: why do you think it will create an endpless loop? could you please elaborate on this? Maybe i miss something

Comment (rajaSahil) [reply pkg/applicationdefinitions/application_catalog.go]: Are you not updating the `fileAppDef.Spec.DefaultValuesBlock = clusterAppDef.Spec.DefaultValuesBlock` after calculating hash?

Comment (buraksekili) [reply pkg/applicationdefinitions/application_catalog.go]: Let me walk you through a sample scenario and get your thoughts.

Before this fix, there was no hash. Adding the annotation triggers a reconciliation; however, in the subsequent reconciliation, the hash annotation remains unchanged, preventing further reconciliation loops.

File: sdk/apis/apps.kubermatic/v1/types.go [hunk 3]
```diff
@@ -48,4 +48,13 @@ const (
 	// for ApplicationInstallations created from this ApplicationDefinition.
 	// The value should be a valid Go duration string (e.g., "5m", "1h", "30s").
 	ApplicationReconciliationIntervalAnnotation = "apps.kubermatic.k8c.io/reconciliation-interval"
+
+	// ApplicationDefaultValuesHashAnnotation stores the SHA1 hash of the file-embedded
+	// defaultValuesBlock. Used to detect admin modifications to system ApplicationDefinitions.
+	ApplicationDefaultValuesHashAnnotation = "apps.kubermatic.k8c.io/default-values-hash"
```
Comment (rajaSahil) [inline sdk/apis/apps.kubermatic/v1/types.go]: Should we rename this to `apps.kubermatic.k8c.io/file-default-values-hash`? WDYT?

File: pkg/applicationdefinitions/application_catalog.go (hunk 1 above)
Comment (mgoltzsche) [reply pkg/applicationdefinitions/application_catalog.go]: > If we introduce SystemValuesBlock, we'll need to handle 3-way merge strategies, which would complicate the user experience, in my opinion.
At the moment, the field itself is just a string, not a structured value. The field is a plain string, so we would need to decide precedence for overlapping keys at runtime, etc.

Helm already supports providing multiple values and merging them together. Therefore Helm users should be familiar with that approach. Even though it is a string field, Helm requires it to be a well formed YAML object. Correspondingly Helm also already defines how to deal with overlapping keys (in case of object properties holding a scalar value, the last one wins; in case of an array, the entire array is replaced).
Similarly, such a values merge approach has been implemented for the kubermatic installer recently, see #15235.

File: sdk/apis/apps.kubermatic/v1/types.go (hunk 3 above)
Comment (buraksekili) [reply sdk/apis/apps.kubermatic/v1/types.go]: Updated in 21326a6d7c3debf0f4ff28b04d782277340fb58a. PTAL
