### PR TITLE
Fix reconcilition error for apiserver-external service for non ClusterIP service type.

### LINKED ISSUE #13584: Configuring LoadBalancer type for API Server
### What happened?

We added the support to configure **type** for the `apiserver-external` service of user clusters through https://github.com/kubermatic/kubermatic/pull/13562. The functionality is working as expected, although there are errors in the UI, specifically in the cluster status. This seems like a transient error with the cache but also could be a genuine issue somewhere.

```
  errorMessage: 'failed to ensure Service cluster-hthltqtwgb/apiserver-external: failed
    waiting for the cache to contain our latest changes: context deadline exceeded'
  errorReason: ReconcileError
```

### How to reproduce the issue?

Configure a datacenter as the following:

```yaml
gcp-westeurope:
  country: DE
  location: Europe West (Germany)
  spec:
    apiServerServiceType: LoadBalancer
```

Create a new cluster, check it's status from CLI and UI.

### How is your environment configured?

- KKP version: development
- Shared or separate master/seed clusters?: shared/doesn't matter

/milestone KKP 2.26

### PR DESCRIPTION
**Pull request by akash-gautam**
**What this PR does / why we need it**:
When we set `apiServerServiceType: LoadBalancer` the `apiserver-external` service is of type `LoadBalancer` as expected, setting the nodeport for it to zero is not possible which causes continuous reconcile error for the service, this used to work earlier as the service type was always `ClusterIP` on using expose strategy as Tunneling, but now we have the option to specify other types as well.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/13584

**What type of PR is this?**
/kind bug
/kind regression

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```
**Documentation**:
```documentation
NONE
```

### CODE REVIEW

File: pkg/resources/apiserver/service.go [hunk 1]
```diff
@@ -87,7 +87,10 @@ func ServiceReconciler(exposeStrategy kubermaticv1.ExposeStrategy, externalURL s
 			se.Spec.Ports[0].Port = 443
 			if exposeStrategy == kubermaticv1.ExposeStrategyTunneling {
 				se.Spec.Ports[0].TargetPort = intstr.FromInt(resources.APIServerSecurePort)
-				se.Spec.Ports[0].NodePort = 0 // allows switching from other expose strategies
+				// skip setting nodeport as zero if the service type is LoadBalancer
+				if se.Spec.Type != *apiServerServiceType {
+					se.Spec.Ports[0].NodePort = 0 // allows switching from other expose strategies
+				}
```
Comment (xrstf) [inline pkg/resources/apiserver/service.go]: `apiServerServiceType` can be nil. Also in line 67 we set the Service's, so this comparison can never be true.

File: pkg/resources/apiserver/service.go [hunk 2]
```diff
@@ -87,7 +87,10 @@ func ServiceReconciler(exposeStrategy kubermaticv1.ExposeStrategy, externalURL s
 			se.Spec.Ports[0].Port = 443
 			if exposeStrategy == kubermaticv1.ExposeStrategyTunneling {
 				se.Spec.Ports[0].TargetPort = intstr.FromInt(resources.APIServerSecurePort)
-				se.Spec.Ports[0].NodePort = 0 // allows switching from other expose strategies
+				// skip setting nodeport as zero if the service type is LoadBalancer
+				if se.Spec.Type != corev1.ServiceTypeLoadBalancer {
```
Comment (xrstf) [inline pkg/resources/apiserver/service.go]: I think this is the opposite of the desired comparison.

File: pkg/resources/apiserver/service.go [hunk 3]
```diff
@@ -87,7 +87,10 @@ func ServiceReconciler(exposeStrategy kubermaticv1.ExposeStrategy, externalURL s
 			se.Spec.Ports[0].Port = 443
 			if exposeStrategy == kubermaticv1.ExposeStrategyTunneling {
 				se.Spec.Ports[0].TargetPort = intstr.FromInt(resources.APIServerSecurePort)
-				se.Spec.Ports[0].NodePort = 0 // allows switching from other expose strategies
+				// set nodeport as zero only if the service type is ClusterIP.
```
Comment (xrstf) [inline pkg/resources/apiserver/service.go]: And now we can see that the comment is not really adding anything at all and can be removed alltogether :) And I promise it's my last nitpick 😁

**Review by xrstf — APPROVED** [review]
/approve
