### PR TITLE
fix: check for cilium system application in default application controller

### LINKED ISSUE #12820: App installation at cluster setup can block CNI deployment
### What happened?

When creating a user cluster through the dashboard, step 5 can be used to configure Applications that will be deployed upon cluster creation. An obvious candidate are the apps from the default app catalog (EE feature).

Unfortunately, this feature is problematic. App installation waits for the Helm chart to succeed deployment, which means it waits for Pods to start up. But Pods will never start up when no CNI is deployed, because nodes are not fully initialised.

If Cilium 1.13+ is used as CNI, it is also deployed via an "System" Application. But since System Applications  do not seem to have priority over normal Applications, you can run into the situation that user-cluster-controller-manager is stuck trying to deploy a "random" Application (e.g. cert-manager), and never gets to deploy Cilium. The cluster is then stuck as CNI never starts, so regular Pods can never start.

Screenshot 2023-11-07 at 08 34 57

The `cert-manager` ApplicationInstallation has the following status:

```yaml
  status:
    applicationVersion:
      template:
        source:
          helm:
            chartName: cert-manager
            chartVersion: v1.12.3
            url: https://charts.jetstack.io
      version: v1.12.3
    conditions:
      ManifestsRetrieved:
        lastHeartbeatTime: "2023-11-07T07:31:24Z"
        message: application's source successfully downloaded
        observedGeneration: 1
        reason: DownloadSourceSuccessful
        status: "True"
      Ready:
        lastHeartbeatTime: "2023-11-07T07:31:24Z"
        message: application is installing or upgrading
        observedGeneration: 1
        reason: InstallationInProgress
        status: Unknown
    method: helm
```

### Expected behavior

Cilium CNI "System Application" is installed with priority over normal Applications.

### How to reproduce the issue?

1. Create user cluster, during the wizard select "cert-manager" as Application to deploy.
2. Observe "cert-manager" Application stuck in deployment and "Cilium" Application never actually deploy.

### How is your environment configured?

- KKP version: `main`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
Recently we have added default applications and we have found out that this [issue](https://github.com/kubermatic/kubermatic/issues/12820) has emerged once again,[check comment](https://github.com/kubermatic/kubermatic/issues/12820#issuecomment-2481423649)

**Which issue(s) this PR fixes**:

Fixes #12820

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixing the issue with blocked cluster provisioning, when selecting default applications that conflicted with Cilium system application and user-cluster-controller-manager was stuck.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go [hunk 1]
```diff
@@ -149,7 +149,7 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *kubermaticv1.Cluste
 	}
 
 	if cluster.Spec.CNIPlugin != nil && cni.IsManagedByAppInfra(cluster.Spec.CNIPlugin.Type, cluster.Spec.CNIPlugin.Version) {
-		ciliumApp, err := getCNIApplicationInstallation(ctx, userClusterClient, cluster.Spec.CNIPlugin.Type)
+		ciliumApp, err := util.GetCNIApplicationInstallation(ctx, userClusterClient, cluster.Spec.CNIPlugin.Type)
```
Comment (SimonTheLeg) [inline pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go]: nit: atm we only have cilium, but I think we should call this cniApp, as in the func could return something different in the future.

File: pkg/controller/seed-controller-manager/default-application-controller/controller.go [hunk 2]
```diff
@@ -156,6 +159,24 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *kubermaticv1.Cluste
...
+	if cluster.Spec.CNIPlugin != nil && cni.IsManagedByAppInfra(cluster.Spec.CNIPlugin.Type, cluster.Spec.CNIPlugin.Version) {
+		ciliumApp, err := util.GetCNIApplicationInstallation(ctx, userClusterClient, cluster.Spec.CNIPlugin.Type)
+		if err != nil {
+			r.log.Debug("Requeue as it could not get Cilium system ApplicationInstallation")
+			return &reconcile.Result{RequeueAfter: 10 * time.Second}, nil
+		}
+		// check if application is deployed and status is updated with app version.
+		if ciliumApp != nil && ciliumApp.Status.ApplicationVersion == nil {
+			r.log.Debug("Requeue as Cilium system application is not ready yet")
+			return &reconcile.Result{RequeueAfter: 10 * time.Second}, nil
```
Comment (SimonTheLeg) [inline pkg/controller/seed-controller-manager/default-application-controller/controller.go]: Even if we use the same code somewhere else already, I think we should add a test for this as well in here. We do the same in the initial app-controller logic.
https://github.com/kubermatic/kubermatic/blob/0033300c919b3b35da913a23eabb6b394cf49e8e/pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go#L165

**Review by SimonTheLeg — CHANGES_REQUESTED** [review]
I have left some comments. 

In general, I am wondering if we should extract the `if cluster.Spec.CNIPlugin != nil && ...` logic into its own separate function since we are re-using it in the inital-application controller as well

**Comment by cnvergence** [comment]
Thanks @SimonTheLeg, we should do this definitely

**Review by embik — APPROVED** [review]
/approve
