### PR TITLE
Mirror etcd-launcher and gatekeeper images in kubermatic-installer

### LINKED ISSUE #12129: Missing mirror images for etcd-launcher, gatekeeper, metering
### What happened?

Reported externally that some KKP images are not mirrored.
> in KKP v2.22.1 etcd-launcher is not mirrored with mirror-images. Please fix. 
> Also not mirrored: 
> metering
> velero-plugin-for-aws
> gatekeeper

The `velero-plugin-for-aws` gets mirrored depending on chart configuration but the other three do not.

### Expected behavior

All KKP essential images are mirrored

### How to reproduce the issue?

```
# get https://github.com/kubermatic/kubermatic/releases/tag/v2.22.1
$ kubermatic-installer -- mirror-images wozniakjan --dry-run --config ./kubermatic.yaml
```

### How is your environment configured?

affects v2.22.1 and prior

### Provide your KKP manifest here (if applicable)

bug is KKP config invariant

### What cloud provider are you running on?

bug is cloud provider invariant

### What operating system are you running in your user cluster?

bug is OS invariant

### PR DESCRIPTION
**Pull request by wozniakjan**
**What this PR does / why we need it**:
`kubermatic-installer` misses some images in `mirror-images` subcommand. This adds `etcd-launcher` and `gatekeeper`.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12129

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
bugfix: include etcd-launcher and gatekeeper images in kubermatic-installer mirror-images
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/install/images/images.go [hunk 1]
```diff
@@ -540,6 +542,10 @@ func getTemplateData(config *kubermaticv1.KubermaticConfiguration, clusterVersio
 	fakeCluster.Spec.ClusterNetwork.DNSDomain = "cluster.local"
 	fakeCluster.Spec.ClusterNetwork.KonnectivityEnabled = pointer.Bool(konnectivityEnabled)
 	fakeCluster.Spec.CNIPlugin = cniPlugin
+	fakeCluster.Spec.Features = map[string]bool{kubermaticv1.ClusterFeatureEtcdLauncher: true}
+	if etcdLauncher, exists := config.Spec.FeatureGates[kubermaticv1.ClusterFeatureEtcdLauncher]; etcdLauncher == false && exists == true {
+		fakeCluster.Spec.Features[kubermaticv1.ClusterFeatureEtcdLauncher] = false
```
Comment (wozniakjan) [inline pkg/install/images/images.go:547]: per https://docs.kubermatic.com/kubermatic/v2.22/cheat-sheets/etcd/etcd-launcher/
etcd-launcher is enabled by default but explicitly stating to disable it is possible through config feature gates, so I guess it's desired to keep `kubermatic-installer` consistent with that behaviour.

File: pkg/install/images/images.go [hunk 2]
```diff
@@ -540,6 +542,10 @@ func getTemplateData(config *kubermaticv1.KubermaticConfiguration, clusterVersio
 	fakeCluster.Spec.ClusterNetwork.DNSDomain = "cluster.local"
 	fakeCluster.Spec.ClusterNetwork.KonnectivityEnabled = pointer.Bool(konnectivityEnabled)
 	fakeCluster.Spec.CNIPlugin = cniPlugin
+	fakeCluster.Spec.Features = map[string]bool{kubermaticv1.ClusterFeatureEtcdLauncher: true}
+	if enabled, exists := config.Spec.FeatureGates[kubermaticv1.ClusterFeatureEtcdLauncher]; exists && !enabled {
+		fakeCluster.Spec.Features[kubermaticv1.ClusterFeatureEtcdLauncher] = false
```
Comment (wozniakjan) [inline pkg/install/images/images.go:547]: per https://docs.kubermatic.com/kubermatic/v2.22/cheat-sheets/etcd/etcd-launcher/
etcd-launcher is enabled by default but explicitly stating to disable it is possible through config feature gates, so I guess it's desired to keep kubermatic-installer consistent with that behaviour.

**Review by embik — APPROVED** [review]
/approve
