### PR TITLE
reconcile Gateway API resources before Deployments

### LINKED ISSUE #15711: kubermatic-installer behavior differs between NGINX Ingress and Gateway API
### What happened?

When installing (not upgrading) KKP on a cluster with the kubermatic-installer and Gateway API enabled, the Gateway is never created and the kubermatic-installer times out waiting for the Gateway. The `KubermaticConfiguration` and the Helm values were retrieved from a running KKP installation, and adjusted according to the [Gateway API migration guide](https://docs.kubermatic.com/kubermatic/v2.30/tutorials-howtos/networking/gateway-api-migration/#migration-steps). The kubermatic-installer is then invoked as follows but fails waiting for the Gateway:

```
$ kubermatic-installer --verbose deploy --config kubermatic.yaml --helm-values values.yaml  --migrate-gateway-api
...
INFO[0115]    Waiting Gateway to be ready...            
DEBU[0115]    failed to get Gateway, err: Gateway.gateway.networking.k8s.io "kubermatic" not found  gateway=kubermatic/kubermatic
```

The installation with the same `KubermaticConfiguration` and Helm values file, but with NGINX Ingress Controller instead of Gateway API is successful.

### Expected behavior

The kubermatic-installer should behave the same and should be able to install KKP on a fresh cluster with Gateway API enabled.

### How to reproduce the issue?

Create a kind cluster, and run the kubermatic-installer with the provided files:

```
kind create cluster
kubermatic-installer --verbose deploy --config kubermatic.yaml --helm-values values.yaml  --migrate-gateway-api
```

### How is your environment configured?

- KKP version: v2.30.0
- Shared or separate master/seed clusters?: /

### Provide your KKP manifest here (if applicable)

<details>
<summary>kubermatic.yaml</summary>

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: KubermaticConfiguration
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  ingress:
    domain: kkp.example.com
    certificateIssuer: null
  auth:
    clientID: kubermatic
    issuerClientID: kubermaticIssuer
    issuerClientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    issuerCookieKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    serviceAccountKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    skipTokenIssuerTLSVerify: true
    tokenIssuer: https://kkp.example.com/dex
  ui:
    extraVolumeMounts:
      - name: themes
        mountPath: /dist/light.css
        subPath: light
    extraVolumes:
      - name: themes
        configMap:
          name: kubermatic-dashboard-themes
```
</details>

<details>
<summary>values.yaml</summary>

```yaml
migrateGatewayAPI: true
httpRoute:
  gatewayName: kubermatic
  gatewayNamespace: kubermatic
  domain: "kkp.example.com"
  timeout: 3600s
kubermaticOperator:
  debug: true
dex:
  ingress:
    enabled: false
  config:
    issuer: "https://kkp.example.com/dex"
    expiry:
      signingKeys: "6h"
      idTokens: "24h"
    oauth2:
      skipApprovalScreen: true
      responseTypes:
        - code
        - token
        - id_token
    storage:
      type: kubernetes
      config:
        inCluster: true
    enablePasswordDB: true
    staticPasswords:
      - email: kubermatic@example.com
        hash: "$2a$10$zMJhg/3axbm/m0KmoVxJiO1eO5gtNrgKDysy5GafQFrXY93OE9LsK"
        username: admin
        userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
    staticClients:
      - id: kubermatic
        name: Kubermatic
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        RedirectURIs:
          - https://kkp.example.com
          - https://kkp.example.com/projects
      - id: kubermaticIssuer
        name: Kubermatic OIDC Issuer
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        RedirectURIs:
          - https://kkp.example.com/api/v1/kubeconfig
          - https://kkp.example.com/api/v2/kubeconfig/secret
          - https://kkp.example.com/api/v2/dashboard/login
telemetry:
  uuid: "f84c6dff-ef2c-45f1-98d6-8975daea6179"
```
</details>

### What cloud provider are you running on?

Not provider specific

### What operating system are you running in your user cluster?

Not OS specific

### Additional information

The actual root cause for this behavior is the following part of the `KubermaticConfiguration`:
```yaml
spec:
  ui:
    extraVolumeMounts:
      - name: themes
        mountPath: /dist/light.css
        subPath: light
    extraVolumes:
      - name: themes
        configMap:
          name: kubermatic-dashboard-themes
```

At installation time, the referenced `ConfigMap` does not exist, and this causes the following behavior:
* kubermatic-installer [is waiting for the Gateway](https://github.com/kubermatic/kubermatic/blob/v2.30.0/pkg/install/stack/kubermatic-master/stack.go#L359) to show the DNS settings
* kubermatic-operator [is failing to reconcile](https://github.com/kubermatic/kubermatic/blob/v2.30.0/pkg/controller/operator/master/reconciler.go#L151) the kubermatic-dashboard deployment
* (as a consequence) kubermatic-operator [never creates the `Gateway`](https://github.com/kubermatic/kubermatic/blob/v2.30.0/pkg/controller/operator/master/reconciler.go#L167)
* (as a consequence) kubermatic-installer times out and fails

However, if you run the kubermatic-installer and rely on the NGINX Ingress Controller Helm chart, the installation would succeed.

### PR DESCRIPTION
**Pull request by buraksekili**
**What this PR does / why we need it**:
A missing ConfigMap referenced by `spec.ui.extraVolumes` caused the `RelatedRevisionsLabels` modifier in `reconcileDeployments()` to fail. Because `reconcile()` uses fail-fast error handling, `reconcileGatewayAPIResources()` was never reached and the Gateway was never created. This blocked `kubermatic-installer` from completing.

The fix moves `reconcileGatewayAPIResources()` before `reconcileDeployments()` so Gateway and HTTPRoute are created regardless of Deployment health.

**Which issue(s) this PR fixes**:
Fixes #15711

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
kubermatic-operator now reconciles Gateway API resources before Deployments, preventing missing ConfigMaps from blocking Gateway creation.
```

**Documentation**:
```documentation
NONE
```

**Test issue**:
```test-issue
Prerequisites: A kind cluster with KKP installed via hack/ci/run-gateway-api-e2e-tests.sh

Setup
1. Deploy KKP with Gateway API enabled using the existing CI script.

Reproduce (without this fix)
2. Patch KubermaticConfiguration to add extraVolumes referencing a non-existent ConfigMap:

  kubectl patch kubermaticconfiguration -n kubermatic e2e --type merge -p '
  spec:
    ui:
      extraVolumes:
        - name: themes
          configMap:
            name: kubermatic-dashboard-themes
      extraVolumeMounts:
        - name: themes
          mountPath: /dist/light.css
          subPath: light
  '
3. Observe that the installer hangs/times out because the Gateway is never created.

Given: this fix applied
4. Delete the kubermatic-operator helm chart, HTTPRoute and Gateway,
5. Re-run kubermatic-installer to verify it passes
```

### CODE REVIEW

**Comment by buraksekili** [comment]
/hold raised this PR to create the failure scenario in the pipeline, to ensure that this issue can be caught later in the pipeline.

The fix will be added subsequently

**Comment by buraksekili** [comment]
/hold cancel

Reproduced the issue [here](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/15712/pre-kubermatic-gateway-api-e2e/2042322539102867456#1:build-log.txt%3A1252)

File: pkg/test/e2e/gateway-api/fresh_install_test.go [hunk 1]
```diff
@@ -56,3 +56,22 @@ func TestGatewayAPIFreshInstall(t *testing.T) {
 		t.Fatalf("Gateway HTTP connectivity verification failed: %v", err)
 	}
 }
+
+func TestGatewayAPIDeploymentFailureTolerance(t *testing.T) {
+	ctx := context.Background()
```
Comment (kron4eg) [inline pkg/test/e2e/gateway-api/fresh_install_test.go]:
```suggestion
	ctx := t.Context()
```

**Review by kron4eg — APPROVED** [review]
/approve
