### PR TITLE
KubeVirt fix ccmClusterName feature for migrated clusters

### LINKED ISSUE #11838: KubeVirt cluster is missing ccmClusterName feature
**This bug applies to: KKP 2.21**

KubeVirt clusters miss the feature (`cluster.spec.features.ccmClusterName = true`).

Then the `--cluster-name` parameter is not passed to the `kubevirt-cloud-controller-manager` controller.
The consequence is that the infra KubeVirt LB services are created with a wrong selector:
- `cluster.x-k8s.io/cluster-name: kubernetes`
with `kubernetes` as cluster-name instead of the correct one.

Adding of the kubevirt ccm flag is done here:
https://github.com/kubermatic/kubermatic/blob/main/pkg/resources/cloudcontroller/kubevirt.go#L134

Fix to be done (2.21) is to have this parameter set for KubeVirt.

**TBD:**
To be discussed if we always pass this parameter, or update the condition when `data.Cluster().Spec.Features[kubermaticv1.ClusterFeatureCCMClusterName]` is set to have it properly set for KubeVirt.

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
KubeVirt clusters upgraded to KKP 2.22 were missing `spec.features.ccmClusterName = true`.
This PR fixes this issue.

**Which issue(s) this PR fixes**:

Fixes #11838 

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixes missing ccmClusterName feature in KubeVirt clusters upgraded to KKP 2.22.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/webhook/cluster/mutation/mutator.go [hunk 1]
```diff
@@ -162,6 +162,15 @@ func (m *Mutator) mutateUpdate(oldCluster, newCluster *kubermaticv1.Cluster, con
 		}
 	}
 
+	// For KubeVirt, we want to mutate and always have ClusterFeatureCCMClusterName = true
+	// It's not handled by the previous loop for the migration 2.21 to 2.22
+	// as ExternalCloudProvider feature not is set for the first time.
+	if newCluster.Spec.Cloud.Kubevirt != nil {
+		if v, exists := newCluster.Spec.Features[kubermaticv1.ClusterFeatureCCMClusterName]; !exists || !v {
+			newCluster.Spec.Features[kubermaticv1.ClusterFeatureCCMClusterName] = true
+		}
```
Comment (xrstf) [inline pkg/webhook/cluster/mutation/mutator.go]: Isn't this `if` statement redundant?

Comment (hdurand0710) [reply pkg/webhook/cluster/mutation/mutator.go]: agreed! removed

**Review by xrstf — APPROVED** [review]
/approve
