### PR TITLE
Check Ingress instead of LB Service to detect DNS settings in installer

### LINKED ISSUE #12928: Determining DNS settings fails if non-default ingress controller is used
### What happened?

I've disabled deploying the `nginx-ingress-controller` Helm chart and will try to use the Cilium built-in ingress controller instead.

Now running `kubermatic-installer deploy` ends with this:
```
time="2023-12-21T13:22:48Z" level=info msg="   📡 Determining DNS settings…"
time="2023-12-21T13:22:48Z" level=debug msg="      Waiting for \"nginx-ingress-controller/nginx-ingress-controller\" to be ready…"
time="2023-12-21T13:22:48Z" level=warning msg="      Timed out waiting for the LoadBalancer service \"nginx-ingress-controller/nginx-ingress-controller\" to become ready."
time="2023-12-21T13:22:48Z" level=warning msg="      Please check the Service and, if necessary, reconfigure the"
time="2023-12-21T13:22:48Z" level=warning msg="      nginx-ingress-controller Helm chart. Re-run the installer to apply"
time="2023-12-21T13:22:48Z" level=warning msg="      updated configuration afterwards."
time="2023-12-21T13:22:48Z" level=info msg="🛬 Installation completed successfully. ✌"
```

### Expected behavior

It probably shouldn't rely on a component that is disabled. But more importantly, it should probably just fetch the IPs from the ingresses that it created - not sure why it's looking at the ingress controller's LoadBalancer service at all.

They literally provide the same info:
```
$ k -n kube-system get svc cilium-ingress -o json | jq .status.loadBalancer.ingress
[
  {
    "hostname": "86.119.36.151.nip.io"
  }
]

$ k -n kubermatic get ingress kubermatic -o json | jq .status.loadBalancer.ingress
[
  {
    "hostname": "86.119.36.151.nip.io"
  }
]
```

... but the latter should be more agnostic.

### How to reproduce the issue?

`kubermatic-installer deploy kubermatic-master --skip-charts="nginx-ingress-controller" [...]`

I think that's all it takes.

### How is your environment configured?

- KKP version: 2.24.1
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

I guess this could technically matter:
```
  ingress:
    domain: kkp.foo
    certificateIssuer:
      kind: ClusterIssuer
      name: letsencrypt-production
    className: cilium
```

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This helps making the installer less dependent on nginx. @judge-red put it best:

> It probably shouldn't rely on a component that is disabled. But more importantly, it should probably just fetch the IPs from the ingresses that it created - not sure why it's looking at the ingress controller's LoadBalancer service at all.

**Which issue(s) this PR fixes**:
Fixes #12928

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
The Kubermatic installer will now detect DNS settings based on the Ingress instead of the nginx-ingress LoadBalancer, allowing for other ingress solutions to be properly detected.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

File: pkg/install/stack/kubermatic-master/stack.go [hunk 1]
```diff
@@ -368,164 +367,35 @@ func showDNSSettings(ctx context.Context, logger *logrus.Entry, kubeClient ctrlr
...
+		ingresses = ingress.Status.LoadBalancer.Ingress
 
 		return len(ingresses) > 0, nil
 	})
 	if err != nil {
-		logger.Warnf("Timed out waiting for the LoadBalancer service %q to become ready.", svcName)
+		logger.Warn("Timed out waiting for the Ingress to become ready.")
 		logger.Warn("Please check the Service and, if necessary, reconfigure the")
 		logger.Warn("nginx-ingress-controller Helm chart. Re-run the installer to apply")
 		logger.Warn("updated configuration afterwards.")
```
Comment (embik) [inline pkg/install/stack/kubermatic-master/stack.go:392]: I think it would be neat to give the `Ingress` resource name here, so users can check out the resource for any problems easily.

In addition, the log warnings below don't seem to be correct anymore:

> Please check the Service

We no longer care about the service, should IMHO also be `Ingress`.

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/install/stack/kubermatic-master/stack.go (hunk 1 above)
Comment (xrstf) [reply pkg/install/stack/kubermatic-master/stack.go:392]: I know what you mean and I saw that when I made the PR. I decided to not change the wording because a) I'm lazy and b) the code above is still used when using our nginx. And if something is not working, I wanted to direct the user to check the "ingress tool you're using" (the "Service") and not look at the Ingress. I assumed the Ingress will not show any issues, will it?

But I have no super strong opinions either way.

Comment (embik) [reply pkg/install/stack/kubermatic-master/stack.go:392]: > I assumed the Ingress will not show any issues, will it?

If the Ingress fails to reconcile, I strongly assume that events/conditions will be on the ingress object. I see what you mean, but I think the message is no longer helpful this way and needs to explain what to look at in a better way.

Comment (xrstf) [reply pkg/install/stack/kubermatic-master/stack.go:392]: But when nginx is broken, it will not be the Ingress that is malfunctioning, but the LB. So I do not expect any "Failed to create loadBalancer: ARN bla bla SKU AWS bla bla" error message from the aws CCM on the Ingress. Why would the CCM "broadcast" this to all Ingresses in a cluster?

Comment (embik) [reply pkg/install/stack/kubermatic-master/stack.go:392]: Fair enough. Let me not block too much on this, although I think the language should be improved at some point.

**Review by embik — APPROVED** [review]
/approve
