### PR TITLE
Upgrade process fix for Seed MLA node-exporter chart

### LINKED ISSUE #14669: [Bug] Node Exporter upgrade fails when upgrading from KKP v2.27.5 to v2.28.0-rc.0
### What happened?
When trying to upgrade seed-mla using the `kubermatic-installer`, the upgrade fails with the following error:
```
$ ./kubermatic-installer deploy seed-mla --charts-directory charts/ --helm-values examples/values.yaml 
INFO[0000] 🚀 Initializing installer…                     edition="Community Edition" version=v2.28.0-rc.0
INFO[0000] 🚦 Validating the provided configuration…     
INFO[0000] ✅ Provided configuration is valid.           
INFO[0000] 🚦 Validating existing installation…          
INFO[0000] ✅ Existing installation is valid.            
INFO[0000] 🛫 Deploying KKP Seed MLA Stack…              
INFO[0000]    📦 Deploying Node Exporter ...             
INFO[0000]       Updating release from 2.27.5 to 2.28.0-rc.0… 
ERRO[0012] ❌ Operation failed: failed to deploy Node Exporter: failed to deploy Helm release: failed to install: Error: UPGRADE FAILED: release node-exporter failed, and has been rolled back due to atomic being set: cannot patch "node-exporter" with kind DaemonSet: DaemonSet.apps "node-exporter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"node-exporter", "app.kubernetes.io/name":"node-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable. 
```

### How to reproduce the issue?

- Install KKP v2.27.5 with seed-mla with minimal configuration.
- Upgrade to v2.28.0-rc.0
- deploy seed-mla

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

kind

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
This PR contains the upgrade issue for `node-exporter` upstream chart introduced with https://github.com/kubermatic/kubermatic/pull/14176

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/14669

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
node-exporter chart is now using the upstream helm chart with app version 1.19.0
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/install/stack/seed-mla/stack.go [hunk 1]
```diff
@@ -659,35 +659,33 @@ func upgradeNodeExporterDaemonSets(
...
 		Version: "v1",
 	})
 
-	nodeExporterMatcher := ctrlruntimeclient.MatchingLabels{
-		"app.kubernetes.io/name": NodeExporterReleaseName,
-	}
-	if err := kubeClient.List(ctx, daemonsetsList, ctrlruntimeclient.InNamespace(NodeExporterNamespace), nodeExporterMatcher); err != nil {
+	key := types.NamespacedName{Name: NodeExporterReleaseName, Namespace: NodeExporterNamespace}
+
+	if err := kubeClient.Get(ctx, key, daemonset); err != nil {
```
Comment (moelsayed) [inline pkg/install/stack/seed-mla/stack.go]: What happens if the daemon set doesn't exist?

Comment (archups) [reply pkg/install/stack/seed-mla/stack.go]: We discussed about the upgrade process internally on how it is implemented in general for all the helm charts. Hope we are aligned. Thanks!

Comment (moelsayed) [reply pkg/install/stack/seed-mla/stack.go]: Yes, thank you. As discussed, we shouldn't fail if we can't find something we are trying to delete anyway. I would recommend that we fix this logic here, and if the same issue exists in other places, we can handle it later in follow up PRs/issues.

Comment (archups) [reply pkg/install/stack/seed-mla/stack.go]: Logic is fixed here now. PTAL. Thanks!
