### PR TITLE
Fix flaky metallb and other app catalog e2e tests

### LINKED ISSUE #14935: Fix failing metallb app catalog E2E test
Currently the metallb E2E tests are failing see https://github.com/kubermatic/kubermatic/pull/14934 & https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_kubermatic/14934/pre-kubermatic-appcatalog-metallb/1960683499778215936 for an example.

We need to investigate and fix it

### PR DESCRIPTION
**Pull request by mgoltzsche**
**What this PR does / why we need it**:

* Make the metallb KKP app use a newer frr version (10.4.1) by default which fixes bugs that affected installations on AWS (zebra process dying silently or crashing and watchfrr not restarting it, e.g. see https://github.com/FRRouting/frr/issues/18699).
* Increase the timeout to poll for pod readiness within app catalog e2e tests. This is because the metallb speaker Pod (its frr container in particular) sometimes takes a very long time to start. Also, I noticed other app tests sometimes exceeding the 7 Minute timeout.
* Increase the timeouts to poll for the ApplicationCatalog and Project resources to become ready since otherwise most of the app catalog e2e tests fail when the environment is under high load which happens when all of them are kicked off at once which started to happen in this PR after my [PR to fix the file path conditions of prow jobs](https://github.com/kubermatic/kubermatic/pull/15637) was merged.

**Which issue(s) this PR fixes**:

Fixes #14935

**What type of PR is this?**
/kind failing-test

**Special notes for your reviewer**:
Apart from e2e test chores, the PR also modifies the default values of the metallb app, overwriting the frr image which is a user-facing change.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
By default the metallb app uses frr 10.4.1 now which fixes a bug that affected installations on AWS.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by mgoltzsche** [comment]
Collecting evidence about the failing metallb speaker Pod...

<details>
<summary>
Pod events show that the frr container's startup probe is failing.
</summary>

```sh
$ kubectl -n metallb describe pod metallb-metallb-speaker-szpxl
Name:             metallb-metallb-speaker-szpxl
Namespace:        metallb
Priority:         0
Service Account:  metallb-metallb-speaker
Node:             ip-172-31-28-88.eu-west-1.compute.internal/172.31.28.88
Start Time:       Mon, 16 Mar 2026 17:27:58 +0100
Labels:           app.kubernetes.io/component=speaker
                  app.kubernetes.io/instance=metallb-metallb
                  app.kubernetes.io/name=metallb
                  controller-revision-hash=6885459d6f
                  pod-template-generation=1
Annotations:      <none>
Status:           Running
IP:               172.31.28.88
IPs:
  IP:           172.31.28.88
Controlled By:  DaemonSet/metallb-metallb-speaker
Init Containers:
  cp-frr-files:
    Container ID:  containerd://756698953190aa412a99c0922a7b013ac9cb3de02d786aa6153882adf4be2b15
    Image:         quay.io/frrouting/frr:8.4.2
    Image ID:      quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      cp -rLf /tmp/frr/* /etc/frr/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 16 Mar 2026 17:28:10 +0100
      Finished:     Mon, 16 Mar 2026 17:28:10 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/frr from frr-conf (rw)
      /tmp/frr from frr-startup (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
  cp-reloader:
    Container ID:  containerd://d54431cfba1c6f0e9a058d6129fc240414c887abe3b54bbb84cb8e40117b55af
    Image:         quay.io/metallb/speaker:v0.13.10
    Image ID:      quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      cp -f /frr-reloader.sh /etc/frr_reloader/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 16 Mar 2026 17:28:14 +0100
      Finished:     Mon, 16 Mar 2026 17:28:14 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/frr_reloader from reloader (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
  cp-metrics:
    Container ID:  containerd://5e3957c6d807a0ebe6cd6095387d391ee8317744227a0b93c35b8cc94d3c4317
    Image:         quay.io/metallb/speaker:v0.13.10
    Image ID:      quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      cp -f /frr-metrics /etc/frr_metrics/
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 16 Mar 2026 17:28:15 +0100
      Finished:     Mon, 16 Mar 2026 17:28:16 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/frr_metrics from metrics (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
Containers:
  speaker:
    Container ID:  containerd://4b8f1abbd061af6b0910588dbd7bea6d89e4490b75712da458308aa4fec51d0f
    Image:         quay.io/metallb/speaker:v0.13.10
    Image ID:      quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    Ports:         7472/TCP (monitoring), 7946/TCP (memberlist-tcp), 7946/UDP (memberlist-udp)
    Host Ports:    7472/TCP (monitoring), 7946/TCP (memberlist-tcp), 7946/UDP (memberlist-udp)
    Args:
      --port=7472
      --log-level=info
    State:          Running
      Started:      Mon, 16 Mar 2026 17:28:16 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:monitoring/metrics delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:monitoring/metrics delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      METALLB_NODE_NAME:            (v1:spec.nodeName)
      METALLB_HOST:                 (v1:status.hostIP)
      METALLB_ML_BIND_ADDR:         (v1:status.podIP)
      METALLB_ML_LABELS:           app.kubernetes.io/name=metallb,app.kubernetes.io/component=speaker
      METALLB_ML_BIND_PORT:        7946
      METALLB_ML_SECRET_KEY_PATH:  /etc/ml_secret_key
      FRR_CONFIG_FILE:             /etc/frr_reloader/frr.conf
      FRR_RELOADER_PID_FILE:       /etc/frr_reloader/reloader.pid
      METALLB_BGP_TYPE:            frr
    Mounts:
      /etc/frr_reloader from reloader (rw)
      /etc/metallb from metallb-excludel2 (rw)
      /etc/ml_secret_key from memberlist (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
  frr:
    Container ID:  containerd://2a45fdc8d46c77c54d559fe3a50a7e622f696cbf756a7921d58d5905f47c58a5
    Image:         quay.io/frrouting/frr:8.4.2
    Image ID:      quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      /sbin/tini -- /usr/lib/frr/docker-start &
      attempts=0
      until [[ -f /etc/frr/frr.log || $attempts -eq 60 ]]; do
        sleep 1
        attempts=$(( $attempts + 1 ))
      done
      tail -f /etc/frr/frr.log
      
    State:          Running
      Started:      Mon, 16 Mar 2026 17:33:16 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Mon, 16 Mar 2026 17:30:46 +0100
      Finished:     Mon, 16 Mar 2026 17:33:16 +0100
    Ready:          False
    Restart Count:  2
    Liveness:       http-get http://:7473/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:        http-get http://:7473/livez delay=0s timeout=1s period=5s #success=1 #failure=30
    Environment:
      TINI_SUBREAPER:  true
    Mounts:
      /etc/frr from frr-conf (rw)
      /var/run/frr from frr-sockets (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
  reloader:
    Container ID:  containerd://70ad33d648768b9edf04ac8b69129ef92a4f8a840959909624f0c5d273499904
    Image:         quay.io/frrouting/frr:8.4.2
    Image ID:      quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    Port:          <none>
    Host Port:     <none>
    Command:
      /etc/frr_reloader/frr-reloader.sh
    State:          Running
      Started:      Mon, 16 Mar 2026 17:28:17 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/frr from frr-conf (rw)
      /etc/frr_reloader from reloader (rw)
      /var/run/frr from frr-sockets (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
  frr-metrics:
    Container ID:  containerd://6fcc1a52e06eeffd314e904d06f650b5dbfeb93951390c76b4cbbd30f52b5e0c
    Image:         quay.io/frrouting/frr:8.4.2
    Image ID:      quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    Port:          7473/TCP (monitoring)
    Host Port:     7473/TCP (monitoring)
    Command:
      /etc/frr_metrics/frr-metrics
    Args:
      --metrics-port=7473
    State:          Running
      Started:      Mon, 16 Mar 2026 17:28:17 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/frr from frr-conf (rw)
      /etc/frr_metrics from metrics (rw)
      /var/run/frr from frr-sockets (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xqvfh (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  memberlist:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metallb-metallb-memberlist
    Optional:    false
  metallb-excludel2:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metallb-excludel2
    Optional:  false
  frr-sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  frr-startup:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metallb-metallb-frr-startup
    Optional:  false
  frr-conf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  reloader:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-xqvfh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
                             node-role.kubernetes.io/master:NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    5m32s                  default-scheduler  Successfully assigned metallb/metallb-metallb-speaker-szpxl to ip-172-31-28-88.eu-west-1.compute.internal
  Warning  FailedMount  5m29s (x4 over 5m33s)  kubelet            MountVolume.SetUp failed for volume "memberlist" : secret "metallb-metallb-memberlist" not found
  Normal   Pulling      5m25s                  kubelet            spec.initContainers{cp-frr-files}: Pulling image "quay.io/frrouting/frr:8.4.2"
  Normal   Pulled       5m21s                  kubelet            spec.initContainers{cp-frr-files}: Successfully pulled image "quay.io/frrouting/frr:8.4.2" in 3.891s (3.891s including waiting). Image size: 72130687 bytes.
  Normal   Created      5m21s                  kubelet            spec.initContainers{cp-frr-files}: Created container: cp-frr-files
  Normal   Started      5m21s                  kubelet            spec.initContainers{cp-frr-files}: Started container cp-frr-files
  Normal   Pulling      5m20s                  kubelet            spec.initContainers{cp-reloader}: Pulling image "quay.io/metallb/speaker:v0.13.10"
  Normal   Pulled       5m17s                  kubelet            spec.initContainers{cp-reloader}: Successfully pulled image "quay.io/metallb/speaker:v0.13.10" in 2.985s (2.985s including waiting). Image size: 50291816 bytes.
  Normal   Created      5m17s                  kubelet            spec.initContainers{cp-reloader}: Created container: cp-reloader
  Normal   Started      5m17s                  kubelet            spec.initContainers{cp-reloader}: Started container cp-reloader
  Normal   Started      5m16s                  kubelet            spec.initContainers{cp-metrics}: Started container cp-metrics
  Normal   Created      5m16s                  kubelet            spec.initContainers{cp-metrics}: Created container: cp-metrics
  Normal   Pulled       5m16s                  kubelet            spec.initContainers{cp-metrics}: Container image "quay.io/metallb/speaker:v0.13.10" already present on machine
  Normal   Pulled       5m15s                  kubelet            spec.containers{speaker}: Container image "quay.io/metallb/speaker:v0.13.10" already present on machine
  Normal   Created      5m15s                  kubelet            spec.containers{speaker}: Created container: speaker
  Normal   Started      5m15s                  kubelet            spec.containers{speaker}: Started container speaker
  Normal   Pulled       5m14s                  kubelet            spec.containers{reloader}: Container image "quay.io/frrouting/frr:8.4.2" already present on machine
  Normal   Created      5m14s                  kubelet            spec.containers{frr}: Created container: frr
  Normal   Started      5m14s                  kubelet            spec.containers{frr}: Started container frr
  Normal   Created      5m14s                  kubelet            spec.containers{reloader}: Created container: reloader
  Normal   Started      5m14s                  kubelet            spec.containers{reloader}: Started container reloader
  Normal   Pulled       5m14s                  kubelet            spec.containers{frr-metrics}: Container image "quay.io/frrouting/frr:8.4.2" already present on machine
  Normal   Created      5m14s                  kubelet            spec.containers{frr-metrics}: Created container: frr-metrics
  Normal   Started      5m14s                  kubelet            spec.containers{frr-metrics}: Started container frr-metrics
  Normal   Pulled       2m45s (x2 over 5m15s)  kubelet            spec.containers{frr}: Container image "quay.io/frrouting/frr:8.4.2" already present on machine
  Warning  Unhealthy    30s (x57 over 5m10s)   kubelet            spec.containers{frr}: Startup probe failed: HTTP probe failed with statuscode: 404
  Normal   Killing      15s (x2 over 2m45s)    kubelet            spec.containers{frr}: Container frr failed startup probe, will be restarted
```
</details>

(The 2nd speaker Pod started up normally.)

<details>
<summary>
The failing speaker Pod's frr container logs that the initial connection attempt failed and attempts to kill its zebra process afterwards which apparently died already at that point.
Though, afterwards the processes seem to have come up again since the container logs that the connection was established successfully.
However, at that point the test failed and cleaned up the metallb installation and I didn't see the end of the log but the startup probe failures may have resulted in the restarting the Pod forcefully in the moment when it started to work...
</summary>

```
$ kubectl -n metallb logs metallb-metallb-speaker-szpxl frr
2026/03/16 16:32:20.630 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:20.793 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:20.793 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:20.793 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.627 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.628 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.628 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.786 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.786 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:32:50.786 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:16 WATCHFRR: [T83RR-8SM5G] watchfrr 8.4.2_git starting: vty@0
2026/03/16 16:33:16 WATCHFRR: [ZCJ3S-SPH5S] zebra state -> down : initial connection attempt failed
2026/03/16 16:33:16 WATCHFRR: [ZCJ3S-SPH5S] bgpd state -> down : initial connection attempt failed
2026/03/16 16:33:16 WATCHFRR: [ZCJ3S-SPH5S] staticd state -> down : initial connection attempt failed
2026/03/16 16:33:16 WATCHFRR: [ZCJ3S-SPH5S] bfdd state -> down : initial connection attempt failed
2026/03/16 16:33:16 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 494]: /usr/lib/frr/watchfrr.sh restart all
/usr/lib/frr/frrcommon.sh: line 211: kill: (396) - No such process
/usr/lib/frr/frrcommon.sh: line 211: kill: (398) - No such process
/usr/lib/frr/frrcommon.sh: line 211: kill: (391) - No such process
Cannot stop zebra: pid 387 not running
2026/03/16 16:33:16 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/16 16:33:17 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/16 16:33:17 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
vtysh: error reading from zebra: Connection reset by peer (104)Warning: closing connection to zebra because of an I/O error!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
2026/03/16 16:33:17 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/16 16:33:17 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/16 16:33:17 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/16 16:33:17 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:17 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:17 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.623 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.623 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.623 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.785 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.785 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 16:33:20.785 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
```

**Comment by mgoltzsche** [comment]
During another test run none of the speaker Pods came up:

<details>
<summary>
Complete speaker Pod's frr container log shows that, while 3 processes (bgpd, bfdd, staticd) within that container have established a connection successfully, the 4th one (zebra?!) did not and therefore all are killed once the startup timeout is exceeded.
</summary>

```
$ kubectl -n metallb logs metallb-metallb-speaker-m98v5 frr -f
2026/03/16 17:08:57 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:08:57 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:25.771 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:25.771 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:25.941 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:25.941 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:55.767 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:55.767 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:55.928 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:09:55.928 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:22 WATCHFRR: [T83RR-8SM5G] watchfrr 8.4.2_git starting: vty@0
2026/03/16 17:10:22 WATCHFRR: [ZCJ3S-SPH5S] zebra state -> down : initial connection attempt failed
2026/03/16 17:10:22 WATCHFRR: [ZCJ3S-SPH5S] bgpd state -> down : initial connection attempt failed
2026/03/16 17:10:22 WATCHFRR: [ZCJ3S-SPH5S] staticd state -> down : initial connection attempt failed
2026/03/16 17:10:22 WATCHFRR: [ZCJ3S-SPH5S] bfdd state -> down : initial connection attempt failed
2026/03/16 17:10:22 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 501]: /usr/lib/frr/watchfrr.sh restart all
/usr/lib/frr/frrcommon.sh: line 211: kill: (424) - No such process
/usr/lib/frr/frrcommon.sh: line 211: kill: (427) - No such process
/usr/lib/frr/frrcommon.sh: line 211: kill: (420) - No such process
Cannot stop zebra: pid 415 not running
2026/03/16 17:10:22 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/16 17:10:22 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/16 17:10:22 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
2026/03/16 17:10:22 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/16 17:10:22 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/16 17:10:22 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/16 17:10:22 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:22 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:22 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.782 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.782 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.782 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.943 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.943 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:25.943 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.779 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.780 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.780 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.938 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.938 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:10:55.938 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:17 WATCHFRR: [K54RW-4APGS][EC 268435457] startup did not complete within timeout (3/4 daemons running)
2026/03/16 17:11:25.773 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:25.773 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:25.773 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:25.931 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:25.931 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:25.932 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:27 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 607]: /usr/lib/frr/watchfrr.sh restart all
2026/03/16 17:11:27 WATCHFRR: [HD38Q-0HBRT][EC 268435457] staticd state -> down : read returned EOF
2026/03/16 17:11:27 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bfdd state -> down : read returned EOF
2026/03/16 17:11:27 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : read returned EOF
2026/03/16 17:11:27 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/16 17:11:27 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : unexpected read error: Connection reset by peer
Cannot stop zebra: pid 518 not running
2026/03/16 17:11:27 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/16 17:11:27 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/16 17:11:27 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
vtysh: error reading from zebra: Connection reset by peer (104)Warning: closing connection to zebra because of an I/O error!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
2026/03/16 17:11:27 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/16 17:11:27 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/16 17:11:27 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/16 17:11:27.446 STATIC: [MRN6F-AYZC4] Terminating on signal
2026/03/16 17:11:27.448 BGP: [ZW1GY-R46JE] Terminating on signal
2026/03/16 17:11:27 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:27 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:27 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.762 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.762 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.762 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.920 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.921 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:11:55.921 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/16 17:12:13 WATCHFRR: [NG1AJ-FP2TQ] Terminating on signal
```
</details>

**Comment by mgoltzsche** [comment]
<details>
<summary>Generated frr.conf</summary>

```
frr version 7.5.1
frr defaults traditional
hostname Router
line vty
log file /etc/frr/frr.log informational
```
</details>

**Comment by mgoltzsche** [comment]
This time both speaker Pods came up successfully.

<details>
<summary>metallb Pods</summary>

```
$ kubectl -n metallb get pod -o wide
NAME                                          READY   STATUS    RESTARTS        AGE    IP              NODE                                          NOMINATED NODE   READINESS GATES
metallb-metallb-controller-6489dcc96d-rdbgp   1/1     Running   0               5m6s   172.25.1.202    ip-172-31-22-218.eu-west-1.compute.internal   <none>           <none>
metallb-metallb-speaker-cnpmv                 4/4     Running   1 (2m22s ago)   5m6s   172.31.22.218   ip-172-31-22-218.eu-west-1.compute.internal   <none>           <none>
metallb-metallb-speaker-pqxbf                 4/4     Running   0               5m6s   172.31.30.186   ip-172-31-30-186.eu-west-1.compute.internal   <none>           <none>
```
</details>

<details>
<summary>speaker pod yaml</summary>

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-03-17T10:54:16Z"
  generateName: metallb-metallb-speaker-
  generation: 1
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: metallb-metallb
    app.kubernetes.io/name: metallb
    controller-revision-hash: 6885459d6f
    pod-template-generation: "1"
  name: metallb-metallb-speaker-pqxbf
  namespace: metallb
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: metallb-metallb-speaker
    uid: def7baee-d54f-4c96-b208-6d8eb069d280
  resourceVersion: "3842"
  uid: 3d308057-a1b7-42b1-bb3d-b350c90b04a3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-172-31-30-186.eu-west-1.compute.internal
  containers:
  - args:
    - --port=7472
    - --log-level=info
    env:
    - name: METALLB_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: METALLB_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: METALLB_ML_BIND_ADDR
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: METALLB_ML_LABELS
      value: app.kubernetes.io/name=metallb,app.kubernetes.io/component=speaker
    - name: METALLB_ML_BIND_PORT
      value: "7946"
    - name: METALLB_ML_SECRET_KEY_PATH
      value: /etc/ml_secret_key
    - name: FRR_CONFIG_FILE
      value: /etc/frr_reloader/frr.conf
    - name: FRR_RELOADER_PID_FILE
      value: /etc/frr_reloader/reloader.pid
    - name: METALLB_BGP_TYPE
      value: frr
    image: quay.io/metallb/speaker:v0.13.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: speaker
    ports:
    - containerPort: 7472
      hostPort: 7472
      name: monitoring
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-tcp
      protocol: TCP
    - containerPort: 7946
      hostPort: 7946
      name: memberlist-udp
      protocol: UDP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_RAW
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ml_secret_key
      name: memberlist
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /etc/metallb
      name: metallb-excludel2
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  - command:
    - /bin/sh
    - -c
    - |
      /sbin/tini -- /usr/lib/frr/docker-start &
      attempts=0
      until [[ -f /etc/frr/frr.log || $attempts -eq 60 ]]; do
        sleep 1
        attempts=$(( $attempts + 1 ))
      done
      tail -f /etc/frr/frr.log
    env:
    - name: TINI_SUBREAPER
      value: "true"
    image: quay.io/frrouting/frr:8.4.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /livez
        port: 7473
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: frr
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_ADMIN
        - NET_BIND_SERVICE
    startupProbe:
      failureThreshold: 30
      httpGet:
        path: /livez
        port: 7473
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  - command:
    - /etc/frr_reloader/frr-reloader.sh
    image: quay.io/frrouting/frr:8.4.2
    imagePullPolicy: IfNotPresent
    name: reloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  - args:
    - --metrics-port=7473
    command:
    - /etc/frr_metrics/frr-metrics
    image: quay.io/frrouting/frr:8.4.2
    imagePullPolicy: IfNotPresent
    name: frr-metrics
    ports:
    - containerPort: 7473
      hostPort: 7473
      name: monitoring
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /etc/frr_metrics
      name: metrics
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - /bin/sh
    - -c
    - cp -rLf /tmp/frr/* /etc/frr/
    image: quay.io/frrouting/frr:8.4.2
    imagePullPolicy: IfNotPresent
    name: cp-frr-files
    resources: {}
    securityContext:
      runAsGroup: 101
      runAsUser: 100
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/frr
      name: frr-startup
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  - command:
    - /bin/sh
    - -c
    - cp -f /frr-reloader.sh /etc/frr_reloader/
    image: quay.io/metallb/speaker:v0.13.10
    imagePullPolicy: IfNotPresent
    name: cp-reloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  - command:
    - /bin/sh
    - -c
    - cp -f /frr-metrics /etc/frr_metrics/
    image: quay.io/metallb/speaker:v0.13.10
    imagePullPolicy: IfNotPresent
    name: cp-metrics
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/frr_metrics
      name: metrics
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
  nodeName: ip-172-31-30-186.eu-west-1.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: metallb-metallb-speaker
  serviceAccountName: metallb-metallb-speaker
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - name: memberlist
    secret:
      defaultMode: 420
      secretName: metallb-metallb-memberlist
  - configMap:
      defaultMode: 256
      name: metallb-excludel2
    name: metallb-excludel2
  - emptyDir: {}
    name: frr-sockets
  - configMap:
      defaultMode: 420
      name: metallb-metallb-frr-startup
    name: frr-startup
  - emptyDir: {}
    name: frr-conf
  - emptyDir: {}
    name: reloader
  - emptyDir: {}
    name: metrics
  - name: kube-api-access-8d7lq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-03-17T10:54:25Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-03-17T10:54:29Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-03-17T10:59:03Z"
    observedGeneration: 1
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-03-17T10:55:35Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-03-17T10:54:16Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f8d42e9a1c59cfcbc3133f6190502cee052bb373bff2f281f225b6927a2ec1e8
    image: quay.io/frrouting/frr:8.4.2
    imageID: quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    lastState: {}
    name: frr
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-17T10:54:29Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://c91a98a7c11ab8121cc263775eee923c52f8ae0a75248924f2e858ee132c4b63
    image: quay.io/frrouting/frr:8.4.2
    imageID: quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    lastState: {}
    name: frr-metrics
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-17T10:54:29Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /etc/frr_metrics
      name: metrics
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://f4289da2aa4fa008a94cc0a62b28c32b332c625d2107e873341919cf98154ef6
    image: quay.io/frrouting/frr:8.4.2
    imageID: quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    lastState: {}
    name: reloader
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-17T10:54:29Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /var/run/frr
      name: frr-sockets
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://288e7f13290ef3a7cc6195c29a546791e0009a4bd7fc43564df7b6b9d6386da5
    image: quay.io/metallb/speaker:v0.13.10
    imageID: quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    lastState: {}
    name: speaker
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-17T10:54:29Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /etc/ml_secret_key
      name: memberlist
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /etc/metallb
      name: metallb-excludel2
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.31.30.186
  hostIPs:
  - ip: 172.31.30.186
  initContainerStatuses:
  - containerID: containerd://38c8942ccf0b1813c20e26c838886aab2e80d46f9340574c2abb4dafbf1a181a
    image: quay.io/frrouting/frr:8.4.2
    imageID: quay.io/frrouting/frr@sha256:54f9a7b9e5436430dea61314169690d08f40342d2ac82406bb9463a53edf8d6f
    lastState: {}
    name: cp-frr-files
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://38c8942ccf0b1813c20e26c838886aab2e80d46f9340574c2abb4dafbf1a181a
        exitCode: 0
        finishedAt: "2026-03-17T10:54:24Z"
        reason: Completed
        startedAt: "2026-03-17T10:54:24Z"
    user:
      linux:
        gid: 101
        supplementalGroups:
        - 101
        - 102
        uid: 100
    volumeMounts:
    - mountPath: /tmp/frr
      name: frr-startup
    - mountPath: /etc/frr
      name: frr-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://06e12c635e92be41a6e985419f34607b43041d060d0a1fa0c1bcf3dabf78228d
    image: quay.io/metallb/speaker:v0.13.10
    imageID: quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    lastState: {}
    name: cp-reloader
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://06e12c635e92be41a6e985419f34607b43041d060d0a1fa0c1bcf3dabf78228d
        exitCode: 0
        finishedAt: "2026-03-17T10:54:28Z"
        reason: Completed
        startedAt: "2026-03-17T10:54:28Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /etc/frr_reloader
      name: reloader
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://e3b1f69be6becac00fa1969e9110223cd8d0d067353feb1017761cc2110895bd
    image: quay.io/metallb/speaker:v0.13.10
    imageID: quay.io/metallb/speaker@sha256:00406ccb1fa08d48cc0ed0b43db7b3cbc3ccc1c4da0e38fca648e64639b06c3c
    lastState: {}
    name: cp-metrics
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://e3b1f69be6becac00fa1969e9110223cd8d0d067353feb1017761cc2110895bd
        exitCode: 0
        finishedAt: "2026-03-17T10:54:28Z"
        reason: Completed
        startedAt: "2026-03-17T10:54:28Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 6
        - 10
        - 11
        - 20
        - 26
        - 27
        uid: 0
    volumeMounts:
    - mountPath: /etc/frr_metrics
      name: metrics
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8d7lq
      readOnly: true
      recursiveReadOnly: Disabled
  observedGeneration: 1
  phase: Running
  podIP: 172.31.30.186
  podIPs:
  - ip: 172.31.30.186
  qosClass: BestEffort
  startTime: "2026-03-17T10:54:16Z"
```
</details>

File: hack/ci/run-default-application-e2e-test.sh [hunk 1]
```diff
@@ -102,7 +103,8 @@ run_application_tests() {
         -application-version "$version" \
         -app-label-key "$APP_LABEL_KEY" \
         -names "$NAMES" \
-        -default-values-block "$defaultValuesBlock"
+        -default-values-block "$defaultValuesBlock" \
+        -deploy-timeout "${APPLICATION_INSTALLATION_TIMEOUT:-0}"
```
Comment (mgoltzsche) [inline hack/ci/run-default-application-e2e-test.sh]: No need to increase the timeout per test scenario when we can increase it for all of them by a few minutes.

**Comment by mgoltzsche** [comment]
Apparently the problem is really simply caused by the frr container failing to initialize in time and then being terminated due to the speaker Pod's startupProbe failureThreshold of 30 being exceeded eventually. When increasing the test timeout from 7 to 11 minutes the frr container becomes ready eventually after ~9 minutes and several restarts.
Thus, the immediate fix for the e2e test is to increase the timeout the test waits for the container to start up.
Though, ideally the startupProbe of the metallb speaker Pod should also be increased to avoid early termination of the Pod which should make it more likely for the Pod to to become ready sooner. For that the following metallb Helm chart value would have to be set:
```yaml
speaker:
  startupProbe:
    failureThreshold: 60
```

File: pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml [hunk 2]
```diff
@@ -48,6 +48,10 @@ spec:
           chartVersion: 0.14.9
           url: oci://quay.io/kubermatic-mirror/helm-charts
     version: v0.14.9
+  defaultValuesBlock: |-
+    speaker:
+      startupProbe:
+        failureThreshold: 90
```
Comment (mgoltzsche) [inline pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml]: Looks like increasing the startupProbe didn't help but rather worsened the problem: now the test times out without any metallb speaker Pod becoming healthy but the Pods also didn't restart. That makes me think that restarting the failing Pod may have actually helped previously. Therefore I am reverting this change.

**Comment by mgoltzsche** [comment]
The last metallb test run failed again despite a 12 minute timeout. After 7 minutes the first speaker Pod was ready but the 2nd didn't make it until the timeout.
Therefore I increased the timeout to 15 minutes now.

Also, since my [PR to fix the file path conditions for prow jobs](https://github.com/kubermatic/kubermatic/pull/15637) was merged, a lot more flaky e2e tests can be observed. To also overcome that flakiness, I also increased retries at another place but that may not be the last problem.

It might be worth increasing the number of CPU core requests per prow job since otherwise multiple concurrent jobs running on the same node might steal each other's compute resources due to the lack of CPU limits. Alternatively we could consider configuring CPU limits for the prow jobs without over-committing (much) to make the e2e tests more deterministic also in case of massive parallel job execution.

**Comment by mgoltzsche** [comment]
Tweaking the compute resources of the prow jobs will not cut it since the user cluster nodes within the e2e test are running on dedicated EC2 instances - only the seed cluster is based on kind and running inside the prow job...

**Comment by mgoltzsche** [comment]
For comparison here are the logs of a successful and a failing frr container (test status poll timeout set to 25m and metallb speaker Pod startupProbe.failureThreshold set to 120):

<details>
<summary>Log of a successfully initialized frr container (also contains `Disabling MPLS support (no kernel support)` warning but zebra didn't crash)</summary>

```
2026/03/19 12:59:07 WATCHFRR: [T83RR-8SM5G] watchfrr 8.4.2_git starting: vty@0
2026/03/19 12:59:07 WATCHFRR: [ZCJ3S-SPH5S] zebra state -> down : initial connection attempt failed
2026/03/19 12:59:07 WATCHFRR: [ZCJ3S-SPH5S] bgpd state -> down : initial connection attempt failed
2026/03/19 12:59:07 WATCHFRR: [ZCJ3S-SPH5S] staticd state -> down : initial connection attempt failed
2026/03/19 12:59:07 WATCHFRR: [ZCJ3S-SPH5S] bfdd state -> down : initial connection attempt failed
2026/03/19 12:59:07 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 53]: /usr/lib/frr/watchfrr.sh restart all
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
Cannot stop zebra: pid file not found
2026/03/19 12:59:07 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/19 12:59:07 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/19 12:59:07 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] zebra state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [KWE5Q-QNGFC] all daemons up, doing startup-complete notify
2026/03/19 12:59:07 ZEBRA: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:07 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:07 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:07 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11 WATCHFRR: [WFP93-1D146] configuration write completed with exit code 0
2026/03/19 12:59:11.246 ZEBRA: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.246 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.246 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.247 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.404 ZEBRA: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.404 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.404 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.405 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:27.839 BGP: [VCGF0-X62M1][EC 100663301] INTERFACE_STATE: Cannot find IF lxc03e9d8f8d316 in VRF 0
```
</details>

<details>
<summary>Log of a failing frr container (logs `zebra crashed in startup, signal 11` initially; container was terminated shortly afterwards due to the startupProbe.failureThreshold being exceeded)</summary>

```
2026/03/19 12:59:06 WATCHFRR: [T83RR-8SM5G] watchfrr 8.4.2_git starting: vty@0
2026/03/19 12:59:06 WATCHFRR: [ZCJ3S-SPH5S] zebra state -> down : initial connection attempt failed
2026/03/19 12:59:06 WATCHFRR: [ZCJ3S-SPH5S] bgpd state -> down : initial connection attempt failed
2026/03/19 12:59:06 WATCHFRR: [ZCJ3S-SPH5S] staticd state -> down : initial connection attempt failed
2026/03/19 12:59:06 WATCHFRR: [ZCJ3S-SPH5S] bfdd state -> down : initial connection attempt failed
2026/03/19 12:59:06 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 50]: /usr/lib/frr/watchfrr.sh restart all
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
/usr/lib/frr/frrcommon.sh: line 211: kill: `': not a pid or valid job spec
Cannot stop zebra: pid file not found
2026/03/19 12:59:07 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
zebra crashed in startup, signal 11
Failed to start zebra!
2026/03/19 12:59:07 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/19 12:59:07 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/19 12:59:07 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/19 12:59:07 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:07 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:07 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.305 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.305 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.306 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.465 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.465 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:11.465 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.662 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.662 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.663 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.876 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.876 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 12:59:40.876 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:01 WATCHFRR: [K54RW-4APGS][EC 268435457] startup did not complete within timeout (3/4 daemons running)
2026/03/19 13:00:07 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 157]: /usr/lib/frr/watchfrr.sh restart all
2026/03/19 13:00:07 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bfdd state -> down : read returned EOF
2026/03/19 13:00:07 WATCHFRR: [HD38Q-0HBRT][EC 268435457] staticd state -> down : write 'echo PING' returned -1 instead of 10
2026/03/19 13:00:07 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : read returned EOF
Cannot stop zebra: pid 83 not running
2026/03/19 13:00:08 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/19 13:00:07.928 BGP: [ZW1GY-R46JE] Terminating on signal
2026/03/19 13:00:07.936 STATIC: [MRN6F-AYZC4] Terminating on signal
2026/03/19 13:00:09 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/19 13:00:09 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
vtysh: error reading from zebra: Connection reset by peer (104)Warning: closing connection to zebra because of an I/O error!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
2026/03/19 13:00:09 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 13:00:09 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/19 13:00:09 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/19 13:00:09 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:09 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:09 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.781 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.781 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.781 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.972 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.972 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:10.972 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.678 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.678 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.678 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.891 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.891 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:00:40.891 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.687 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.687 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.687 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.906 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.906 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:10.906 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.666 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.666 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.666 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.883 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.883 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:01:40.884 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.664 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.664 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.664 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.879 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.879 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:10.879 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:14 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 328]: /usr/lib/frr/watchfrr.sh restart all
2026/03/19 13:02:14 WATCHFRR: [HD38Q-0HBRT][EC 268435457] staticd state -> down : read returned EOF
2026/03/19 13:02:14 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : read returned EOF
2026/03/19 13:02:14 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bfdd state -> down : read returned EOF
Cannot stop zebra: pid 180 not running
2026/03/19 13:02:14 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/19 13:02:14.624 BGP: [ZW1GY-R46JE] Terminating on signal
2026/03/19 13:02:14.625 STATIC: [MRN6F-AYZC4] Terminating on signal
2026/03/19 13:02:14 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/19 13:02:14 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
vtysh: error reading from zebra: Connection reset by peer (104)Warning: closing connection to zebra because of an I/O error!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
Warning: connecting to zebra...failed!
2026/03/19 13:02:15 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 13:02:15 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/19 13:02:15 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/19 13:02:15 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:01
2026/03/19 13:02:15 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:01
2026/03/19 13:02:15 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:01
2026/03/19 13:02:40.683 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:40.683 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:40.683 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:40.900 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:40.900 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:02:40.900 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.692 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.692 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.692 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.916 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.917 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:10.917 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.656 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.656 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.656 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.875 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.875 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:03:40.875 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.669 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.670 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.670 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.885 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.885 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:10.885 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.677 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.677 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.677 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.887 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.887 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:04:40.888 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.690 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.690 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.690 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.907 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.907 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:10.907 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.665 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.665 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.665 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.874 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.874 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:05:40.874 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.660 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.660 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.660 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.876 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.876 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:10.876 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:15 WATCHFRR: [YFT0P-5Q5YX] Forked background command [pid 580]: /usr/lib/frr/watchfrr.sh restart all
2026/03/19 13:06:15 WATCHFRR: [HD38Q-0HBRT][EC 268435457] staticd state -> down : read returned EOF
2026/03/19 13:06:15 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bfdd state -> down : read returned EOF
2026/03/19 13:06:15 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : read returned EOF
2026/03/19 13:06:15 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 13:06:15 WATCHFRR: [HD38Q-0HBRT][EC 268435457] bgpd state -> down : unexpected read error: Connection reset by peer
Cannot stop zebra: pid 348 not running
2026/03/19 13:06:15 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
2026/03/19 13:06:15 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/profile/minimum-ttl'
2026/03/19 13:06:15 BFD: [ZKB8W-3S2Q4][EC 100663330] unneeded 'destroy' callback for '/frr-bfdd:bfdd/bfd/sessions/multi-hop/minimum-ttl'
2026/03/19 13:06:15 WATCHFRR: [QDG3Y-BY5TN] bgpd state -> up : connect succeeded
2026/03/19 13:06:15 WATCHFRR: [QDG3Y-BY5TN] staticd state -> up : connect succeeded
2026/03/19 13:06:15 WATCHFRR: [QDG3Y-BY5TN] bfdd state -> up : connect succeeded
2026/03/19 13:06:15.142 STATIC: [MRN6F-AYZC4] Terminating on signal
2026/03/19 13:06:15.144 BGP: [ZW1GY-R46JE] Terminating on signal
2026/03/19 13:06:15 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:15 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:15 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.687 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.687 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.687 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.901 BGP: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.901 STATIC: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
2026/03/19 13:06:40.901 BFD: [VTVCM-Y2NW3] Configuration Read in Took: 00:00:00
```
</details>

<details>
<summary>List of all Pods within the user cluster</summary>

```
$ kubectl get pod -Ao wide
NAMESPACE              NAME                                          READY   STATUS      RESTARTS   AGE   IP              NODE                                          NOMINATED NODE   READINESS GATES
kube-system            cilium-8ch78                                  1/1     Running     0          12m   172.31.22.82    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            cilium-bkxgg                                  1/1     Running     0          12m   172.31.25.108   ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
kube-system            cilium-operator-cc88c9f78-m7q49               1/1     Running     0          12m   172.31.25.108   ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
kube-system            coredns-76956df94d-2z6cz                      1/1     Running     0          14m   172.25.0.184    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            coredns-76956df94d-mqg2x                      1/1     Running     0          14m   172.25.0.218    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            ebs-csi-controller-69bc7c65bd-4xtwr           5/5     Running     0          14m   172.25.0.134    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            ebs-csi-controller-69bc7c65bd-kz4hb           5/5     Running     0          14m   172.25.0.62     ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            ebs-csi-node-bhx4f                            3/3     Running     0          12m   172.25.1.18     ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
kube-system            ebs-csi-node-r9mdn                            3/3     Running     0          12m   172.25.0.55     ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            hubble-generate-certs-f7jrt                   0/1     Completed   0          12m   172.25.0.214    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            hubble-relay-5cc59dfcb4-dzsd5                 1/1     Running     0          12m   172.25.0.82     ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            hubble-ui-58c86bcb8c-7djbx                    2/2     Running     0          12m   172.25.0.226    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            konnectivity-agent-5689588d8-2jg4b            1/1     Running     0          14m   172.25.0.63     ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            konnectivity-agent-5689588d8-7r5wb            1/1     Running     0          14m   172.25.0.4      ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            metrics-server-645c9bff67-ng2jw               1/1     Running     0          14m   172.25.0.242    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            metrics-server-645c9bff67-xn59b               1/1     Running     0          14m   172.25.0.240    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kube-system            node-local-dns-jw2dx                          1/1     Running     0          12m   172.31.25.108   ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
kube-system            node-local-dns-wb7wj                          1/1     Running     0          12m   172.31.22.82    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kubernetes-dashboard   dashboard-metrics-scraper-f7bfc94dd-gwgnx     1/1     Running     0          14m   172.25.0.166    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
kubernetes-dashboard   dashboard-metrics-scraper-f7bfc94dd-lwbpd     1/1     Running     0          14m   172.25.0.239    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
metallb                metallb-metallb-controller-6489dcc96d-4v8qv   1/1     Running     0          10m   172.25.1.169    ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
metallb                metallb-metallb-speaker-m4b8d                 4/4     Running     0          10m   172.31.25.108   ip-172-31-25-108.eu-west-1.compute.internal   <none>           <none>
metallb                metallb-metallb-speaker-wb6kz                 3/4     Running     0          10m   172.31.22.82    ip-172-31-22-82.eu-west-1.compute.internal    <none>           <none>
```
</details>

Two minutes later the failing speaker Pod was restarted due to the startupProbe.failureThreshold exceeded at which point it initialized successfully immediately.

<details>
<summary>The Linux kernel used by user cluster machines is pretty recent but AWS-specific</summary>

```
# uname -a
Linux test 6.17.0-1007-aws #7~24.04.1-Ubuntu SMP Thu Jan 22 21:04:49 UTC 2026 x86_64 Linux
```
</details>

File: hack/ci/run-default-application-e2e-test.sh (hunk 1 above)
Comment (mgoltzsche) [reply hack/ci/run-default-application-e2e-test.sh]: I added that again now in order to only increase the timeout for the metallb e2e test as opposed to all apps since the metallb test needs a very high timeout as an exception to take its occasionally very long taking startup time into account.

**Comment by mgoltzsche** [comment]
I was able to reproduce the very slow metallb speaker startup time on AWS outside the e2e test. Thus, it is not a problem of the e2e test setup but really a problem of metallb which resolves itself eventually but it can take a long time.
A previous test run even timed out after 25 minutes which is why I increased the timeout for metallb to 35 minutes now.
Within the e2e test the slow startup time is more likely to occur since the test is repeated for every version of the metallb app.

UPDATE: I increased the timeout to 45 minutes.

**Comment by mgoltzsche** [comment]
Turns out the extreme metallb speaker startup slowness only appears on AWS, not on kubevirt or GCP.
While it takes seconds to 6 minutes for the speaker Pod to start on kubevirt or GCP, I just observed a case where it took 70 minutes and 18 restarts for the speaker Pod to become ready on an EC2 instance on AWS.

**Comment by mgoltzsche** [comment]
Turns out the root cause is that, in case of a failing speaker Pod, the zebra process within the frr container terminates immediately (sometimes it crashes with a segmentation fault, see e.g. https://github.com/FRRouting/frr/issues/18699; sometimes it doesn't log any error but terminates silently) and is not restarted by the watchfrr process at that point.
Inspecting the running processes within the frr container confirms that:
```
# ps aux | grep -E 'zebra|bfdd|bgpd|staticd'
   73 root      0:00 /usr/lib/frr/watchfrr zebra mgmtd bgpd staticd bfdd
  370 frr       0:00 /usr/lib/frr/bgpd -d -F traditional -A 127.0.0.1 -p 0
  375 frr       0:00 /usr/lib/frr/staticd -d -F traditional -A 127.0.0.1
  377 frr       0:00 /usr/lib/frr/bfdd -d -F traditional -A 127.0.0.1
  414 root      0:00 grep -E zebra|bfdd|bgpd|staticd
```
Manually starting the zebra process inside the frr container in such a situation makes the frr container and speaker Pod become ready immediately:
```
# /usr/lib/frr/zebra -d -F traditional -A 127.0.0.1 -s 90000000
2026/03/20 14:43:47 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support)
```
This also explains why the speaker Pod becomes healthy, if at all, only shortly after a container restart: that forcefully restarts the zebra process. Increasing the `speaker.startupProbe.failureThreshold` is therefore disadvantageous in this case.

This only happens when running metallb on AWS (possibly due to AWS' custom Linux kernel and complex network setup).

The bug(s) have been fixed in newer frr versions but the older metallb versions installed by the KKP app use an older frr version. Therefore using a newer frr container image with the metallb chart solves the problem, e.g. using the following metallb chart values:
```yaml
speaker:
  frr:
    image:
      tag: 10.4.1 # default in metallb v0.15.3
```
Therefore ideally the metallb KKP app should install an up-to-date metallb chart version.

**Review by mohamed-rafraf — APPROVED** [review]

**Review by mohamed-rafraf — APPROVED** [review]
/approve
/lgtm
