### PR TITLE
fix default policy catalog reconcile loop timeout from policy spec on installer rerun

### LINKED ISSUE #14884: With deploy-default-policy-template-catalog, second run of installer fails
### What happened?

KKP installer fails with the following error when `deploy-default-policy-template-catalog` is enabled and PolicyTemplates already exist.

```
time="2025-08-10T11:40:13Z" level=error msg="❌ Operation failed: failed to deploy default Policy Template catalog: failed to apply PolicyTemplates: failed to ensure PolicyTemplate /disallow-capabilities-strict: failed waiting for the cache to contain our latest changes: context deadline exceeded."
```

### How to reproduce the issue?

Re-run installer after PolicyTemplates have been installed.

### How is your environment configured?

- KKP version: 2.28.1
- Shared or separate master/seed clusters?: N/A

### PR DESCRIPTION
**Pull request by adoi**
**What this PR does / why we need it**:
This PR fixes the bug we were facing when rerunning the policy catalog through kubermatic installer.

Rerunning the default policy catalog was hitting the retry loop because the `PolicyTemplate.Spec.PolicySpec` we generated from the embedded Kyverno policies wasn’t in canonical json. On every reconcile our desired object differed from what the informer cache held, although they were the same (well, semantically). The reconciling framework updated the resource on each run and then timed out waiting for a change. 

This PR keeps the strict Kyverno validation (from UnmarshalStrict) because of validation safety, but converts `ClusterPolicy.Spec` into an unstructured map and marshals it back to json, ensuring we provide the same bytes to the reconciler. After this step there will be no unnecessary diff detected and the catalog will be deployed as intended.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/14884

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix the default policy catalog `--deploy-default-policy-template-catalog` flag timing out in the installer.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/ee/default-policy-catalog/embed.go [hunk 1]
```diff
@@ -71,6 +71,8 @@ func GetPolicyTemplates() ([]kubermaticv1.PolicyTemplate, error) {
 
 // convertClusterPolicyToPolicyTemplate converts a Kyverno ClusterPolicy to a Kubermatic PolicyTemplate.
 func convertClusterPolicyToPolicyTemplate(file fs.File) (kubermaticv1.PolicyTemplate, error) {
+	defer file.Close()
```
Comment (kron4eg) [inline pkg/ee/default-policy-catalog/embed.go]: I'd argue that it's caller's of `convertClusterPolicyToPolicyTemplate()` responsibility to close the file. Whom opened the file, that's closing it.

Comment (adoi) [reply pkg/ee/default-policy-catalog/embed.go]: Since we are working with embed FS we can completely skip closing it, but I added it to be safe for the future. For now even deleting it completely would work, but let's add closing in the caller func so that we're safe.

**Review by kron4eg — APPROVED** [review]
/approve
