### PR TITLE
Unblock reconciliation loop if default backup destination is not set

### LINKED ISSUE #11833: etcd backups doesn't work if `defaultDestination` field is not set
### What happened?

My etcd backups stopped working after I removed `defaultDestination` from the Seed CR.

### Expected behavior

Backups should run just fine without `defaultDestination` field.

### How to reproduce the issue?

1. Ensure `defaultDestination` is set on your Seed object.
2. Go to one of your user clusters.
3. Go to etcd backups tab.
4. Create a new automatic configuration alongside the default one. (for debugging convenience use cron expression like `*/5 * * * * *`)
5. Wait for the first snapshot to appear.
6. Now edit your seed object and remove the `defaultDestination` field.

### How is your environment configured?

- KKP version: 2.21

### Additional information

Looks like this place is the culprit: https://github.com/kubermatic/kubermatic/blob/release/v2.21/pkg/apis/kubermatic/v1/datacenter.go#L832

This check happens at the very beginning of etcd backup controller’s reconciliation loop: https://github.com/kubermatic/kubermatic/blob/release/v2.21/pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go#L198

As a result, if you delete the default backup destination, the controller stops processing any etcd backup configs - including cleanup logic.

To **workaround** this issue you can set some dummy value for `defaultDestination`. 

Most probably this is just an oversight that should be part of https://github.com/kubermatic/kubermatic/pull/11617

### PR DESCRIPTION
**Pull request by pkprzekwas**
**What this PR does / why we need it**:
Unblock reconciliation loop if default backup destination is not set

**Which issue(s) this PR fixes**:
Fixes #11833 

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Unblock etcd backup controller's reconciliation loop in case `defaultDestination` field is missing on Seed CR.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Nit: Can we give this a release note? It's gonna be a fix for the 2.21 backport.

File: pkg/controller/seed-controller-manager/backup/backup_controller.go [hunk 1]
```diff
@@ -236,7 +236,7 @@ func (r *Reconciler) reconcile(ctx context.Context, log *zap.SugaredLogger, conf
 
 	// the etcdbackup/etcdrestore controllers are enabled (at least for this seed), so we
 	// only perform cleanup for older clusters when needed
-	controllerEnabled := !seed.IsDefaultEtcdAutomaticBackupEnabled()
+	controllerEnabled := seed.IsEtcdAutomaticBackupEnabled()
```
Comment (pkprzekwas) [inline pkg/controller/seed-controller-manager/backup/backup_controller.go]: This part was very misleading to me. Better name to the variable before the change would be `controllerDisabled` and I don't fully understand what this was trying to achieve.

Comment (pkprzekwas) [reply pkg/controller/seed-controller-manager/backup/backup_controller.go]: Now, if the cluster is deleted and controller is running, it schedules cleanup job.

Comment (embik) [reply pkg/controller/seed-controller-manager/backup/backup_controller.go]: Wait, I think there's something wrong here. I believe this is an old backup controller and that is why it was checking for the "automatic backup" to be _disabled_, since it shouldn't run when the new one is enabled. I think this shouldn't change.

Comment (pkprzekwas) [reply pkg/controller/seed-controller-manager/backup/backup_controller.go]: Oh, now it makes more sense to me. Let me fix this.

**Review by embik — APPROVED** [review]
/approve
