### PR TITLE
fix policy template selector targeting with empty target selectors

### LINKED ISSUE #15143: empty selector for policy templates should select all clusters when specified
### What happened?
There seems to be a bug when using the selector for clusters when applying policy templates with `target` field set. The bug is only hit when you specify `target: {}`, it it expected that when you specify that all resources are selected inside the specific project (if the policy template has `Project` visibility) or globally (if the template has `Global` visibility).

### Expected behavior

When creating a policy template with `Global` or `Project` visibility and adding `target: {}` all resources should be selected. Creating one without target works fine though, it seems the bug is hit because target is treated as nil in Go.

### How to reproduce the issue?

Create a PolicyTemplate with `target: {}`, you will find that it will not apply to all clusters within the project or globally.

### How is your environment configured?

- KKP version: 2.28
- Shared or separate master/seed clusters?: N/A

### What cloud provider are you running on?

Not an issue that is Cloud Provider specific.

### What operating system are you running in your user cluster?

This issue is not OS specific.

### Additional information

The selector works fine if the `target` field is added with the specified clusterselector or projectselector, it will not apply only in cases when `target: {}`. Also when no target is specified it will also work fine (it will treat it as an empty selector, which will apply to all resources).

### PR DESCRIPTION
**Pull request by adoi**
**What this PR does / why we need it**:
This PR fixes a bug in the default policy controller where policy templates with `target: {}` (empty target object with nil selectors) were incorrectly excluded from cluster targeting, preventing PolicyBindings from being applied.

**Which issue(s) this PR fixes**:

Fixes #15143

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix policy template selector targeting with empty target selectors.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/ee/default-policy-controller/controller.go [hunk 1]
```diff
@@ -272,7 +272,7 @@ func (r *Reconciler) handleGlobalWithTarget(ctx context.Context, cluster *kuberm
 		// Global + Target [ClusterSelector]
 		return handleGlobalClusterSelectorOnly(cluster, template)
 	default:
-		return false
+		return true
```
Comment (kron4eg) [inline pkg/ee/default-policy-controller/controller.go:275]: That will make a cluster without project or cluster selector a targeted cluster, isn't it?

Comment (adoi) [reply pkg/ee/default-policy-controller/controller.go:275]: Yes, and it should. If the visibility is `Global` and there is no further targetting with selectors, it should always target all clusters.
