### PR TITLE
Fix project spam / Prevent reconciliation race condition

### LINKED ISSUE #10238: master-ctrl-mgr is spamming the logs
### What happened?
The KKP master-ctrl-mgr is logging endlessly that it is throttling itself:

```
I0704 11:00:40.162187       1 request.go:533] Waited for 994.826141ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/khl9dl5ww6](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/khl9dl5ww6)
I0704 11:00:40.212345       1 request.go:533] Waited for 996.108969ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/fdq97nnpkt](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/fdq97nnpkt)
I0704 11:00:40.262973       1 request.go:533] Waited for 994.084106ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/bhjxf2rkkq](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/bhjxf2rkkq)
I0704 11:00:40.312919       1 request.go:533] Waited for 995.155977ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/rqqgjn8krd](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/rqqgjn8krd)
I0704 11:00:40.362893       1 request.go:533] Waited for 995.660161ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/rqfg22tvvp](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/rqfg22tvvp)
I0704 11:00:40.413114       1 request.go:533] Waited for 993.050537ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/f7hkv9t69r](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/f7hkv9t69r)
I0704 11:00:40.462300       1 request.go:533] Waited for 992.304389ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/f6ftmknwsj](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/f6ftmknwsj)
I0704 11:00:40.513170       1 request.go:533] Waited for 996.262182ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/t6grwvrh7p](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/t6grwvrh7p)
I0704 11:00:40.562788       1 request.go:533] Waited for 995.034251ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/cjf48fzv99](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/cjf48fzv99)
```

This indicates some issue. Why is this only happening for projects?

### Expected behavior
No spam in the controller logs.

### How to reproduce the issue?
`kubectl -n kubermatic logs -f kubermatic-master-...`

### How is your environment configured?

- KKP version: master branch
- Shared or separate master/seed clusters?: both

### PR DESCRIPTION
**Pull request by xrstf**
**What does this PR do / Why do we need it**:
This PR started out as a follow-up to #8458: currently our master-ctrl-mgr is logging endless amounts of 

> I0704 11:00:40.462300       1 request.go:533] Waited for 992.304389ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/f6ftmknwsj](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/f6ftmknwsj)
> I0704 11:00:40.513170       1 request.go:533] Waited for 996.262182ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/t6grwvrh7p](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/t6grwvrh7p)
> I0704 11:00:40.562788       1 request.go:533] Waited for 995.034251ms due to client-side throttling, not priority and fairness, request: GET:[https://10.47.240.1:443/apis/kubermatic.k8c.io/v1/projects/cjf48fzv99](https://10.47.240.1/apis/kubermatic.k8c.io/v1/projects/cjf48fzv99)

The original fix for a flaky test made it so that we're using an APIReader instead of a cached client. I want to investigate whether we can solve this better.

---

So I learned that a controller that watches objects can be triggered about changes _before_ the cache has been updated. This is generally not a problem as we never really watch an Object X and then, during the reconciliation, _change_ Object X, too (except for the Status).

However we do have a bunch of controllers that replicate/mirror objects from the master cluster to all seeds. When those controllers accidentally read an older version of a resource and then attempt to copy that old version to a seed, everything is still fine. But when master and seed cluster are the same, then the controller will suddenly overwrite an object with itself, undoing the actual changes.

Using an API reader is a valid solution, but leads to the log spam above. This PR instead adds an UID check, which will make the controller never overwrite the object it was triggered by. This is also not perfect, but at least no more log spam?

I applied the same fix to all the controllers that replicate the same behaviour. In the future we might build a generic function, now that we have Go 1.18.

Fixes #10238

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go [hunk 1]
```diff
@@ -115,6 +116,16 @@ func (r *reconciler) reconcile(ctx context.Context, log *zap.SugaredLogger, requ
 	}
 
 	err := r.syncAllSeeds(log, applicationDef, func(seedClient ctrlruntimeclient.Client, appDef *appskubermaticv1.ApplicationDefinition) error {
+		seedDef := &appskubermaticv1.ApplicationDefinition{}
+		if err := seedClient.Get(ctx, ctrlruntimeclient.ObjectKeyFromObject(appDef), seedDef); err != nil && !apierrors.IsNotFound(err) {
+			return fmt.Errorf("failed to fetch ClusterTemplate on seed cluster: %w", err)
```
Comment (lsviben) [inline pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go]: NIT: a few error messages have ClusterTemplate instead of the proper name

Comment (xrstf) [reply pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go]: Not a nit, but a real issue. Fixed now.
