### PR TITLE
fix: overwriting etcd backup images

### LINKED ISSUE #14351: The "docker.io/d3fk/s3cmd" image is not available when activating the automatic etcd backup
### What happened?
Within air-gapped environments and while activating the automatic etcd backup it fails to pull the needed image "docker.io/d3fk/s3cmd".

See ref: 
https://github.com/kubermatic/kubermatic/blob/release/v2.27/pkg/defaulting/configuration.go#L705
and 
https://github.com/kubermatic/kubermatic/blob/release/v2.27/pkg/defaulting/configuration.go#L730

The Kubermatic-installer "mirror-images" command option does not cover this needed image.

### Expected behavior
The Kubermatic-installer "mirror-images" command option should cover this image.

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by mohamed-rafraf**
**What this PR does / why we need it**:

This PR fixes the issue where etcd backup container images were not being overwritten in air-gapped environments. It ensures that all image references respect the configured private registry settings. With this change, users can now reliably override image paths for air-gapped setups.

**Which issue(s) this PR fixes**:

Fixes #14351

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Ensure that etcd backup images are pulled from the overwrite Registry in air-gapped environments
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by iakmc — APPROVED** [review]
/approve

File: pkg/resources/data.go [hunk 1]
```diff
@@ -199,11 +199,13 @@ func (td *TemplateDataBuilder) WithEtcdLauncherImage(image string) *TemplateData
 }
 
 func (td *TemplateDataBuilder) WithEtcdBackupStoreContainer(container *corev1.Container) *TemplateDataBuilder {
+	container.Image = registry.Must(td.data.RewriteImage(container.Image))
```
Comment (moadqassem) [inline pkg/resources/data.go]: But this means, if I add a custom job, the container image will be overwritten unconditionally which is not a desired behavior. Or am I overlooking something here ?

Comment (mohamed-rafraf) [reply pkg/resources/data.go]: @moadqassem the Image will be overwritten only if we have an overwriteRegistry. If the overwriteRegistry is empty, the RewriteImage function will keep the same reference!

Comment (moadqassem) [reply pkg/resources/data.go]: Sure, the custom script must have a higher priority. Meaning, before you set the container image, I would say you should check if you are using the default backup job or not. If the default one is used then override the image but if it is not then I would say we should take whatever the user has opted in.

Comment (moadqassem) [reply pkg/resources/data.go]: Here is an example, I am using the overwrite image functionality, however I also would like to customize the backup job to address different things. Now, if I use a different image because of some special situation(backup image comes from a different source) then I would choose the override image that I set in the KubermaticConfigs or in the Seed unconditionally

Comment (xrstf) [reply pkg/resources/data.go]: So this PR boils down to a documentation issue: should the image rewriter be applied to customized backup containers. Rafraf seems to be in favor, Moath seems to be against, I don't really have a strong opinion.

I think it's correct that we do replace the image in the container, especially if it's the default container. For a customized container I could see both variants (rewriter still being applied, or not), with the "do not apply rewriter to customized containers" being more flexible in the long run, I guess.

> I would say you should check if you are using the default backup job or not

Yeah this might be necessary to decide if we rewrite or not.

Comment (mohamed-rafraf) [reply pkg/resources/data.go]: I updated the code to only rewrite the default settings. If the user uses his customized settings, he must take care of the image source

File: pkg/resources/data.go [hunk 2]
```diff
@@ -199,11 +199,17 @@ func (td *TemplateDataBuilder) WithEtcdLauncherImage(image string) *TemplateData
 }
 
 func (td *TemplateDataBuilder) WithEtcdBackupStoreContainer(container *corev1.Container) *TemplateDataBuilder {
+	if td.data.KubermaticConfiguration() != nil && td.data.KubermaticConfiguration().Spec.SeedController.BackupStoreContainer == "" {
+		container.Image = registry.Must(td.data.RewriteImage(container.Image))
+	}
```
Comment (xrstf) [inline pkg/resources/data.go]: Conceptually this is correct I think, but personally I find it a bit ugly. Technically this function (WithEtcdBackupStoreContainer) doesn't know or care where the container is coming from, it just gets passed into this function. However with this PR suddenly the function also has knowledge about the KubermaticConfiguration and how and where custom containers are configured in there, even though this logic should be part (and is part) of the controller code.

IMHO a nicer way would be to change the WithEtcdBackupStoreContainer function to be `WithEtcdBackupStoreContainer(container *corev1.Container, rewriteImage bool)`, and then in the controller

```
storeContainer, customized, err := getBackupStoreContainer(config, seed)
if err != nil {
	return nil, fmt.Errorf("failed to get etcd backup store container: %w", err)
}

return resources.NewTemplateDataBuilder().
	....
	WithEtcdBackupStoreContainer(storeContainer, customized).
	....
	Build(), nil


func getBackupStoreContainer(...) (container, bool, error) {
	....
}
```

**Comment by moadqassem** [comment]
I think @xrstf needs to review his comments ;)

**Review by xrstf — APPROVED** [review]
/approve
