### PR TITLE
replace label handling with loop and spec comparison

### LINKED ISSUE #1442: User cannot be created invalid: metadata.labels
One of our customers cannot create any clusters. After logging in to the dashboard via the openstack authentication he receives this error:  

`
"User.kubermatic.k8s.io "user-dtql6" is invalid: metadata.labels: Invalid value: "-rRUWaeIDhikDyrv3-IACPqmfXc": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"
`

The user does not get created. It looks like a problem with the labels for the  id field.

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
replace label handling with loop and spec comparison

Fixes #1442

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: api/pkg/provider/kubernetes/user.go [hunk 1]
```diff
@@ -32,29 +34,40 @@ type UserProvider struct {
 
 // UserByEmail returns a user by the given email
 func (p *UserProvider) UserByEmail(email string) (*kubermaticv1.User, error) {
-	selector := labels.SelectorFromSet(map[string]string{userEmailLabelKey: kubernetes.ToLabelValue(email)})
-	users, err := p.userLister.List(selector)
+	users, err := p.userLister.List(labels.Everything())
```
Comment (p0lyn0mial) [inline api/pkg/provider/kubernetes/user.go:34]: Do you think it would be okay to call the API directly in case of an error ?

File: api/pkg/provider/kubernetes/user.go [hunk 2]
```diff
@@ -32,29 +34,40 @@ type UserProvider struct {
...
 	user.Spec.Name = name
 	user.Spec.ID = id
 	user.Spec.Projects = []kubermaticv1.ProjectGroup{}
 
-	return p.client.KubermaticV1().Users().Create(&user)
+	createdUser, err := p.client.KubermaticV1().Users().Create(&user)
+	if err != nil {
+		return nil, err
+	}
+	return createdUser, wait.Poll(1*time.Millisecond, 5*time.Second, func() (done bool, err error) {
```
Comment (p0lyn0mial) [inline api/pkg/provider/kubernetes/user.go]: > Do you think it would be okay to call the API directly in case of an error ?

If yes then we could remove `wait.Poll` :)

File: api/pkg/handler/cluster_test.go [hunk 3]
```diff
@@ -744,14 +736,14 @@ func TestCreateClusterEndpoint(t *testing.T) {
...
+			ExpectedResponse:                   `{"metadata":{"name":"%s","creationTimestamp":null,"labels":{"worker-name":""},"ownerReferences":[{"apiVersion":"kubermatic.k8s.io/v1","kind":"Project","name":"myProjectInternalName","uid":""}]},"spec":{"cloud":{"dc":"do-fra1","fake":{"token":"dummy_token"}},"clusterNetwork":{"services":{"cidrBlocks":null},"pods":{"cidrBlocks":null},"dnsDomain":""},"version":"1.9.7","masterVersion":"","humanReadableName":"keen-snyder","workerName":"","pause":false},"address":{"url":"","externalName":"","kubeletToken":"","adminToken":"","ip":""},"status":{"lastUpdated":null,"health":{"apiserver":false,"scheduler":false,"controller":false,"machineController":false,"etcd":false,"lastTransitionTime":null},"lastDeployedMasterVersion":"","rootCA":{"key":"","cert":""},"apiserverCert":{"key":"","cert":""},"kubeletCert":{"key":"","cert":""},"apiserverSshKey":{"privateKey":"","publicKey":""},"serviceAccountKey":"","namespaceName":"%s","userName":"","userEmail":"john@acme.com"}}`,
```
Comment (p0lyn0mial) [inline api/pkg/handler/cluster_test.go:746]: i have just realised that `newCreateClusterEndpoint` does't call `convertInternalClustersToExternal` method - could you please update that ?

File: api/pkg/provider/kubernetes/user.go (hunk 1 above)
Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: I would like to reduce the number of API calls as much as possible as we use this function in a middleware which always gets executed

Comment (p0lyn0mial) [reply api/pkg/provider/kubernetes/user.go:34]: we would only call the API if the value is not present in the cache. I think that if we would leave it as is the following scenario can happen:

1. We call `user.Create`
2. We wait `wait.Poll`

as we wait the client resends the request and we:

1. Read the value from the cache - not present
2. We call `user.Create`
3. We wait `wait.Poll`

Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: Good point!, i'll fix

File: api/pkg/handler/cluster_test.go (hunk 3 above)
Comment (mrIncompetent) [reply api/pkg/handler/cluster_test.go:746]: Done in https://github.com/kubermatic/kubermatic/pull/1511/commits/85e3b9911811f12aa83f7740593092eac431bbe5

File: api/pkg/provider/kubernetes/user.go (hunk 1 above)
Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: One issue i found with this:
As we use `generateName` to create the user, we don't have a `name` yet. Therefore we cannot do a `GET` request to the API. Since we moved away from the labels, we would need to list all existing users.

Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: I changed the logic:
- We call `user.Create`
- We wait `wait.Poll`

Second request comes in:
- We call `user.Create`
- We get `AlreadyExists` from the API
- We wait `wait.Poll`

File: api/pkg/handler/cluster.go [hunk 4]
```diff
@@ -94,7 +94,7 @@ func newCreateClusterEndpoint(sshKeyProvider provider.NewSSHKeyProvider, cloudPr
 		if err != nil {
 			return nil, kubernetesErrorToHTTPError(err)
 		}
-		return newCluster, nil
+		return convertInternalClusterToExternal(newCluster), nil
```
Comment (p0lyn0mial) [inline api/pkg/handler/cluster.go]: this is nice :) 

Could you please update `newGetCluster` and `newUpdateCluster` to use this function ?

File: api/pkg/provider/kubernetes/user.go (hunk 1 above)
Comment (p0lyn0mial) [reply api/pkg/provider/kubernetes/user.go:34]: we use the `email` address to determine if the user exists in our system not the `name`. We use `generateName` just to create a unique object in the database. What do you think ?

Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: > we use the email address to determine if the user exists in our system not the name. We use generateName just to create a unique object in the database.

Thats correct

> What do you think ?

About what? :thinking: 
If you propose to take the email as `metadata.Name`, that won't work as an email is not a valid `metadata.Name`

Comment (p0lyn0mial) [reply api/pkg/provider/kubernetes/user.go:34]: I'm not sure if we are on the same page but I think that the flow we have in our system is:

1. On each request (`userSaverMiddleware` middleware) we check if the authenticated user exists in our system by calling `UserByEmail` which in turn reads the data from the `cache` and checks the email address.
 
2. If the user doesn't exist we create a `User` object with a random`*` name and call `KubermaticV1().Users().Create`

when the second request arrives and the cache is stale we will go to `2` - in particular we will create a new object give it a random`*` name and call `KubermaticV1().Users().Create` which will not return `AlreadyExists` error because the generated name will be unique. 

`*` yes, I know that the random name is actually generated by `kube-API`

Comment (mrIncompetent) [reply api/pkg/provider/kubernetes/user.go:34]: You are completely right - we will never get a `AlreadyExists` error.
I'll change the code as you suggested

**Comment by mrIncompetent** [comment]
@kdomanski @alvaroaleman sorry, screwed up the rebase & you got assigned due to code-owners. 
No need to have more than one reviewer here

File: api/pkg/provider/kubernetes/user.go [hunk 5]
```diff
@@ -32,24 +31,36 @@ type UserProvider struct {
...
+		return nil, err
+	}
+
+	for _, user := range users {
+		if strings.ToLower(user.Spec.Email) == strings.ToLower(email) {
+			return user.DeepCopy(), nil
+		}
+	}
+
+	// In case we could not find the user from the lister, we get all users from the API
```
Comment (p0lyn0mial) [inline api/pkg/provider/kubernetes/user.go:45]: thanks for the comment !

**Review by p0lyn0mial — APPROVED** [review]
and your imports look good :P
