### PR TITLE
fix: make local kind installer idempotent

### LINKED ISSUE #15539: kubermatic-installer local kind command is not idempotent
### What happened?

Running the `kubermatic-installer local kind` command more than once results in the following error:
```
INFO[0000] Creating kind cluster "kkp-cluster"…         
INFO[0000] Kind cluster "kkp-cluster" already exists, skipping creation... 
INFO[0000] Kind cluster ready, continuing configuration… 
INFO[0000] Installing KubeVirt…                         
INFO[0001] Installing KKP at 192.168.178.55.nip.io…     
FATA[0001] Service "nodeport-proxy-kind" is invalid: spec.ports[0].nodePort: Invalid value: 30652: provided port is already allocated
```

Relates to #15185
Discovered by #15440

### Expected behavior

The `kubermatic-installer local kind` command should be idempotent.

### How to reproduce the issue?

Run the `kubermatic-installer local kind` command multiple times.

### How is your environment configured?

- KKP version: v2.30.0-rc.0 (CE)
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

The example manifest from the KKP 2.29 release with `spec.api.dockerTag` set to `NA` (due to local build).

### What cloud provider are you running on?

None (kind v0.31.0)

### What operating system are you running in your user cluster?

kind v0.31.0 container

### Additional information

As a workaround, before re-running the kubermatic-installer, delete the `nodeport-proxy-kind` Service within the `kubermatic` namespace as follows:
```sh
kubectl -n kubermatic delete service nodeport-proxy-kind
```

### PR DESCRIPTION
**Pull request by mgoltzsche**
**What this PR does / why we need it**:

Don't attempt to create the `nodeport-proxy-kind` Service when it already exists. Check for its existance explicitly upfront instead of relying on the 409/AlreadyExists response handling since, in case of a NodePort Service, the k8s endpoint rejects the resource with a validation error if the port is already taken, even if it is taken by the same resource that is submitted.

Relates to #15185

**Which issue(s) this PR fixes**:

Fixes #15539

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix idempotency of local kind installer
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by mohamed-rafraf — APPROVED** [review]
/approve
/lgtm

File: cmd/kubermatic-installer/cmd_local.go [hunk 1]
```diff
@@ -232,6 +232,9 @@ func localKind(logger *logrus.Logger, dir string) (ctrlruntimeclient.Client, con
 }
 
 func ensureResource(kubeClient ctrlruntimeclient.Client, logger *logrus.Logger, o ctrlruntimeclient.Object) {
+	if err := kubeClient.Get(context.Background(), ctrlruntimeclient.ObjectKeyFromObject(o), o); err == nil {
```
Comment (buraksekili) [inline cmd/kubermatic-installer/cmd_local.go:235]: This Get call mutates the original `o` template in memory.
What do you think about creating a deepcopy of the object before running Get, to ensure we do not modify the object passed to the function?

```go
key := ctrlruntimeclient.ObjectKeyFromObject(o)

existing := o.DeepCopyObject().(ctrlruntimeclient.Object)
if err := kubeClient.Get(context.Background(), key, existing); err == nil {
  return
}
```

Comment (mgoltzsche) [reply cmd/kubermatic-installer/cmd_local.go:235]: While I also prefer pure functions without side effects in general, this method already uses the provided object pointer for resource creation without copying the object and currently none of the objects provided to the `ensureResource` method are used anywhere else afterwards. Therefore unmarshalling the resource from the cluster into the provided object shouldn't be a problem.
