### PR TITLE
(fix): Parse overrides for knp components during reconciliation

### LINKED ISSUE #14204: Cannot configure resources for Konnectivity agents and server
### What happened?

Currently, setting resources is not doable for konnectivity server and agents.

When I try to override `resources` configurations for konnectivity deployments, controllers do not respect the configuration specified in CRs; instead, they continue using the default resources configuration.

### Expected behavior

Setting 
-`.spec.componentsOverride.konnectivityProxy.resources` field in Cluster should update konnectivity agent deployed in user cluster
- `.spec.defaultComponentSettings.konnectivityProxy.resources` field in Seed should update konnectivity server deployed in the seed cluster

### How to reproduce the issue?

Try setting the fields mentioned above and check resources allocated for KNP deployments. The overridden resources will not be reflected.

### How is your environment configured?

- KKP version: 2.27.0
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by buraksekili**
**What this PR does / why we need it**:

This PR fixes bug in the reconciliation logic of KNP deployments (agent and server) to respect overrides specified in [ComponentSettings](https://docs.kubermatic.com/kubermatic/v2.27/references/crds/#componentsettings)

**Which issue(s) this PR fixes**:

Fixes #14204

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fixes a bug that prevents configuring `resources` in KNP deployments.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/user-cluster-controller-manager/resources/reconciler.go [hunk 1]
```diff
@@ -1054,8 +1054,10 @@ func (r *reconciler) reconcileDeployments(ctx context.Context, data reconcileDat
 	}
 
 	if r.isKonnectivityEnabled {
+		kResourcesOverrides := resources.GetOverrides(data.cluster.Spec.ComponentsOverride)
```
Comment (cnvergence) [inline pkg/controller/user-cluster-controller-manager/resources/reconciler.go]: nit: would we prefer having the names as konnectivityResources instead of kResources?

**Review by cnvergence — COMMENTED** [review]
looks good to me overall 
I have just left one small comment

File: pkg/controller/user-cluster-controller-manager/resources/reconciler.go (hunk 1 above)
Comment (buraksekili) [reply pkg/controller/user-cluster-controller-manager/resources/reconciler.go]: sounds good to me! i renamed the variable in 13eba87cf01e6e2777dea21137e2e391b9025b78

**Review by cnvergence — APPROVED** [review]
/approve

**Comment by embik** [comment]
@buraksekili this looks like a change that we should backport to previous releases. Do you need help in doing that? Ping me if you do.
