### PR TITLE
fix: Add exclusions to immutable values validation in Cilium

### LINKED ISSUE #12802: `ApplicationInstallation` "cilium" fails to update immutable value`spec.values.ipam`
### What happened?

During a KKP 2.23.6 to 2.24.0-beta.1 upgrade the following issue was observed in the seed-controller-manager log. The cluster in question is a 1.26.9 cluster with Cilium 1.13.8 as CNI:

```json
{"level":"error","time":"2023-10-31T11:02:01.926Z","caller":"controller/controller.go:266","msg":"Reconciler error","controller":"kkp-cni-application-installation-controller","object":{"name":"c5cnp55hxx"},"namespace":"","name":"c5cnp55hxx","reconcileID":"08f35f5c-3696-4698-8e2e-6f461ec70bda","error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 371461d4-fb17-46cf-8111-3952fdd89fbe denied: [spec.values.cni: Invalid value: map[string]interface {}{\"chainingMode\":\"portmap\", \"exclusive\":false}: value is immutable spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDR\":\"172.25.0.0/16\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]","errorCauses":[{"error":"failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation \"kube-system/cilium\": admission webhook \"applicationinstallations.apps.kubermatic.k8c.io\" denied the request: ApplicationInstallation validation request 371461d4-fb17-46cf-8111-3952fdd89fbe denied: [spec.values.cni: Invalid value: map[string]interface {}{\"chainingMode\":\"portmap\", \"exclusive\":false}: value is immutable spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"24\", \"clusterPoolIPv4PodCIDR\":\"172.25.0.0/16\", \"clusterPoolIPv4PodCIDRList\":[]interface {}{\"172.25.0.0/16\"}}}: value is immutable]"}]}
```

The "current" values for this field are:

```yaml
    ipam:
        operator:
          clusterPoolIPv4MaskSize: "24"
          clusterPoolIPv4PodCIDR: 172.25.0.0/16
 ```
 
And now KKP tries to override this to set the new `clusterPoolIPv4PodCIDRList`, but apparently it is immutable. 

It looks like this was changed in #12561.

### Expected behavior

Upgrade works without Cilium system application failing to reconcile.

### How to reproduce the issue?

As per the description above, create a user cluster with Cilium 1.13 on KKP 2.23.6, then upgrade to KKP 2.24.0-beta.1.

### How is your environment configured?

- KKP version: 2.24.0-beta.1
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

### Additional information

The PR mentions that the fields were deprecated and removed in Cilium 1.14. I haven't even tried to upgrade to Cilium 1.14 as part of this testing, because it breaks before. But that is another case that needs to be considered, especially in how to handle those fields and their immutability (?).

### PR DESCRIPTION
**Pull request by cnvergence**
**What this PR does / why we need it**:
This PR allows for specifying allowlist for fields in immutable values validation webhook.
It will help to unblock Cilium upgrade scenarios, whenever:
- new setting was introduced in restricted values
- some of the settings were deprecated

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubermatic/kubermatic/issues/12802

**What type of PR is this?**

/kind bug
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/cni/cilium/cilium_test.go [hunk 1]
```diff
@@ -144,6 +144,32 @@ func TestValidateCiliumValuesUpdate(t *testing.T) {
...
+		},
+		{
+			name: "Modified immutable nested value in ipam",
+			testValuesModifier: func(values map[string]any) {
+				ipam := values["ipam"].(map[string]any)
+				op := ipam["operator"].(map[string]any)
+				op["clusterPoolIPv4PodCIDRList"] = []string{"192.168.0.0/24"}
+			},
+			expectedError: "[spec.values.ipam: Invalid value: map[string]interface {}{\"operator\":map[string]interface {}{\"clusterPoolIPv4MaskSize\":\"16\", \"clusterPoolIPv4PodCIDRList\":[]string{\"192.168.0.0/24\"}}}: value is immutable]",
+		},
```
Comment (embik) [inline pkg/cni/cilium/cilium_test.go]: I don't understand this test. Don't we want to specifically _allow_ this? Why would we expect an error here?

File: pkg/cni/cilium/cilium.go [hunk 2]
```diff
@@ -353,13 +355,18 @@ func ValidateValuesUpdate(newValues, oldValues map[string]any, fieldPath *field.
...
 }
 
-func validateImmutableValues(newValues, oldValues map[string]any, fieldPath *field.Path, immutableValues []string) field.ErrorList {
+func validateImmutableValues(newValues, oldValues map[string]any, fieldPath *field.Path, immutableValues []string, excludedKeys []string) field.ErrorList {
 	allErrs := field.ErrorList{}
+	for _, exclusion := range excludedKeys {
+		if excludedKeyExists(newValues, strings.Split(exclusion, ".")...) {
+			return allErrs
+		}
+	}
```
Comment (embik) [inline pkg/cni/cilium/cilium.go]: Doesn't this completely skip the validation for the whole list of keys if any sub key is excluded? e.g. this is called with `immutableValues := []string{"cni", "ipam", "ipv6"}`, but since `excludedKeys := []string{"cni.chainingMode", "ipam.operator.clusterPoolIPv4PodCIDR"}` is set, it will find `ipam.operator.clusterPoolIPv4PodCIDR` in `newValues` and just return this function without validating _any_ keys configured as immutable?

**Review by embik — COMMENTED** [review]
Some questions I had while reading this PR.

File: pkg/cni/cilium/cilium_test.go (hunk 1 above)
Comment (cnvergence) [reply pkg/cni/cilium/cilium_test.go]: We only want to allow `clusterPoolIPv4PodCIDR` to unblock upgrade
This checks if the changes only to `clusterPoolIPv4PodCIDRList` are still blocked.

File: pkg/cni/cilium/cilium.go (hunk 2 above)
Comment (cnvergence) [reply pkg/cni/cilium/cilium.go]: That's a good concern, if we want to go that way, I also thought that we could validate each of them separately.

File: pkg/cni/cilium/cilium_test.go (hunk 1 above)
Comment (embik) [reply pkg/cni/cilium/cilium_test.go]: Okay, gotcha.

**Comment by embik** [comment]
@cnvergence please give this PR a proper description that documents the taken approach.

**Review by embik — APPROVED** [review]
/approve

**Comment by embik** [comment]
cc @wozniakjan also needs approval from you.

File: pkg/cni/cilium/cilium.go [hunk 3]
```diff
@@ -353,15 +355,24 @@ func ValidateValuesUpdate(newValues, oldValues map[string]any, fieldPath *field.
...
-func validateImmutableValues(newValues, oldValues map[string]any, fieldPath *field.Path, immutableValues []string) field.ErrorList {
+func validateImmutableValues(newValues, oldValues map[string]any, fieldPath *field.Path, immutableValues []string, excludedKeys []string) field.ErrorList {
 	allErrs := field.ErrorList{}
+	allowedValues := map[string]bool{}
+
 	for _, v := range immutableValues {
-		if fmt.Sprint(oldValues[v]) != fmt.Sprint(newValues[v]) {
+		for _, exclusion := range excludedKeys {
+			if strings.HasPrefix(exclusion, v) {
+				if excludedKeyExists(newValues, strings.Split(exclusion, ".")...) {
```
Comment (wozniakjan) [inline pkg/cni/cilium/cilium.go:370]: tiny nit for future improvement: maybe we can store exclusions as both `string` and then `[]string` to not have to `strings.Split` the same constant values every time a webhook is called

**Review by wozniakjan — APPROVED** [review]
/lgtm
/approve
