### PR TITLE
Augment REST mapper discovery with CRD information

### LINKED ISSUE #12186: Standalone master requires CRDs only installed on Seeds
### What happened?

When running a standalone master (as described in our documentation for large scale installation), KKP 2.22 runs into issues with the rbac-controller reporting `no matches for kind "Cluster" in version "kubermatic.k8c.io/v1"`.

An initial review of the code lets me believe that this is happening because the rbac-controller is using a REST mapper to discover information about some resource types, including the Cluster type:

https://github.com/kubermatic/kubermatic/blob/0ee7810a629ab4e3ec0568eae633e8b897155543/pkg/controller/master-controller-manager/rbac/sync_project.go#L112-L116

This no longer works in KKP 2.22 because #10903 stopped installation of the `Cluster` (and other) CRD(s) to master clusters. Only if master/seed are co-located on the same Kubernetes cluster this will continue to work.

### Expected behavior

Standalone master installations working properly.

### How to reproduce the issue?

- Install Master onto a Kubernetes cluster and do not install a Seed onto that same cluster.
- Install the first Seed into a second cluster.

### How is your environment configured?

- KKP version: v2.22.2
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

n/a

### What operating system are you running in your user cluster?

n/a

### Additional information

This can be worked around by installing the `Cluster` CRD (and potentially others) manually into the Master cluster.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
For some of our CRDs, we have the information that the rbac-controller needs (plural resource names) stored in the CRD information we compile into the code. The dynamic discovery via a REST mapper no longer properly works because some CRDs are only deployed onto Seeds.

Thus, this PR tries to discover information from CRDs before trying to dynamically discover them. This also prompted me to fix the last remains of `usersshkeies`, a plural for `UserSSHKeys` that only seems to exist in our tests at this point (I couldn't find any reference to it on dev).

**Which issue(s) this PR fixes**:

Fixes #12186

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Fix kubermatic-master-controller-manager trying to discover the `kubermaticv1.Cluster` resource type, which does not exist on standalone masters
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/master-controller-manager/rbac/utils.go [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+	"k8c.io/kubermatic/v2/pkg/crd"
+
+	"k8s.io/apimachinery/pkg/api/meta"
+	ctrlruntimeclient "sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+// getPluralResourceName returns the resource name we require to generate RBAC in rbac-controller.
+// If the resource type is part of our CRDs, it will be read from the CRD definition. As a fall back,
+// we try to dynamically discover it (e.g. for corev1 resources).
```
Comment (xrstf) [inline pkg/controller/master-controller-manager/rbac/utils.go]: Can we rephrase this a bit, as "read from the CRD defition" doesn't make it clear that this means the compile-time CRDs. Also the reason for why we do this double take is not mentioned. How about

```
// getPluralResourceName returns the plural resource name we require to generate RBAC in rbac-controller.
// If the resource type is part of our CRDs, it will be read from the compiled-in CRD definitions; otherwise
// we try to dynamically discover it (e.g. for corev1 resources).
// Relying on the compile-time CRDs allows this function to work even if the CRDs are not installed in the 
// cluster, which is the case for example for Clusters, which live on seeds, but for which RBAC has to be
// generated by the master-ctrl-mgr on the master cluster.
```

Comment (embik) [reply pkg/controller/master-controller-manager/rbac/utils.go]: done, thank you!
