### PR TITLE
[release/v2.21] Remove promtail sidecar from user cluster MLA that sets `fs.inotify.max_user_instances`

### LINKED ISSUE #11946: User cluster MLA still sets `fs.inotify.max_user_instances`
### What happened?

We removed a sidecar from `charts/logging/promtail` to stop inotify overrides on seed and master cluster nodes. However, this still happens in User Cluster MLA:

https://github.com/kubermatic/kubermatic/blob/e22a604b542516cdd40bf4c94a9e140d4eea6def/pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go#L93-L107

This is hardcoded to a very low `256`.

### Expected behavior

User cluster MLA doesn't override max user instances for inotify.

### How to reproduce the issue?

Enable user cluster MLA on a KKP installation, create a user cluster with logging enabled and check inotify limits.

### How is your environment configured?

- KKP version: v2.21.5 (.6 also affected)
- Shared or separate master/seed clusters?: n/a

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

n/a

### What operating system are you running in your user cluster?

n/a

### Additional information

This was reported via the Kubermatic community slack.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
We removed a `inotify` setting sidecar, but missed this one as part of user cluster MLA. This PR fixes that oversight. A fix for 2.22 and `main` is not necessary because we are using a different agent there.

**Which issue(s) this PR fixes**:

Fixes #11946

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Remove promtail sidecar from user cluster MLA that sets `fs.inotify.max_user_instances`
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go [hunk 1]
```diff
@@ -90,21 +86,7 @@ func DaemonSetCreator(overrides *corev1.ResourceRequirements, registryWithOverwr
...
-						"sh",
-						"-c",
-						fmt.Sprintf("sysctl -w fs.inotify.max_user_instances=%d", inotifyMaxUserInstances),
-					},
-					SecurityContext: &corev1.SecurityContext{
-						Privileged: pointer.BoolPtr(true),
-					},
-				},
-			}
+			ds.Spec.Template.Spec.InitContainers = []corev1.Container{}
```
Comment (wurbanski) [inline pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go:89]: is this required at all if we don't set up the initcontainer?

Comment (embik) [reply pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go:89]: I believe if we don't set it, the reconciling framework will use the previous values of the resource it finds within the cluster, so it will not remove the init container from existing DaemonSets.

Comment (wurbanski) [reply pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go:89]: gotchu, makes sense!
