### PR TITLE
Fix for auditLogging overwritting on Cluster level

### LINKED ISSUE #14141: auditLogging sidecar config is removed from the Cluster CR, if auditLogging is enabled in the Seed CR
### What happened?
A customer reported an issue related to overwriting a spec.
The ticket: https://support.kubermatic.com/a/tickets/7849?current_tab=details.
There is no sidecar field in the Seed CRD, but it is available in the Cluster CRD. However, if you enable auditLogging in the Seed CR, you cannot add a sidecar config in the Cluster CR, as it gets overwritten.
https://github.com/kubermatic/kubermatic/blob/8cabf43533aeec62294a68af27d3a0d81c520f1b/pkg/defaulting/cluster.go#L98-L103

### Expected behavior

We should be able to configure sidecar even auditLogging is enabled on the Seed level.

### How to reproduce the issue?

Add the following to the Seed CR:
```
auditLogging:
    enabled: true
```

As a result, the Cluster CR will look like this
```
apiVersion: kubermatic.k8c.io/v1
kind: Cluster
...
spec:
  auditLogging:
    enabled: true
```
In this case, there is no way to configure the sidecar.

### How is your environment configured?

- KKP version:
- Shared or separate master/seed clusters?:

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### PR DESCRIPTION
**Pull request by iakmc**
**What this PR does / why we need it**:
There is no sidecar field in the Seed CRD, but it is available in the Cluster CRD. However, if you enable auditLogging in the Seed CR, you cannot add a sidecar config in the Cluster CR, as it gets overwritten.

**Which issue(s) this PR fixes**:

Fixes #14141

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
It is now possible to configure the sidecar configuration for a given cluster while the auditLogging field is enabled at the Seed level. Previously, if the auditLogging field was enabled at the Seed level, it would override the same field at the Cluster level, resulting in the removal of the sidecar configuration.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

File: pkg/defaulting/cluster.go [hunk 1]
```diff
@@ -96,6 +96,10 @@ func DefaultClusterSpec(ctx context.Context, spec *kubermaticv1.ClusterSpec, tem
 
 	// Enforce audit logging
 	if datacenter.Spec.EnforceAuditLogging {
+		if spec.AuditLogging != nil {
+			spec.AuditLogging.Enabled = true
+		}
+
 		spec.AuditLogging = &kubermaticv1.AuditLoggingSettings{
 			Enabled: true,
 		}
```
Comment (embik) [inline pkg/defaulting/cluster.go]: I don't think this fixes the override that you are trying to fix, given that the second part of the if branch still completely overrides `spec.AuditLogging`. I think what you want to do is this:

```suggestion
		if spec.AuditLogging == nil {
		    spec.AuditLogging = &kubermaticv1.AuditLoggingSettings{}
		}
		spec.AuditLogging.Enabled = true	
```

**Review by embik — CHANGES_REQUESTED** [review]

File: pkg/defaulting/cluster.go (hunk 1 above)
Comment (iakmc) [reply pkg/defaulting/cluster.go]: good catch, thank you

**Review by embik — APPROVED** [review]
/approve
