### PR TITLE
Fix component health status shown during cluster creation

### LINKED ISSUE #3880: All components are marked as failed on cluster creation
Related to https://github.com/kubermatic/dashboard-v2/issues/717, all components (api server, etcd, machine controller,...) are marked as failed during cluster creation.

There already is some progress with this PR https://github.com/kubermatic/kubermatic/pull/3784. 
Nevertheless as said in the PR comments, there is space to improve.

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**:
Makes control plane appear as pending instead of failed until the cluster is fully initialized.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3880

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by zreigz — APPROVED** [review]
/lgtm
/approve

File: api/pkg/controller/seed-controller-manager/kubernetes/health.go [hunk 1]
```diff
@@ -4,10 +4,13 @@ import (
 	"context"
```
Comment (alvaroaleman) [inline api/pkg/controller/seed-controller-manager/kubernetes/health.go:4]: What about openshift?

Comment (floreks) [reply api/pkg/controller/seed-controller-manager/kubernetes/health.go:4]: Is there a separate endpoint for openshift? I thought only `ExtendedClusterHealth` is returned and it does not have openshift specific code.

Comment (alvaroaleman) [reply api/pkg/controller/seed-controller-manager/kubernetes/health.go:4]: This is not an endpoint, this is part of the `kubernetes` controller. The openshift controller has `syncHealth` for this, which needs a similiar change.

File: api/pkg/controller/seed-controller-manager/kubernetes/health.go [hunk 2]
```diff
@@ -60,5 +63,41 @@ func (r *Reconciler) syncHealth(ctx context.Context, cluster *kubermaticv1.Clust
...
+}
+
+func isClusterInitialized(cluster *kubermaticv1.Cluster) bool {
+	isInitialized := cluster.Status.HasConditionValue(kubermaticv1.ClusterConditionClusterInitialized, corev1.ConditionTrue)
+	// If was set to true at least once just return true
+	if isInitialized {
+		return true
+	}
+
+	_, success := helper.ClusterReconciliationSuccessful(cluster)
```
Comment (alvaroaleman) [inline api/pkg/controller/seed-controller-manager/kubernetes/health.go]: Thinking about this, we should also require the `kubermaticv1.ClusterConditionSeedResourcesUpToDate` condition which is excluded from `ClusterReconciliationSuccessful`, as the former checks if our controllers do the right thing and the latter check if the underlying seed realizes it. However from the APIs POV we don't care who does it, we only care if it was done

File: api/pkg/controller/seed-controller-manager/openshift/openshift_controller.go [hunk 3]
```diff
@@ -14,6 +14,7 @@ import (
 	openshiftresources "github.com/kubermatic/kubermatic/api/pkg/controller/seed-controller-manager/openshift/resources"
 	controllerutil "github.com/kubermatic/kubermatic/api/pkg/controller/util"
 	kubermaticv1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
+	"github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1/helper"
```
Comment (alvaroaleman) [inline api/pkg/controller/seed-controller-manager/openshift/openshift_controller.go]: Please alias this as `kubermaticv1helper`, because `helper` is a super generic name and to keep it consistent

File: api/pkg/crd/kubermatic/v1/cluster.go [hunk 4]
```diff
@@ -570,3 +571,11 @@ func (cluster *Cluster) GetSecretName() string {
 	}
 	return ""
 }
+
+func (cluster *Cluster) IsOpenshift() bool {
+	return cluster.Annotations["kubermatic.io/openshift"] != ""
```
Comment (alvaroaleman) [inline api/pkg/crd/kubermatic/v1/cluster.go:576]: Finally someone adds this, we should be using this everywhere instead of duplicating it

File: api/pkg/controller/seed-controller-manager/kubernetes/health.go [hunk 5]
```diff
@@ -4,10 +4,13 @@ import (
 	"context"
 	"fmt"
 
+	corev1 "k8s.io/api/core/v1"
+	"k8s.io/apimachinery/pkg/types"
+
 	kubermaticv1 "github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1"
+	"github.com/kubermatic/kubermatic/api/pkg/crd/kubermatic/v1/helper"
```
Comment (alvaroaleman) [inline api/pkg/controller/seed-controller-manager/kubernetes/health.go]: some comment wrt to aliasing the import

**Review by alvaroaleman — APPROVED** [review]
/lgtm
/approve
